apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: infra
  values:
    deployment:
      replicas: 1
    updateStrategy:
      type: Recreate
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    service:
      spec:
        type: ClusterIP
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443
    additionalArguments:
      - "--providers.kubernetescrd"
      - "--providers.kubernetesingress"
      - "--entrypoints.websecure.transport.respondingtimeouts.readtimeout=600s"
      - "--entrypoints.websecure.transport.respondingtimeouts.writetimeout=600s"
      - "--entrypoints.websecure.transport.respondingtimeouts.idletimeout=600s"
    persistence:
      enabled: false
    ingressRoute:
      dashboard:
        enabled: true
