apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
    namespace: linkwarden
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:praXPndRGFnf2IkjvYICVv4VFa610vP/GBbX2eaTAKcTk6fgFvq8grJH/oA=,iv:7bKELxxh4BYNUrslqEd1VViHDyq64hwv0zB57cPM9mU=,tag:raSdu+I2YhWZxyqrhbmIGg==,type:str]
    database-url: ENC[AES256_GCM,data:aJ5FZjimILZDvv2BcxfDRPXoPvUCphqOlhOm+yh1xXUJJGIICHDXHzDu4RaQIcj4uLqJuSqq7AOPp4PNUo5y4ei+zoExyrKMLu/t//8mb+0B4d2XERJi/p+5b7xKXJOtezup3HR2mswG5ITOaTJFKpnqSCNpZD+X46WXI3C8nL/uDl7Ilvg=,iv:sq7ANkTWl2WAKgjf3lkpCN2OlSaiO3G7M+STjT8i3wg=,tag:TUvbTU/pvvnNmiVbJH3g/g==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYzlwVkVGUXNCcG5jNmJE
            MXNxcTlMWkZ3RHZVLzYrMnR3dHdKOUNLQlRvCkZWVnZUV0hHN3h1bktVNG85S2Vt
            aUhaaVo0MDFQZFdaWG0ydXZtYUE5TjQKLS0tIFVZWjlGd3UxT1RZUUk1UTh6eGxF
            SE5TZmI0TzRZSi94ZExsaWpoem9wT0kK8/MjxD+oZRydSOqgTkRnzpuX4Pnp1WlV
            enZO2uTSn66XEIx+rpRI9atdMSWx+g0IRwnZSPIxpyEZpNfjLd7l9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T06:27:51Z"
    mac: ENC[AES256_GCM,data:HvW9eCCN97ty2tJgMrVmN2DmRKtHN4lJ3JW62MVJwXHZCcXXqiYeoPy4G3MjW+1lRh40uKVtIZLzK/SdZEwQnx9zUY+ESvZYv//O+ca7RAu1wPkMVFUbBrtGXVL7g/zLJhGuCEsLZLNLqj/WldWBH5qesl6wPmQTasrN57AoNU4=,iv:MRe+QUo4bFbGMjkleArIdarOq1JuUdTdkUdhhlsKRHk=,tag:3Fjq9YxjKrhE1AY+ukW+pA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
