apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
    namespace: linkwarden
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:6bxOwYaXT1UYEDxh17KbYlmqJOxHTkxGIwcUoePxh2qai93haQxBrkMl5ms=,iv:62Jue4iS3vvJNhrZzcHNX94/BdH5lqoet4Sbb2NJwUo=,tag:koGFmk0hZBoWtssr5IJl2w==,type:str]
    database-url: ENC[AES256_GCM,data:aM2SrYdPOifyqaiMMU0cofEix7IGnAFKZWURlV7Q9irrkPVye8qNhOeymuYVdRKCOMhAIRGdf/IAQ7ByEmvkGf8OWdJEi9i0xf0IhjqcCUUdrGYfaNUWOM2WLiW4t/iy5dzugWIwBeBkfQVNY2E7k7X1Rv9k+3IuOyjv24kKo1XMaQ==,iv:25DoZt+IQac4TxCSfLgIsKRecAH/STKhmLFeUh76Oak=,tag:oXOm5eZiM1urg+F927FLXQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMU1LSFRXM1F0U2cvZUhU
            R2ZlNmROTHJvaCt1Z1NrVytLblNjQlV0Z0JvCllkTlQrZ2tEeTZkd29Eb1FFeU1p
            djJ1cHpYdGVFajNDRUJuQVR4Z2NaWmcKLS0tIDVZYVlqNEYvRHQxUFlWSEROSnhz
            N0JZOUpUcnRXN1MyaG1nekpIVWFYek0KshPRm6ZzUXyBXdukqH/wEC06lSQwKZcw
            sPMsRqCzdiC+lZu5JRnAKpqcqWZjLffgcb8N8LmWwga1G99kRdWgiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T06:02:31Z"
    mac: ENC[AES256_GCM,data:s9hNOP3c6z9hwG0SXp6RFYJr1g02nWyAVs4gJ+9O+dXUmOi0STTN4noiWDV7urLGiojs/4esh+caDoXhtCwdPw6v1esnpp6iIWD+khB33W3LojKuhZufpXpbjRLWOcpBSVt9lINiHUJQPJHGvmRuF12j8GhNVJrxCi7+DjflkQA=,iv:30/88X3ehV4heP+CnVDW2KVofcnSFHXrTWSPXZ1KyOg=,tag:ZK9yS3tWk0n3pG9L3CQhaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
