apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-db-auth
    namespace: linkwarden
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nsMi42kIUq8INg==,iv:f82+V0+bySM44i30G57DfG+t8PKKHyXxLQjAz7cViDY=,tag:OzA7sx2GhZ5LE0exxNdgdg==,type:str]
    password: ENC[AES256_GCM,data:HtXQR2btxT8z1S31avUmUxOenX7PG44yugnr89NF/BjpzLl6MdVt7Pt3xD0=,iv:Y3FJRie+t4G6GsiXcfwmt8T4m14GPXjh1WXtVWr8mTg=,tag:ESW8eshHhn0q3cdKjRJGUw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVclk5UTZTU2p2OU95S2dX
            ZHp3SVF0cWdmWGZnTk9BMk9pWjdrVWRaVjFRCnc1U2JnTzZZdmszNHRYQ3VGZ05R
            dzRPakJSbE1qb1pUVStEVnRwWHlQdFEKLS0tIGJyV1VmOWlzUUtvVnpuTmVMYndZ
            MUhUdGNIamRENnBrQ1E2ZEpJUTZCaWMKw+92hEByo9NcDvFL4uUkdIUF+j1iO86b
            joAMMUdr9KbNAETWgs1cYfUtlPDDkzbgsXKLZwwqVcdsLKeDX0dFvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T06:02:27Z"
    mac: ENC[AES256_GCM,data:tnR9nVXm4hXhEtiFNHgvQlnb6W5FswGudVDWORYkeyLn+gb8zgFWc3iv6ZhnNisygyh59VEzM0JID332l8/GbdAF12SmJDFXdUiOd7h2XhkBXGMLjiJ1LdANyhDDylMKJ2mMk3E4JWi1fhhrHATCHRxogEuODSTpCdg3Ic0RCh0=,iv:OKZWrE6Wphl271XHK5q1WsfMGGastYYnqBLmFdYNqRA=,tag:i/aHGecAjMNkMBHfmqC8RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
