apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: home-assistant
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:z0Whky2fMnrdsHjGGAu5Np4+OaU5MREU6A==,iv:TWPDokysXtk3lIewBgyp8Z7TQFjL+lxYFDfJGSF3Tb0=,tag:pfCAteFEd6v8REFHVJihIg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:VQ9OyH55qjL5DFn//cER1giKGWKPYIyOhbZ0gDFvTg==,iv:mb2ocpfOOPJ2NgZDy1B+vOdjv8n1Y6/vXM4DC8UcvjM=,tag:TWAqG+jIrnvYiO1n2JQO1A==,type:str]
    REGION: ENC[AES256_GCM,data:WVfx4UVLcUU4BVi4g90=,iv:V4e5JN/S4bHTwXo1Owog9VoLqs+7aLKr5HYPRpmYn2Y=,tag:SoggQTK+5WxrCVj/l56HkQ==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:q2QMvZFuh7Gdgia+qU8kWVZ9ZCQPOgf92M7pa82d92vIHm9BJUHZGDs=,iv:/a55sFoAA/CNjsJs/lOuP+a5noUu4DXAqJmlKCN4+vM=,tag:oROAxJaF6hLntDHTm0hGwQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUVRVMWNJKzdnd05LY3cy
            RVJxK1ZudTFHUEFrTERBejkwRndJVVk1eGw4CldVdVo2NFVmMTliTVFBaUNidWlY
            N2c5Ulg5R3JzUmdZR0o4UU1PZE4vSGsKLS0tIEdhYnF0ejEwaVNneVZlaGxia0o2
            djRQSDlmdGxYQUJ5VjcyZ3BlTzFzSGcKKQYI5mIlWmgQgH8mdT0mGBOG2UTNyiIl
            z6221XAO+O8nx3t53ISNeBNK7EkwrNTm9g0OyCjvsjJGbnqTV3MWnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:33:36Z"
    mac: ENC[AES256_GCM,data:0PzAMZsn37+2KHRG0fUMtX6WFGEbpCOfAh8XlnEuF9UPGu3hlXOQLEdUkm7YPYV+6o3eDu+XWWj+C8GasS8g7O6OQ8/9Oe3OzKBXxxvT6QLUOvRg1nKnzgBjo19Hm0DC+1km4zEWtRFMDeGr2JS/6EJDbiyCi5EYLprg46iM56I=,iv:9uegDKFoL30O9CMFFoUjGPd1r4jW2HsCY7BsgZvm+A4=,tag:7f0KfuRadOv4zW9SgQEzfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
