apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    postgres_url: ENC[AES256_GCM,data:yKwoUo2Uc9WGXIhDcSw0SvecEdNMNWPEJ8DA8nLCAGU49IhmsFQEeDWQWrk/YDNGwuNRG7AaBwNAmQ44Pury5b4uSNHCzxNor2Wz6HrEwx/LbNOubGtGa532Cu8Fq2Kkx/fDG+h0jBXMsOMGZ1lLk9X0rdr96zwPyBK3aO1bZoMcfA==,iv:BLmWOp8oANkzfEdG7woszaPNTtNH6h+5QrBONTrXy+M=,tag:+e/asX85qLVJAsZVxtH3WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZmQ2N3k5NDE5QUZnVDVD
            emNtQytaSFdmdmJuT1pKSk9iRW5nZTJRM1F3ClZiMXdLSzBsUDVERXFwN2c1TkFk
            eDYwUmhqa0lVN0g1THJEdExZYk01WlUKLS0tIGRKUXJYYjFkUTdRNHNYQXVUYndi
            Sm9Db1BjdDUvdTQ1R1RXcm4vTnBKNDgKnMv4BN/rgzfZIaWc3wdBTmUhvuwmRGFl
            jn/whQhJRWNy2/h2VMlS2eyp5r7temUiEAVS8eabnhe/6AyV3YfiNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T15:59:28Z"
    mac: ENC[AES256_GCM,data:O8yxU3qL9Q+tWWSWEt4K0dy5fXR9raIhz7qBYWJY57DTMuxvnFoLeunsiCsKexuzSm8q7f02BDltcrkvQkTtwd0j/ZQxwHjxgsFGb7eZIKnPxg1WdYzsXKkDhX8/KWiOzP5vF5aBdFyPJ5NbwMAqg8iWhAYERtqNGdAiEPy4D20=,iv:jhdYsHGOipnJvYBEo4oRDZurEspeI2A0kwiNER/YGHc=,tag:ICfHewFqSyO5DhwvLicxCA==,type:str]
    version: 3.11.0
