apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    POSTGRES_URL: ENC[AES256_GCM,data:C/kJ5o+xujLmxpygmauxFL53F0bzle1ZqMfnleGCRKj/ezEKHCWP4Z555b/71Yj0ONmljoH6IuM70SgQTq50QaVBVWuE1nkSeQ98Cjy1UdgNCU7+OfEPco0yZN2J4cdevAyXi3RfVLMC13o/KIdtwRKOg524GoKpT9HNkQ==,iv:WT4BqVbbLXYZvWjdt+u9AGtHIWrFU88nGnWp76Pyjps=,tag:s3oQMC06qVlpvDSaGhL3UQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY3ZLVEptcVF0d1Vab2tz
            UWw0dThqdW11UUs5dCtTeDVSNHhXQXhoNmc4ClRyWlNrVGtVVUVVczUrVi9xOTZr
            N2RhTzY2cUF6bWdPdzZiK2NEenVxWE0KLS0tIHZaVVFmQnBaYSt2c3JLbjJCeUI4
            a1BWRVRNYXVyTE5TWHlJN1p6MWg2QmsK4Zc1j7KeD0xZr2AZs07d+mojGRMsQrDR
            gX1F38MxX65GDiXPhVvh47LsSP617JlQoo7kJNkhSHAgUSgAZuvnOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:41:46Z"
    mac: ENC[AES256_GCM,data:Q0H52TsD3NsUOHr/585nQRIK3FMuvIxj0idmzC7xZR9AU9/Lv6zR1X1GC5N35ybNjW96X39ZR/DZ5lCdy33B6xONNVsdvvHEhA3QKPp5fu4zPuvlX4prOxuuZnB+ghBlKMksZvrZQk0aqvlV98n2a9IAifboxiGQOrdjluYQeCo=,iv:U5O2/+MAMRfSy5VrgbmdWfF3lsB/VhtXFsrYph8oJE4=,tag:Os8U/KXi6GZmXUUGiAif4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
