apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    postgres_url: ENC[AES256_GCM,data:yKwoUo2Uc9WGXIhDcSw0SvecEdNMNWPEJ8DA8nLCAGU49IhmsFQEeDWQWrk/YDNGwuNRG7AaBwNAmQ44Pury5b4uSNHCzxNor2Wz6HrEwx/LbNOubGtGa532Cu8Fq2Kkx/fDG+h0jBXMsOMGZ1lLk9X0rdr96zwPyBK3aO1bZoMcfA==,iv:BLmWOp8oANkzfEdG7woszaPNTtNH6h+5QrBONTrXy+M=,tag:+e/asX85qLVJAsZVxtH3WQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTnZ1V1VnQU9PYThhLzBL
            dWJSRjFrS0ZXZlV4SGtjekVYbFo5MVZEQUdrCnIrUmk3M1BDM2tUSkVzZ1lNa1lF
            cFpKNWJNRXVPVWNaQ3FLMW43WTdZc00KLS0tIE10b3NwTy85NXI1ZktvcjhNdCt6
            NTZhYklaeXFVM2JCSTZjbWk3REJLOEEK/CBnz35dyWkI+DWd8UO/t0oT9JbzaR0m
            hU4VNiW1xEdnkNV+EGaoySABKsY1YP/Inmx/Vp4TShtzqt19T6o7ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T15:59:28Z"
    mac: ENC[AES256_GCM,data:O8yxU3qL9Q+tWWSWEt4K0dy5fXR9raIhz7qBYWJY57DTMuxvnFoLeunsiCsKexuzSm8q7f02BDltcrkvQkTtwd0j/ZQxwHjxgsFGb7eZIKnPxg1WdYzsXKkDhX8/KWiOzP5vF5aBdFyPJ5NbwMAqg8iWhAYERtqNGdAiEPy4D20=,iv:jhdYsHGOipnJvYBEo4oRDZurEspeI2A0kwiNER/YGHc=,tag:ICfHewFqSyO5DhwvLicxCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
