apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-nikitos-account
    namespace: home-assistant
type: Opaque
stringData:
    NIKITOS_USERNAME: ENC[AES256_GCM,data:yGZBwi8Kpw==,iv:gEMEjZeoqvC4uERkmI8J5gu9JmmPZNjIXvbsWvgIfmQ=,tag:+C5twP24I3ysfg3lGn/qSg==,type:str]
    NIKITOS_PASSWORD: ENC[AES256_GCM,data:iBNJlg5K4hbaJdxRCg==,iv:/a0Vq51Z57ZJfOflo2IM8Rjlyf8utCPGCnSeWqxvNjs=,tag:xP4xJZS3QSOasQb4la4yQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUWtkMFJuRkd4NW9uU2sx
            dUd5R1RkWkFOZm03QzlodkxudFo1RUNRcVJjCm96c1FkT1RpeU9mdVZCK0VYWGpm
            ZmFQU2NLYnFORmJ2L1dsRUU4TDJ1KzQKLS0tIHY3MExvNUxuYnB5SEdlN3J2WVJS
            bkpuNk1PQUswMUhkQmtRTlVnMjN1NzAK6xBx/E+DUSd9p2hgxecRk/TBLJuC0622
            9eTW4wBm4fHoUda+zaSauXUzslZswsbH3Sqm0AZqT5cL7SUlUxFJHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T11:25:05Z"
    mac: ENC[AES256_GCM,data:pXHj5XEpJBHirCDLIZgRmeKZHjGNnKkROb1rCo3GB/CgnqFwNYREf8I9afpq2bFHUGObRfdRKDMj4IxcWajW1n5y1YfTpYJFmolyguflklVQk9OxedJVuwBOOUv/FON2De2sGPn6fuWEE4PkdHVBpHXutnVg44jiO8+hjp7N/kw=,iv:K0bjWPZq1Qtt+MxGp96sCdx8Q+aCH8DuMZNPwE89/Tg=,tag:wDiVNmtXPFqCuasT2E7Dvw==,type:str]
    version: 3.13.2
