apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-auth
    namespace: home-assistant
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NEvdkQnpszkjChQQnA==,iv:cplvAxUckzL1Vhu8s+n60RzoaVupNOUE0TWaq2O/AXs=,tag:hkylriRSR/E/9oIB6FFHoA==,type:str]
    password: ENC[AES256_GCM,data:R9XQorsQ9AUWSMBY53zHj2FwOyZ2O/Xd,iv:tbU3JchkBoOcPj+rwjq60kFjmuQ7gFm+sWv5blEcO+g=,tag:KBc5Gr/RECqqi5pXxZSaVA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNytuSUFFWFMyYkh2YnhN
            cy9xNndialJkMzVMMU9YOEt0RldPSlFyeWxZCnZRMjNIeCtzRzdDUnlJU3BlMjYr
            aDI4UjlvWHdTUlU5Ty9kQ09YM0R2dmcKLS0tIDBaa1BNNHZzaGdvbmgrNWk3VUdn
            eExJMXd2cFQ5UG5kaFpCeXJ2Z01oZU0K5/6b/jOAoR5Q1hGJxyuUUCZMACLlonMD
            YesVEBCnuIjwFCG/ku7txRXSi4tQALVtx75xvimqW8XqyqzE+HyQkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:41:46Z"
    mac: ENC[AES256_GCM,data:0fA6eGn7GCzgY+Y/Yvis9ou2yK+/0E6aUzsiDNrZnNSRsib/j89pEINYPj15RgKVMA02papovf9PKvXOK3aErxVSCg6Lqu58pRaJ/I5ymrH+sou/gDHoNHiPLGNji0hUCPtUIHx3QKstiuSnbGEeGp5U9dh/XyxQ/Ywe42rU9+g=,iv:iBL7FpFUzbYGeM8N1a+cZBu1mSgTNuzUnt47qYwa3Ik=,tag:QV9+n6uPV+6Q4C5Q1SPO2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
