apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-auth
    namespace: home-assistant
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NEvdkQnpszkjChQQnA==,iv:cplvAxUckzL1Vhu8s+n60RzoaVupNOUE0TWaq2O/AXs=,tag:hkylriRSR/E/9oIB6FFHoA==,type:str]
    password: ENC[AES256_GCM,data:R9XQorsQ9AUWSMBY53zHj2FwOyZ2O/Xd,iv:tbU3JchkBoOcPj+rwjq60kFjmuQ7gFm+sWv5blEcO+g=,tag:KBc5Gr/RECqqi5pXxZSaVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeTMveU8xN0Vlclg0Z21E
            OVh4Vms0OGkyTXczd1QwRDBmUUcwd2tLSmxJCjZMbi9sd09JUU92Uk5iV0NJMVJG
            VHVKUDdLTHZPM2JOS2hDT2trQWhQSDQKLS0tIDZiWERtNG5lcGY1K2VXcGVjbCsr
            QVJsY2tPcndoeHNsMm01WlNCdDhIUmsKYIje0ITqgBERts+UEjtnKqSPnQP1u/77
            Qb9ZcPeiKbBgvhTPrGdNWr3CaKh+NB7IlPVW2ZPkCH59CExjuWzkWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T20:41:46Z"
    mac: ENC[AES256_GCM,data:0fA6eGn7GCzgY+Y/Yvis9ou2yK+/0E6aUzsiDNrZnNSRsib/j89pEINYPj15RgKVMA02papovf9PKvXOK3aErxVSCg6Lqu58pRaJ/I5ymrH+sou/gDHoNHiPLGNji0hUCPtUIHx3QKstiuSnbGEeGp5U9dh/XyxQ/Ywe42rU9+g=,iv:iBL7FpFUzbYGeM8N1a+cZBu1mSgTNuzUnt47qYwa3Ik=,tag:QV9+n6uPV+6Q4C5Q1SPO2g==,type:str]
    version: 3.11.0
