apiVersion: v1
kind: Secret
metadata:
    name: restic-credentials
    namespace: infra
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LJJmBz4HkXN7lHPtN8y2iw2+3rk6rLtywg==,iv:sDwhYN8guOXP/PWZIJ2416fznFKeGGlPqQ/2TkW9zsc=,tag:aLrcxhi84nhTSi3wCIFVUA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dWcJkG2LzNx0dlfUXnJY1CNJBKnd1vyoyuyU8I7pmA==,iv:mspES+Q/h+Q3gCw0I8junVD0+SUh/puVaynynZlJQA4=,tag:VnJhnsoMi7ouKR1mS6rvNw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:EMVioTQTnc4+KtK7GRo=,iv:9BSOgWJQXocdDN3uVn8eDZrAFXfLD/knjRP+Zyhcv2Y=,tag:Iq8kFvneZuGolIITWQuJBg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:t9pgnx+7rw+KNyYXvRshXhhzXD4XJeq1qkcrXvp+LeXr8sIvwUcWcXCYOPYHlS287pkkRg==,iv:DPsihHTvgJUdJ+RRE4iX6uZ2zu4GsfHNR54NpYRsAWU=,tag:3nUrVopa67OavVrCZPJb9Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:AzCTpJy4FJoytzqgsmzjiI4VIXb0vAwJjNQSow9Yd7O4UW9nNhlZBYcUfU/x5WCvNxDkkJ4Qhk/pS/wR9brMHw==,iv:wav4zaBZ/PEQX3bOStEBIw0hmmUnp7lAcB19Hpnu+Z0=,tag:kz5sLzxy075HLSo2AjLutw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMHVHbkluT2VxbWs4Nml6
            UndjaHhYWjFub084UVNHNjlLSndRNHdodEdVCjhHa05zM0J6YUJ6U09LcDBMUEhs
            Q3BQeGJxRjhBZzNSQ09rNFFMOGhaZUUKLS0tIHkzYmZ1RUNnRzNVNy9IbmxGQXli
            WWhhMzEyOUYzOTV4dktsR1BlallOejgK2PyaQKpAHipp72eQMuA2huOvTsTgiLeq
            Py+4XycKo7iIC9ngmP0FnHJa59MC1RBwO/wi0L1H7KiU0dY7nVr8hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T16:46:31Z"
    mac: ENC[AES256_GCM,data:1H1mhX8hG5ssx/95Iu7eC0lb9TKt+SP1L/UW8vAUUxsLDRdP5ScAsoKd24oDJsykZuQiSw17ENuleapYTg5TnCQn3JygKuUecCJTi9O5MCQ5pJkmCJFULaDBE9aUke5JHlbUl/y4Zyezh45hFqTpm4qwzG7tHeTyiWgbZ/ymf1o=,iv:rjW6OLzwXa0k8oDKrYdqfk7VsmB9se+jjb0tOyBlmfo=,tag:uSnszO7a831IBl9LMmuXHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
