apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-local
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: manual-local
  volumeName: perun-plex-config-local
