apiVersion: v1
kind: Secret
metadata:
    name: paperless-rag-secrets
    namespace: ai
type: Opaque
stringData:
    paperless-token: ENC[AES256_GCM,data:peR0eaywrRY=,iv:MCTvVayN9qOnlghkRFEld+tBwp97eOWYv7JhAPCX5r4=,tag:Uqtu/nuHUv/iucVQADcg5g==,type:str]
    open-webui-api-key: ""
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOVQ1aFVVMjJjU0xjN2dt
            elphb3Z1MWFKVkhNT0g0QTluY0lYTnhvbDJJCmtsMFBZekZWSjIyN09qb3hBZDk5
            aG80K3R2T1JqWnViaGFaQjlXck95NmMKLS0tIHFyTnNaTG9ESmRLdmNJQndCWEJm
            a1pxTm9wcWJmWjg2cXA4c09nNUQ5aUEKHKALDdAYovbrjH8drpqkiOpXMFvxeP5L
            +o1+Q6V/LFnzhHE9dUw7EUjVb3xUIzlWwbhIOoAjd67ZayDeMLblzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T10:37:45Z"
    mac: ENC[AES256_GCM,data:hW/l4XBpccWVxJXKUVtC1RYk1p4H4fRp42ooaa11txlwa9NJ791rTRrnxirwfUu/5PS/AVQVzwcmCZTfwxpUO233kYKJJHCrtVuxK3KoWo+/FSPmzvvY4vecRxxhUSf6fFCXRomvxerRvRLRu0mRUx5iDjgs/JumRHQsALeFUJQ=,iv:tZspl6ex8q57xCe4bEYy1/6OPaqVlwa9ewNLT7m+Pj4=,tag:D2lYMcI134MgoN4VKXmnrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
