apiVersion: v1
kind: Secret
metadata:
    name: paperless-rag-secrets
    namespace: ai
type: Opaque
stringData:
    paperless-token: ENC[AES256_GCM,data:9BXmkYHVAb38u+lOj3IFkT19WVB/se5NvniR9e4Ack4uRkL0B6ldtQ==,iv:5ExnwR8K71QM5IsedxFiD72AQYsUweAO2fMrosN7FsY=,tag:7QaHWo+fMFqg2M68/qW3rw==,type:str]
    open-webui-api-key: ""
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOVQ1aFVVMjJjU0xjN2dt
            elphb3Z1MWFKVkhNT0g0QTluY0lYTnhvbDJJCmtsMFBZekZWSjIyN09qb3hBZDk5
            aG80K3R2T1JqWnViaGFaQjlXck95NmMKLS0tIHFyTnNaTG9ESmRLdmNJQndCWEJm
            a1pxTm9wcWJmWjg2cXA4c09nNUQ5aUEKHKALDdAYovbrjH8drpqkiOpXMFvxeP5L
            +o1+Q6V/LFnzhHE9dUw7EUjVb3xUIzlWwbhIOoAjd67ZayDeMLblzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T10:39:48Z"
    mac: ENC[AES256_GCM,data:XSm0K3I7yfAKFWcDCi1IOUBXrDffE+OVj0bOi0x6YrNbI1tuMn99CIK7N4kHQfvbHpBLHYHxRHrCJN8ZiTS64WoW+PAu40hFfymlz9xLgMs/Nw1rCo2Byvkuim3R1zCcXyioY0gZ1RhyzL7N0odUmju15Sb7ikFQkgT9XZjTIZE=,iv:miv9dPoCkMTEt61rpbJAVYegojqietFOUZZbtlTG0/M=,tag:+/r27Xdv+cQ32lhV/qDQeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
