apiVersion: v1
kind: Secret
metadata:
    name: juicefs-auth
    namespace: juicefs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:k73AoeomQQ==,iv:X2xMW3ayaHSVPZHOc47bpktewSawNHxZprf9UWX7wSA=,tag:04XnuClDeL/RQ2brjPvk4Q==,type:str]
    password: ENC[AES256_GCM,data:WB+bFGRPLUDYsOOzkigWI5E39mcz4x9PRXURdHpxPkQ=,iv:zLOFyTbJp80ixLrNYAtnHyy5fIwmddEu4irYbXTwV3A=,tag:cjf/vCU/9Y6lOijImoJGGw==,type:str]
    name: ENC[AES256_GCM,data:W1KeR6ndbqjcJ0Xy9G0=,iv:NOMfKkvYT3W1AURMD3Fdu3SCxiOemsUPoOBNYeHQHQ8=,tag:E9ZbAH28VOZRmohk/Kg98g==,type:str]
    metaurl: ENC[AES256_GCM,data:P7jttEJi71oLh6jl89quejjUENVaZZT5EDw3Mxkq4hWqeCzwQ8jTZOBK9Ju/6GgJ9eQkMlVQKyha2bZyH7A50m4LDM4zIA+7d4N2op35fCDs6uGNV065IFUkx2SIB0pE6MeDFVyNu9VhS66dkVj3ewhG3NaXzNHoqMboGPv8,iv:Eh+fBFpMUZrX3JcyRfeFFCBFJsOzpCLDsjryGu/6wps=,tag:qqKv+eLmR/n45R9w7/9yJQ==,type:str]
    storage: ENC[AES256_GCM,data:Cjo=,iv:d4lrPf3JpaznCKRXxug+Ixzly0gvow1g7g5Ukx/yTLQ=,tag:G0OIFqau6hZN0OgfGq2AZA==,type:str]
    bucket: ENC[AES256_GCM,data:cAtQxFYs3vh5i+thS5bqUxEwJybcezxTD1y7OgLbKFf0KicU6KoS4ApeZp0/5q/qoQXToOB3QpD/9socF67qBVV87zbyJshh,iv:xxSY9DrPNEfSnJ4hoUp50vAxCru65s8gEFuZGm6o+dc=,tag:+ZPueSTmCJeNRs5JMMSNxg==,type:str]
    access-key: ENC[AES256_GCM,data:jlr3XDvsu49854DVLzMik1XiuWR5nYM9zQ==,iv:9HGlYPe06fGD5ecwj/JB3nljVjsiicUc5MXD4ysHJfc=,tag:fUO3+O2XxWC9gKGR9eG84A==,type:str]
    secret-key: ENC[AES256_GCM,data:t5fyf05m0/KzEOeSeTwoL4qjwHvNy3mJBo9rQeIsoA==,iv:o/RWgUts8LxY6MDdSGpeTcWKqlu/E9vcLiCQgUObe9w=,tag:52yIxFXiJSkBivwyS4P0ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0L0tnYmp3Q2FZaEROWkpE
            YmQrd1dXZWtSbmoyY2w1K0tKRVlLLzZucGxzCmdFT2xZOTRqWlpZalhHTHE0Z1Fy
            RlFRakZYVjJ0bEI2d2RLdjhvYXNmL0EKLS0tIE9paFVNOUEvM0VieEUxWDFkN29p
            dDlROFVrK2lwanJubFVMSkpTQ1JqNUkKCyVDh5zaaw/Is3XpROHLe/kxvR1lmavd
            UUVj0n1wleyuo16QZNw6tbLXTMSzQPZVFrRWUzzQsnq/ZRDiPj5vRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T09:07:10Z"
    mac: ENC[AES256_GCM,data:pHXTTJSSpLIuPPrKDtXBAw8FlBuJNQZ394LbbTgQCBY2//oShHgclDEFodkaXXQNG5njOW/1HoXmuitMS56we7N9/da8J2j+3Zlyv5aa1zsQxOPhG9DsW8n9mGYgsC1rV2RdHHFaTokwBJeZroeRSLgfSZSOT5qWKPOJTgbBy/s=,iv:ER6wGd80Y6e1inTn027jB54qzMJa0hWCWsRn3Lk88UU=,tag:NTHDbUdXXXYToZCPXJX2fQ==,type:str]
    version: 3.11.0
