apiVersion: v1
kind: Secret
metadata:
    name: juicefs-auth
    namespace: juicefs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:vv/pxAYr9w==,iv:KEYdA2HLa8XbhhJxczr8oZLH5W61c3ZGJJxmEZaGkiM=,tag:qySOPV5odAah0thIwvEw0A==,type:str]
    password: ENC[AES256_GCM,data:lf5KN5ty3sFWJoY8IYy5s3p7MXOoiQmPBluqqhX6gLs=,iv:eTJ4VGQ/fON4MFCiVfalLt1HZ1uOodnl3XNusP6t0X8=,tag:suUjdgVVUuF7J8JqIaH52g==,type:str]
    name: ENC[AES256_GCM,data:EBhjY/tBrxiY+pKuj/Q=,iv:albnBPwDPYzTU0rjEabzzIAyiLYw6lfsBPLbnLsYOEs=,tag:Z/LBA87SZ8QEyu0AML/rww==,type:str]
    metaurl: ENC[AES256_GCM,data:8Kp0cd3miWeaMyaNdNw2VKmXC1f2/PFG7Ey1014too4Z+iC0hh+CNkz4Eltk2Dq8DTOkTo9GbAwfL56NQS04FvLnAO0vJCSfxww9xUHDjm08SwJOv7IeKflkgM9cHPYMbUnbZ886OMOPK1LNHUAkQKrv4THgRmjv,iv:LjoVYlf2YeFZJEwVY97EVMA05mELC4zWrYvwLO7rJ1k=,tag:ImchztMO2AITpBrdfEoo2w==,type:str]
    storage: ENC[AES256_GCM,data:WPQ=,iv:yFdWFQf7r4rM0sxik926CM+7We5JhPoivA95AEflE7o=,tag:XkB59UFtx+n0L5rnIgYfTQ==,type:str]
    bucket: ENC[AES256_GCM,data:Fg7u9rRqxW4hzwsEeEnkTvSk8YU8RX8uTwt9jyDn13ELvWxGmwKfh/kneIN/+mbFApy6FW17WXpRkwWCh1XKav5xwobP0AqL,iv:S/Y7ID30WAozxezCzfLYgjRcQiqI0agWalSRa2P7DCw=,tag:nmBF8J6HIt/OO3Ev8opM7w==,type:str]
    access-key: ENC[AES256_GCM,data:Tq4I8m1+r9flOOCaGRBDe+gFlwDFIzBHdg==,iv:1KcFVHcn8Whw8LWuXfBNwRZcrj7st9O/aYe/st6TJek=,tag:IVFr5Qe1FbG2Sw1u2hGniw==,type:str]
    secret-key: ENC[AES256_GCM,data:tSs2+0CNgS41zVZS49+6onTf47ep+uJG2sUAVWEjzg==,iv:ngc2yDNlBzFR7YJt+i/wUF4CwvZ/V/5rJK7y7O9ri0g=,tag:YwUVapy1A5P44O7pb1iHaw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQmJ2dTdsSE13RjN6VWRO
            RE5JVTUxdFRIZHpDeGlhYk9LT1NJSG5ZSG5nCmpoaE5DZXpnVk5raWljLzJ5aGdD
            YWNjTWdxa1BKVFpETHl2ekJiNHFKazgKLS0tIDZ4TWRDYUJQdTcxU2R3ZklnZTEr
            ZTRaOVdPbTIwVENBaXdJZVV4RktWU00KFXSOEyO9gdPh6t083ajJL3BTHCdGWXn1
            hNRr7LWnBuuu1ZCN3KmtSyEDWNXER+LkT2kfcknoXCBuwizcFO6/5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T07:22:09Z"
    mac: ENC[AES256_GCM,data:DqiPfVOVc7d0h7fKDpDb7V8ZuDMGShR6s8W/F0Brh+aDO0H7MVUSK6kxwZULtwi8kTvYC5IY9Xp60NnWtP9cPRKFu8xdNnnpUxIZGfQUwJlgr96uh6eyfU9YNjBykst9yIFOA7z1gKKwG7PfeddChZDXTqtR2sdqEJP8QBkgeI4=,iv:UJXnPcAoKgNKPXRONb62dBB5dg+UTdgR5kOw5xgmtFc=,tag:tt3pxY12GcxU3/ibrpa3jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
