apiVersion: v1
kind: Secret
metadata:
    name: juicefs-auth
    namespace: juicefs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:k73AoeomQQ==,iv:X2xMW3ayaHSVPZHOc47bpktewSawNHxZprf9UWX7wSA=,tag:04XnuClDeL/RQ2brjPvk4Q==,type:str]
    password: ENC[AES256_GCM,data:WB+bFGRPLUDYsOOzkigWI5E39mcz4x9PRXURdHpxPkQ=,iv:zLOFyTbJp80ixLrNYAtnHyy5fIwmddEu4irYbXTwV3A=,tag:cjf/vCU/9Y6lOijImoJGGw==,type:str]
    name: ENC[AES256_GCM,data:W1KeR6ndbqjcJ0Xy9G0=,iv:NOMfKkvYT3W1AURMD3Fdu3SCxiOemsUPoOBNYeHQHQ8=,tag:E9ZbAH28VOZRmohk/Kg98g==,type:str]
    metaurl: ENC[AES256_GCM,data:fzK2a9ytT/YUeRgnQsB7EwI+lq/k/CtV6jKkZvbCwZ36f+nFz1z/h1mf4zCdG6cZ5hMFKCJ9mWdVmyPIvV1LSNt6OdRdmaQqC66AWrQlS2BwWRujTTrBhjrLk8z25FY4lkdFNjYXTAFYr1U1+XR1HMlUNwfBh+9x,iv:08QJO8vyrTT1wPcpNTFm4WIXSf0xZ/zFXb8YjMNVGCU=,tag:SzFpus/PUTfTJ1vpJx3rKw==,type:str]
    storage: ENC[AES256_GCM,data:Cjo=,iv:d4lrPf3JpaznCKRXxug+Ixzly0gvow1g7g5Ukx/yTLQ=,tag:G0OIFqau6hZN0OgfGq2AZA==,type:str]
    bucket: ENC[AES256_GCM,data:cAtQxFYs3vh5i+thS5bqUxEwJybcezxTD1y7OgLbKFf0KicU6KoS4ApeZp0/5q/qoQXToOB3QpD/9socF67qBVV87zbyJshh,iv:xxSY9DrPNEfSnJ4hoUp50vAxCru65s8gEFuZGm6o+dc=,tag:+ZPueSTmCJeNRs5JMMSNxg==,type:str]
    access-key: ENC[AES256_GCM,data:jlr3XDvsu49854DVLzMik1XiuWR5nYM9zQ==,iv:9HGlYPe06fGD5ecwj/JB3nljVjsiicUc5MXD4ysHJfc=,tag:fUO3+O2XxWC9gKGR9eG84A==,type:str]
    secret-key: ENC[AES256_GCM,data:t5fyf05m0/KzEOeSeTwoL4qjwHvNy3mJBo9rQeIsoA==,iv:o/RWgUts8LxY6MDdSGpeTcWKqlu/E9vcLiCQgUObe9w=,tag:52yIxFXiJSkBivwyS4P0ZQ==,type:str]
sops:
    age:
        - recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENjlXeVFkbDlkeUJZR1Nr
            L0hObkhab1VSVjZUZXFWQS9Mc3pMNDNJVno0CmZvcnZacEN3cldqZ2M0aU9yd3Ju
            aXl6OEUyN0ZDc0hVeHJ5TWI0a2JNVDQKLS0tIHZ0cTZBaFhpWHdHS1V6dTdicFJu
            dkljYStuZFFCS1dHVEhmb1YwcFF5RHcKHo4cE2RYbMQvS6hzZOieAoIZqGeawSXS
            xHbEX0oW/nc5SuisGaiK8qkB57AuLhgcb3fj/DpXlIjuWNJfc6nA8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T05:53:51Z"
    mac: ENC[AES256_GCM,data:uGxOElMPl1766Mdo5H7wszUFRbL7EtKje5aMDUtAdIRWMmqH65tw5YEkQfAQ2uiB744wAosxsnt4HSF1hkXiIkPqAL66K6MBW58hIISAFf1w+4PFhq7NKVHyiGvYsSdXKBsEAu24tpUtw7S1tC/E+cvgq8t5eZXCoCmkbJtsrAw=,iv:ntBqqI7tdoZmSD+cxmy5lztz+NfKs9BU5KKXMLPapPo=,tag:frrF+gvcuEmfS2wC+zGoEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
