services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /var/lib/homeassistant:/config # Mount Nix-managed host directory for HA data
      - /etc/homeassistant/configuration.yaml:/config/configuration.yaml:rw # Mount specific Nix config file
      - /etc/homeassistant/scripts.yaml:/config/scripts.yaml:rw # Mount specific Nix scripts file
      - /etc/homeassistant/automations.yaml:/config/automations.yaml:rw # Mount specific Nix automations file
    environment:
      - TZ=Europe/Berlin
    network_mode: "host"
