services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /var/lib/homeassistant:/config # Mount Nix-managed host directory for HA data
    environment:
      - TZ=Europe/Berlin
    network_mode: "host"
