apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../glance
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: glance-data
      namespace: glance
    patch: |-
      - op: remove
        path: /spec/storageClassName
      - op: remove
        path: /metadata/labels/recurring-job.longhorn.io~1source
      - op: remove
        path: /metadata/labels/recurring-job-group.longhorn.io~1glance
