apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        supplementalGroups:
          - 26
          - 303
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: web
              containerPort: 8096
          readinessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: transmission-data
              mountPath: /media/transmission
              readOnly: true
            - name: dri
              mountPath: /dev/dri
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-local
        - name: transmission-data
          persistentVolumeClaim:
            claimName: transmission-data-local
            readOnly: true
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
