apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: executor
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
  - secrets/executor-secrets.sops.yaml
