apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: infra
  values:
    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: monitoring-alertmanager
    grafana:
      admin:
        existingSecret: monitoring-grafana
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
      ingress:
        enabled: false
      persistence:
        enabled: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        retention: 3d
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: {}
        podMonitorNamespaceSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        serviceMonitorNamespaceSelectorNilUsesHelmValues: false
        ruleSelector: {}
        ruleSelectorNilUsesHelmValues: false
        ruleNamespaceSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 15Gi
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
