apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual-local
  volumeName: perun-loki-data-local
