apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-endpoints
  namespace: infra
spec:
  groups:
    - name: monitoring.endpoints
      rules:
        - alert: ExternalEndpointDown
          expr: probe_success == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Endpoint {{ $labels.instance }} is down"
            description: "Blackbox probe {{ $labels.job }} failed for {{ $labels.instance }} for more than 5 minutes."
