apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-grafana-local
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual-local
  volumeName: perun-monitoring-grafana-local
