apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docmost
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/docmost
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cnpg
    - name: cert-manager
    - name: longhorn
    - name: traefik
  timeout: 10m
  wait: true
