apiVersion: v1
kind: ConfigMap
metadata:
  name: nanobot-config
  namespace: ai
data:
  model: google-gemma-4-31b-it
  obsidian-vault-repo: https://github.com/def4alt/vault
  obsidian-vault-branch: main
  obsidian-embedding-model: qwen/qwen3-embedding-8b
  obsidian-sync-period-seconds: "300"
  obsidian-default-top-k: "3"
