apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-data
  namespace: ai
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/nanobot: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
