apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shell-home
  namespace: shell
  labels:
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
