apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: shell
spec:
  type: NodePort
  selector:
    app: shell
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31022
