apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-config
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual-local
  volumeName: pinchflat-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-media
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual-local
  volumeName: youtube-media
