apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-local
  volumeName: radarr-config
  resources:
    requests:
      storage: 5Gi
