apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-local
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-local
  volumeName: perun-radarr-config-local
  resources:
    requests:
      storage: 5Gi
