apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docmost-db
  namespace: docmost
spec:
  instances: 1
  bootstrap:
    initdb:
      database: docmost
      owner: docmost
  storage:
    storageClass: longhorn
    size: 20Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-barman-s3
