apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-redis-data
  namespace: docmost
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
