apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost-redis
  namespace: docmost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost-redis
  template:
    metadata:
      labels:
        app: docmost-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: docmost-redis-data
