apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: docmost-db-daily
  namespace: docmost
spec:
  schedule: "0 30 3 * * *"
  backupOwnerReference: self
  cluster:
    name: docmost-db
