apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints-proxy
  namespace: authentik
data:
  traefik-forward-auth.yaml: |
    version: 1
    metadata:
      name: Traefik forward-auth baseline
      labels:
        managed-by: gitops
    entries:
      - model: authentik_providers_proxy.proxyprovider
        id: provider-traefik-forward-auth
        identifiers:
          name: Traefik Forward Auth
        attrs:
          name: Traefik Forward Auth
          mode: forward_domain
          external_host: https://auth.def4alt.com
          skip_path_regex: ""
          intercept_header_auth: false
          basic_auth_enabled: false
          cookie_domain: ".def4alt.com"
          authentication_flow: !Find [authentik_flows.Flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.Flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.Flow, [slug, default-provider-invalidation-flow]]

      - model: authentik_core.application
        id: app-traefik-forward-auth
        identifiers:
          slug: traefik-forward-auth
        attrs:
          name: Traefik forward auth
          slug: traefik-forward-auth
          provider: !KeyOf provider-traefik-forward-auth
          open_in_new_tab: false

      - model: authentik_policies.policybinding
        id: binding-app-only-me
        identifiers:
          target: !KeyOf app-traefik-forward-auth
          order: 0
        attrs:
          target: !KeyOf app-traefik-forward-auth
          policy: !Find [authentik_policies_expression.expressionpolicy, [name, Traefik only-me]]
          order: 0
          negate: false
          failure_result: false

      - model: authentik_outposts.outpost
        id: outpost-traefik-forward-auth
        identifiers:
          name: Traefik Forward Auth Outpost
        attrs:
          name: Traefik Forward Auth Outpost
          type: proxy
          providers:
            - !KeyOf provider-traefik-forward-auth
          config:
            authentik_host: https://auth.def4alt.com
            authentik_host_insecure: false
            authentik_host_browser: https://auth.def4alt.com
            kubernetes_replicas: 1
            kubernetes_namespace: authentik
            kubernetes_service_type: ClusterIP
