apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints-passkeys
  namespace: authentik
data:
  passkeys.yaml: |
    version: 1
    metadata:
      name: Passkey login for the default authentication flow
    entries:
      - model: authentik_stages_authenticator_validate.authenticatorvalidatestage
        id: default-authentication-passkey-validation
        identifiers:
          name: default-authentication-passkey-validation
        attrs:
          name: default-authentication-passkey-validation
          not_configured_action: skip
          device_classes:
            - webauthn
          webauthn_user_verification: preferred

      - model: authentik_stages_identification.identificationstage
        id: default-authentication-identification
        identifiers:
          name: default-authentication-identification
        attrs:
          webauthn_stage: !KeyOf default-authentication-passkey-validation
