apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints-flows
  namespace: authentik
data:
  policies.yaml: |
    version: 1
    metadata:
      name: Custom access policies
      labels:
        managed-by: gitops
    entries:
      - model: authentik_policies_expression.expressionpolicy
        id: policy-restrict-akadmin
        identifiers:
          name: Restrict to akadmin
        attrs:
          name: Restrict to akadmin
          execution_logging: true
          expression: |
            allowed_usernames = ["akadmin"]
            return (
              request.user is not None
              and request.user.is_authenticated
              and request.user.username in allowed_usernames
            )

      - model: authentik_policies_expression.expressionpolicy
        id: policy-any-authenticated
        identifiers:
          name: Any authenticated user
        attrs:
          name: Any authenticated user
          execution_logging: false
          expression: |
            return request.user is not None and request.user.is_authenticated
