apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/watch: "true"
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  values:
    blueprints:
      configMaps:
        - authentik-blueprints
    authentik:
      enabled: false
    postgresql:
      enabled: false
    server:
      replicas: 1
      persistence:
        size: 20Gi
      resources:
        requests:
          cpu: 100m
          memory: 384Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - auth.def4alt.com
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.def4alt.com
      livenessProbe:
        timeoutSeconds: 10
      readinessProbe:
        timeoutSeconds: 10
      startupProbe:
        timeoutSeconds: 10
    worker:
      replicas: 1
      livenessProbe:
        timeoutSeconds: 10
      readinessProbe:
        timeoutSeconds: 10
      startupProbe:
        timeoutSeconds: 10
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 750m
          memory: 768Mi
