apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - postgres-cluster.yaml
  - outpost-proxy.yaml
  - outpost-ingress.yaml
  - blueprints-configmap.yaml
  - certificates.yaml
  - secrets/authentik-config.sops.yaml
  - secrets/postgres-auth.sops.yaml
