apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-proxy-outpost
  namespace: authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-proxy-outpost
  template:
    metadata:
      labels:
        app: authentik-proxy-outpost
    spec:
      containers:
        - name: proxy
          image: ghcr.io/goauthentik/proxy:2025.10.3
          env:
            - name: AUTHENTIK_HOST
              value: https://auth.def4alt.com
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: authentik
                  key: AUTHENTIK_OUTPOST_TOKEN
            - name: AUTHENTIK_INSECURE
              value: "false"
          ports:
            - name: http
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy-outpost
  namespace: authentik
spec:
  selector:
    app: authentik-proxy-outpost
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
