apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-auth
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
