apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-barman-s3
  namespace: paperless
spec:
  retentionPolicy: 180d
  configuration:
    destinationPath: s3://def4alt-homelab-backups/cnpg/paperless/paperless-db-plugin
    endpointURL: https://s3.eu-west-1.amazonaws.com
    s3Credentials:
      accessKeyId:
        name: cnpg-barman-aws
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-barman-aws
        key: ACCESS_SECRET_KEY
      region:
        name: cnpg-barman-aws
        key: REGION
    data:
      compression: gzip
    wal:
      compression: gzip
