apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: paperless
spec:
  instances: 1
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-auth
  storage:
    size: 5Gi
