apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
  namespace: paperless
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/paperless: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
