apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
  namespace: paperless
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
