apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: paperless-db-weekly
  namespace: paperless
spec:
  schedule: "0 15 0 * * 5"
  backupOwnerReference: self
  cluster:
    name: paperless-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
