apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlays
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: minecraft
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/modes/apps/minecraft
