apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../paperless
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: paperless
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: paperless-gotenberg
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: paperless-redis
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: paperless-tika
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
