apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:3aUn0krr9cJPEAkw7VzOEkp6ByIcLuVP,iv:1X6G1LUjsTHO66LrYyMwuHrbd1gt+2oWrbRZAvl1O1I=,tag:3qBUyw2DzOM6qVgUdkb7uw==,type:str]
    admin-password: ENC[AES256_GCM,data:AdYG/fOczLOWignZBAycfFVwnyexZ1AU,iv:JgFA1DKmrCivOqlEPkoR93nKZix7E9fpiFxoR+CM7rU=,tag:K0QHvKvYJRo1cmkp5vvRtA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YklUcEVlcXQ5K0VqQUlU
            Mng3cXNtbW5Jbkx2QnJKWGVmYkI4bUtXRHcwCnJYUWNVTEpPQ0t4MzJQSHhacmUv
            VVR0d2dHYzZHdUVOMllZaHpNYi9GZ1UKLS0tIEtDR3BpVUlNMk90M0pBR3hGZkRw
            YlYzSlVZUEIza2tJM0VWaDVTZnc3cmMKcTvw8JOToghSM5S2vK3C6aQ1ybgSfrc1
            ly8PHZJKjIHtWewfg4nKPkoUScunGH4DRrkGlNP2s31NLX8metCUjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:44:37Z"
    mac: ENC[AES256_GCM,data:Pp4EewG9LcfIwZ7opSLBKHH3FuqP4ehYH4ot2JJNPDr/pqPNxRNcJCVyIaDrAy4b+N05CHLUUcboDBYOo8i0M+4oFRiGvxmZR6W4JwsNIQ1LIcRpt/LM/yT5DoOaO5BDYyEAVvuW7lBuZdlnwyN4/Nncko6YSiFgKna5tCR4C0I=,iv:IpLevXV3WStnT0V2mSKfI0c8se3Ew1dvfW2u2ewD+s0=,tag:yOQln81K0BW7DVp3p42p9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
