apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-auth
    namespace: paperless
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xKUeMem6Tgde,iv:MfybaY7E9d4/nccxP+P82Ky8USiZ1Tg4DSeLMDqRk6A=,tag:4RAImxW1b/XFmJOu/7xATw==,type:str]
    password: ENC[AES256_GCM,data:ERNbRlGhIVpSbVRuGIFj2tC7xcGw5TSD,iv:Vb4QM3h0t9VdxfRkF/L7gSNJ65kP/uslr1JwWlgIMc4=,tag:FcggRHLbxP6sE5/MNKOHDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaTdNR3FwNTMxbUxrQTAz
            ajVneUZCUjk0NzFvUmE0ZjZkWXZUQ1hzcmhBCk1mTXBpeVVyWHN1eDQ1MmxEZFFP
            VUpwZUZCMjVMK09aVmtlMWNYME5iZWcKLS0tIHVaNjkzcktOSXZpOUJkL0QzemNQ
            S1VDZjVYSGpGZFE5YUJWRy95M1pMNDAKIBktMqfURHW9w89Pfj/9tjjiOVYVBcBn
            vpKWgZbwdEyHGSi2js7yqqZs/xq76ipdry20Djycpdzx944t+gi5bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T20:44:37Z"
    mac: ENC[AES256_GCM,data:M4rGwrK/+s6izhDQBnld7FnopxjuyUswnW9hUmwVtbb3LxaY5xrrsRFaxmlnFxri32p2BLztv8xnhO6kKzRNYdI3aA9iZQQeQDkoBFVlpBYRLbI0ctQyvVWuIWF1veJSQ06fbtrDaC5WFli2SMeT+qNEa4TY+BII494WvN7eWtQ=,iv:c1+CCaBe50DPXRCxrC6KMF+R5AKx9rdH8q4fTdCwXmQ=,tag:fDMVv+UzXJUPfR2+XDMHaw==,type:str]
    version: 3.11.0
