apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-auth
    namespace: paperless
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xKUeMem6Tgde,iv:MfybaY7E9d4/nccxP+P82Ky8USiZ1Tg4DSeLMDqRk6A=,tag:4RAImxW1b/XFmJOu/7xATw==,type:str]
    password: ENC[AES256_GCM,data:ERNbRlGhIVpSbVRuGIFj2tC7xcGw5TSD,iv:Vb4QM3h0t9VdxfRkF/L7gSNJ65kP/uslr1JwWlgIMc4=,tag:FcggRHLbxP6sE5/MNKOHDA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb2FKZUZiamo4VG96Uzh6
            WWpvQktYRlBiZjNRaGk4M01QQ2ZtWjlNYTFZCmpHRzlTRHBpR1B4SUNDb0xsaGlm
            ald2ZHJBYWxubTZlR29VT3VqNzRuTWMKLS0tIENEb2YvbzQxNFAwcFE4WDEwWGZM
            ckVHcGE4WlE1MWNYbUVHdWdCNjl0VmMKZf/jUZ+PCnULfJxgnDYS3nMu4VUhnYit
            DtonCVB1Ji/rII+5kbeRdnnLsXu38NY1zaGY2ME6URhSSFiQ8UE4iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:44:37Z"
    mac: ENC[AES256_GCM,data:M4rGwrK/+s6izhDQBnld7FnopxjuyUswnW9hUmwVtbb3LxaY5xrrsRFaxmlnFxri32p2BLztv8xnhO6kKzRNYdI3aA9iZQQeQDkoBFVlpBYRLbI0ctQyvVWuIWF1veJSQ06fbtrDaC5WFli2SMeT+qNEa4TY+BII494WvN7eWtQ=,iv:c1+CCaBe50DPXRCxrC6KMF+R5AKx9rdH8q4fTdCwXmQ=,tag:fDMVv+UzXJUPfR2+XDMHaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
