apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis-auth
    namespace: paperless
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sb97gD5ElhuGSnbg+1S1U5iKpmJxhMIB,iv:HOZ7ru105sn3Jf1j1U2HZDy2CVDxbS/rVvpioetIS38=,tag:z1sx1mxsOfsOfhxytA+NgA==,type:str]
    redis-url: ENC[AES256_GCM,data:ezXOUczAUOu5r/our5xJ12BQxK01kzpMw/9Ia365ZS8Qvfdj0Es+1Padw76Ng8feGxYjNvGm3o0GbryBvn8ilmRAkJjzlz8pY1rCimL6yJm5lg==,iv:Bleef069+evf15a0HK9WpRIveihpgA+/gXO8Ccof0tY=,tag:qNRlGJKzJ7q4MnX9LVjgJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSnEyeHFqdzNBdDBwMDNU
            a0RsbExTWWM1YitWQng2R1hJZDNIRzFuK3g0ClBSOTVmVXUzb1lXS3BqcGNoc0Vn
            VXdkbTNuV29IMmVLY1VKZXA0b01QNEkKLS0tIFdJNFQzRnB4N1dSaHJ5ODdWRXZ4
            d0V0S3hUTVE2QkxydlZiS0pzOHZSdkkKARX/qEFO5GQS2yR5CBWNDs9ZNdaZ2dgc
            +ZDPCSVf82Gophzxsv3jEcifbTtPgSPPUbULgLS5LyNwWeRWXjrwmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T20:44:37Z"
    mac: ENC[AES256_GCM,data:pBVNx2DVRJJVnrgj/fGS3IJw73qYryLGAB9xcyxVi2oRjeZgL0zpyGEfGbG1CNWRM5ddpipKiKjP92zR6qpGTDBDOk/yy1I1YWGDHghryAapOv4tHqFxCoN06zKS6TfU3V57zmiLxJmRKCRxfxlEFBqbiHdHaYUKVYuG1ArDRmM=,iv:kW1lbJctagJDKLwvwdVaklTRt+S8Dv4ylIRDSfKFQM8=,tag:w4surfFGDkxjd4Nltly/cQ==,type:str]
    version: 3.11.0
