apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale
  namespace: infra
spec:
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.78.1
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_KUBE_SECRET
              value: tailscale
            - name: TS_USERSPACE
              value: "false"
            - name: TS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_ACCEPT_DNS
              value: "false"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: var-lib-tailscale
              mountPath: /var/lib/tailscale
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: var-lib-tailscale
          hostPath:
            path: /var/lib/tailscale
            type: DirectoryOrCreate
