apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: nextcloud
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: nextcloud:29
              command:
                - /cron.sh
              env:
                - name: POSTGRES_HOST
                  value: "nextcloud-db-rw.nextcloud.svc.cluster.local"
                - name: POSTGRES_DB
                  value: "nextcloud"
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-db-auth
                      key: username
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-db-auth
                      key: password
                - name: REDIS_HOST
                  value: "nextcloud-redis"
                - name: REDIS_HOST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-redis-auth
                      key: password
              volumeMounts:
                - name: nextcloud-data
                  mountPath: /var/www/html/data
                - name: nextcloud-config
                  mountPath: /var/www/html/config
                - name: nextcloud-apps
                  mountPath: /var/www/html/custom_apps
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: nextcloud-data
            - name: nextcloud-config
              persistentVolumeClaim:
                claimName: nextcloud-config
            - name: nextcloud-apps
              persistentVolumeClaim:
                claimName: nextcloud-apps
