apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - postgres-cluster.yaml
  - cronjob.yaml
  - scheduled-backup.yaml
  - secrets/postgres-auth.sops.yaml
  - secrets/redis-auth.sops.yaml
  - secrets/nextcloud-secrets.sops.yaml
  - secrets/cnpg-barman-s3.sops.yaml
