apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual-local
  volumeName: navidrome-music
