apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: infra
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:6w1/+gb5lWgJbhUIsiTbPgrBdvyH7yWtFZdoIgiia7pbFv+9qJpahYqXYOA8FcXunmu8C0eqHheWesa2DfI=,iv:3bdNCBOtpb2fPItIq4YKx7L/9RuyRr2O1m9avu+BDJg=,tag:Q2LfXPA2rhtS22LiPagMTQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZHZGcHJlYzg4dDkrekJH
            NkR6alFuOHRQVjNUMDlOU3pRSS8wUFlWQkJ3CnBzU2RqZmVXWUFmc0RVRkZjZFFR
            NzlucDJTeVdhM01SSnZXNkRWTjRxSDQKLS0tIFhnb2NYOGVpWU14K3RnTzQ2ZXI1
            QmlWRU5mVFlBcnh4dHJKNlBKVHljUkUKDn8ogWZgxRYASuuxmjbyxCXSOsKXhMD7
            4rH/KLdHQF4VSVwYj3rxHtAPoYt1gxHmOTQtB2Z91SnOmNSgXas5Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T00:44:31Z"
    mac: ENC[AES256_GCM,data:y8WQ9I7PbTZ6LCKmj2KpFt44Hfy1waJ412G/Viv7+iOZeflYrEsQwCAkVAw2aJo+V2c8Y+YuH4WsBSi0j/g9UcLZ2KIgXpR6ARqr7//47P1QNFYItTF2Tmjhy1Tzl9anFIkMqPnOpBfPcvVL3orJxeaI7BtSsWF+UVPjf6bUcdk=,iv:uVKAR8YIeumbCgPJrn8RsFGjSOj/IAiyyuB7Eng0OSs=,tag:NEJLkB4GaGwExHD+YYTs1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
