apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: infra
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:iiR16QeyMYmL4m/K0wLkmGEbFVUiD9PB0SqyfEtLKrQeA3ABAE3oFw9DR4J4Uzg2e9IycFHW3EoQQ/u1H5I=,iv:mOMQwiRD9ghPedgA0nn9nBdUTqdl246tr5AcuB8qU+s=,tag:lKHuxW45y0TT/2S5FJsI+g==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZHZGcHJlYzg4dDkrekJH
            NkR6alFuOHRQVjNUMDlOU3pRSS8wUFlWQkJ3CnBzU2RqZmVXWUFmc0RVRkZjZFFR
            NzlucDJTeVdhM01SSnZXNkRWTjRxSDQKLS0tIFhnb2NYOGVpWU14K3RnTzQ2ZXI1
            QmlWRU5mVFlBcnh4dHJKNlBKVHljUkUKDn8ogWZgxRYASuuxmjbyxCXSOsKXhMD7
            4rH/KLdHQF4VSVwYj3rxHtAPoYt1gxHmOTQtB2Z91SnOmNSgXas5Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T16:45:39Z"
    mac: ENC[AES256_GCM,data:TC8BfO+42YFiNKvlCaNYgdIM+vGmQawTAzXFWq5PZvpGViiu33hJLzXygxU6kV7pIlScgmbvOW2idaCqtr8wl6FExiZqzK5Ev4iJTdCZSBxdIy2+pXN9WxslRChA/6Et+PnzBJ9DGP3Sph1NlazwnqxyoFJ+bOfZ60L8/UOFKNI=,iv:0FUmvOdt5E3g5M+E6L0hPTjQkPaWHp7IwOEdcH8KX18=,tag:VsGy/IDTpDcNUztS9R+C4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
