apiVersion: v1
kind: Secret
metadata:
    name: documents-restic-secret
    namespace: syncthing
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WqRgOgUT3FXCsM6TWz62o8yHHCiYZ7RwqlqU0DIytJCa8934v/N7pJWqBYpH6yylPLbQUid5vkSU2rsQoFdvwQ==,iv:+qfWqW+zrDBxXmMhtL9Yj0/Hx2Zmap2eVRfF5Opnk1M=,tag:NZRGt9ELsztKQhWuLPj7yw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZXVF7kFb+gRGia/s1pTEv7U6ZZaLZiVTqA==,iv:7/OvdVDDur5PDsFZiddLnThqwddKqa7isgsVhwSIyXY=,tag:QCg5Xj68RxEUMGUXibU2wg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A3k7g3LSpciqb6ijX3QI4eVxMwZtvo1Ewouvnhl2lA==,iv:y6IDX/gWMWIvrGrRDYx641OYUNgBMOFS43hjKKaK/YE=,tag:XcwyMQj2bhlopoP6ARh3WQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRzV1Y09RTHZMY3drTlMr
            U0F2Vnk4djZlU2lUOXVVS2tMQWY2ZElQVHpJCnF3ek9aTFBic2IvajQvOXRnams1
            c2U3NzA3dmM1QjQ3UndwSWpVWFZCaGsKLS0tIGJMaWxuY0VHTXFvalFqdUtzYnpa
            dGg3S1Z1TER6VmMrTDErRWhWdldCOTQKsJUrtD4EUsf24Rvb+Xb01dnDwqHjYm5E
            RX7aXguTyZNXx28sVkMbcYjTxYAxjzWL28i5rTMn0bj1+1YlcDY1NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T06:22:30Z"
    mac: ENC[AES256_GCM,data:3FNNeZ1I2zEupWx+qgpsptynYHSSSe4En3Qan5avsrhHST6sBn4WhPNDrFBZBCXWstFw6+SO9vNGg4tLASfEPpbKZ7U7ZAvWCaFOaLN4oS5b5d8csXtUOx5pSvcXVlS+Ju+JUevaEfp+wwFgT7UW8fha5qaosPLHKv3YxWu1SIc=,iv:nUOF29e7s562XUJG92Qy+lUGeZRwPPweANmPAfZL/Lw=,tag:Arn2yY5Q5z3yN4usZeThkQ==,type:str]
    version: 3.13.3
