apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juicefs
resources:
  - juicefs-csi-driver.yaml
  - postgres-cluster-local.yaml
  - barman-objectstore.yaml
  - scheduled-backup.yaml
  - storageclass.yaml
  - secrets/juicefs-auth.sops.yaml
  - ../secrets/cnpg-barman-s3.sops.yaml
