apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: juicefs-db
  namespace: juicefs
spec:
  instances: 1
  bootstrap:
    recovery:
      source: pre-rename
  storage:
    size: 10Gi
    storageClass: manual-local
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-barman-s3
        serverName: juicefs-db-20260718
  externalClusters:
    - name: pre-rename
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cnpg-barman-s3
          serverName: juicefs-db-local
