apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - server-deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - postgres-cluster.yaml
  - database.yaml
  - secrets/postgres-auth.sops.yaml
  - secrets/redis-auth.sops.yaml
