apiVersion: batch/v1
kind: Job
metadata:
  name: immich-library-migrate-to-juicefs-writeback
  namespace: immich
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: immich-library-migrate-to-juicefs
    spec:
      restartPolicy: Never
      containers:
        - name: copy
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -eux
              cp -a /from/. /to/
          volumeMounts:
            - name: source
              mountPath: /from
              readOnly: true
            - name: target
              mountPath: /to
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: immich-library
        - name: target
          persistentVolumeClaim:
            claimName: immich-library-juicefs
