apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db-local
  namespace: immich
spec:
  instances: 1
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-auth
  storage:
    size: 20Gi
    storageClass: manual-local
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-barman-s3
