apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-juicefs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: immich-juicefs
