apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-weekly
  namespace: immich
spec:
  schedule: "0 15 22 * * 4"
  backupOwnerReference: self
  cluster:
    name: immich-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
