apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - secrets/postgres-auth.sops.yaml
  - secrets/kan-secrets.sops.yaml
  - secrets/cnpg-barman-s3.sops.yaml
