apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kan-db
  namespace: kan
spec:
  instances: 1
  bootstrap:
    initdb:
      database: kan_db
      owner: kan
      secret:
        name: kan-db-auth
  storage:
    size: 5Gi
  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      destinationPath: s3://def4alt-homelab/cnpg/kan/kan-db
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-barman-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-barman-s3
          key: ACCESS_SECRET_KEY
        region:
          name: cnpg-barman-s3
          key: REGION
      data:
        compression: gzip
      wal:
        compression: gzip
