apiVersion: v1
kind: Secret
metadata:
    name: piped-db-auth
    namespace: piped
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:puBtXy4=,iv:5Fxo8+YpscDTJlsH9vyLBjiWF389kO8pojXdtYeEQio=,tag:E0/XyvyFyj7ROGorBluACA==,type:str]
    password: ENC[AES256_GCM,data:pV/ohwfAMLScZZPUKFAVeLpogaewhG+79U9eok8RolA=,iv:54ectSrme1ow7kmznOYqpuuQgPSF7GQT+7YeBjVsauM=,tag:FfiMBT0M0jCJ6rwYXdgU7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTlhvY29uUmtDaWxnYkdC
            bExRR3UrKzJ2OE8xd0ZYWGN1TXJPcm1NTmdFCm1hOXBLaWQwZ0RqVHg2NnpCNmli
            SHhBMXQ5TzBsUVV0K1gydVQ3UWRIdDQKLS0tIDhXbStXcFhrUFphanlnVGdiSVJj
            dUlQc1VqOTQzSVhrTFJzYUYyeUxLeVUKJWtzp6ruV2+1G+PuM8fSJ5MHrukGDQO3
            Slpl/WqIcJxZi2WasoBWV/U03rvs3MJ5veBu8KBuTE+UnEqW6tNltA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T05:42:42Z"
    mac: ENC[AES256_GCM,data:WRy6Bu110kkkzh4kErsavIh4cHbqk3SO0Sf0tdVnLHibKdaULL+0DkljjKIOZIixKT8KSZTcRwbtxd+NGEC73QaItL2tDTFDbK8R1I73FawCLdFsk9r8ru10rutLmUfvt+32wfVRp3SuEeQMRGUFzOWaaR+4+GJkUSntwNO018w=,iv:UPJHGkTb1Skc7s5aJZ8rpHGTrPy3RCratcJW0jXih8U=,tag:szxRqFYGPOr4tBpDYUdZ/A==,type:str]
    version: 3.13.2
