apiVersion: v1
kind: Secret
metadata:
    name: piped-wireguard
    namespace: piped
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:D4S3prascLDxleDOShEkpzuNmr6Ob8Q5u73IA+X3LoPnI51DwAnAVDw5X4M=,iv:abWUoOZxzvn+b/A2NUbYd1l1J696BDzxIYOGY9pvWHM=,tag:4jiBJbH9NTNngmDB0FZp1w==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:uR93tsU5sE2SN4nNKMs2DA==,iv:r4kvimcGKLO+7CKY4M4gksBbnJm/u9yrwPZPWkE29I8=,tag:qPlbRAabsdYByY15+W3OEA==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:X28t9ahxUFxvwBHC7NS64gp1DuAaLFTTJ1/xqnr3slPR/46rvpoAbrkGRRo=,iv:j11gC++x7nGZrO7WMGw5bP9bhWqhjl0l9kuakeXV3Jg=,tag:JQtDqgQvAR4xTcmnmp5TKA==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:5e6GQO9USOxDihQNJQ==,iv:7Pem/Ijz+iHzwtRGvTclegAOQt1EEDSW1BvZD0HalL0=,tag:IXQjwilzTg1NfH9nZIR94A==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:bzz7QzA=,iv:+JvEq3Yb4ehYS76WOIYk98VQQmdtz4w+xkiMEz05jcI=,tag:saeJmrHKBuMDup1mcXgvNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTWZHeGJvOFFlQS9LZUR3
            OXJ6YmZOOGZ1b0Q5SzFwSmdlYWtDUTZJemg0CjlJQ2tSRDhVVEV5bFNUam9rMFlz
            MUs5NGExMExwUWxtazg3TFJKVkdYU28KLS0tIEhiRDlGZkRrVGJGeGwvOHdsYVNt
            UXVETGNBUWpCZ0FJNXFuRVY2ZHV6Q1kKCK3lAudJoP0jIi3eDCVHDmMEYLsOJvH/
            PFhabc/gM9CLxIgk/fBsX+iRbi7MIXhALZLKNWE3bxiQpHlCGfOLQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T05:42:44Z"
    mac: ENC[AES256_GCM,data:ovZVcVLg3LfbsEhDmxE465wfWv243EY/AbHR39S/e588Aw3FCA3gQ3x7PLLI2DDHkTaAJ5g5rVaN/cd7twexLZjr3PazLga9eoVKbarHqWrHXqLWftfme2kfZQ//Zttat/rNsqHb16g9IopRIUorOfuxmduyRtOTXKmuJRFKBsA=,iv:bxNijXdfKM6dmdIGJXMQ9DqrQeqLoxv/1wfY8SPMhD8=,tag:VBBEn1xZ3sYcTH6qZCHz0A==,type:str]
    version: 3.13.2
