apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: kan
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:xcyNXkrHABVsqSZ8j3s+xjS+uRTgQ3aW2g==,iv:EvMixVDVthOmSo7NNKWyI3jpVAvkmhglGgOn+mA5fWc=,tag:gCoTNzCCvnNbUeLFVQ5HDA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4ElFoH9aFMSEOCNSDqpQBeQfrA99h0wcBBgcxNcOoQ==,iv:lIb50Yc1A5lJtP393Xa/0eqTfXv4mqbA99OzolyxwjQ=,tag:7i9J/omM4yGNhe3OAbpvCg==,type:str]
    REGION: ENC[AES256_GCM,data:ATTs/nhGOH1P84i4sd0=,iv:Sd3Nsz3Mo7kRscOM6whFbWme3BwDCye9qFvX3ghL2cs=,tag:HkmBtFpffbEAttVmCycKwA==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:nMvsuN8YTz6pnQi291HEfp6IKPSDYYLPVxEDGW+u713V1PgFVxvm6hE=,iv:vtx3FIpNTFnROK1zCuot32bAqy4FNDBNQ8tp9tUVzm8=,tag:fUc9a96N0YY80/ZFb0Qw2w==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQmpXTGJDZjQ5eUZhQXlV
            N2VRcjBTdWRrTDcxY0dEd0hVZ2xTRU5xcGpBCkg4YitSbGFlYUJyNk1DcVFlbWU4
            dWtveTZZVUozTjQ5YitYQU1pTzlGZncKLS0tIDFSdHFIcWlxK0svMytsaVRUcndk
            NVdCOE1IZVUzaWtGaGUyT3NGTGppWW8KPnozDOPDpIWrTb/w7ZIjOmcDz161MuU9
            uceFTa1zrS7BKx3/bVCmh/vu3viVkrG1LZ85V9wJecPg5mpyKx2eSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:33:36Z"
    mac: ENC[AES256_GCM,data:ldP3Ey0+MDoXA0+44JqSi9vJ6ddwHDDu6VsNYbF9biLDFWnsH6wqUvC1+oH2ncNkcZhYCCplKxr7qacw+ROBi3mB6Qr3T9kPTMwoVl3L+h9lRdiXS+XnaY6ucTKNPNRQJaH0gW89fwPT5DipxW/rNfZR4xhw4PIV5/pO+y2VlUU=,iv:+vQB4ek52CjENHNCJK5MUxTj86UYIEleuc2dHgPgdLM=,tag:CPQVCPnRbDhpq6q7wk9Yqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
