apiVersion: v1
kind: Secret
metadata:
    name: kan-secrets
    namespace: kan
type: Opaque
stringData:
    better-auth-secret: ENC[AES256_GCM,data:AnjgDDPshKmPvDBZzmYnuVW9d4Hot6wC,iv:QVqQ9iAqsNZ7UBYO60Cl8vn9ISODXSpUm+uO4YKneDY=,tag:3Xsdt6bMTqDaV1Wx882asg==,type:str]
    postgres-url: ENC[AES256_GCM,data:Z4mO23G5HhwgkTsu+8hdW3PWuLSFm/OW4hl++FNXpC4wUNfNZ9bpKkwm1gU7g58tLFcMqVFan5msyM7YK3KviWen2sokoOGDJx5oohh6kFn7BczpiQ==,iv:j0mTVvXymRORlm1l9cm8I5+R56+NJIMLNrUcBjea1L4=,tag:7PiwbXmHkPITuqYcAz1RNw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnJsL0FOUDJmUnZSTkF4
            TUxRM0YzYnZ0b2U2bmgrRlhYQTVxMHhNYjNrCkkrbXVoeU94bDViSXJYR1liUXp3
            cjFsWG9WWjI3TElPNjU1OVVvMmJuQU0KLS0tIDlSQ2ZTZnpFenVEdlNsWEhlRlpO
            VkpWWW9PdHo4R2tIbnkvQVVTUi9sOEEKOixdPj+GmS0ZCshFraxfvpMvZY8HyFQH
            A4S+DahQCqqyH4eDXwUzxR42M6icZvKSlfXglw0BILNSPpdRm54WEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:45:46Z"
    mac: ENC[AES256_GCM,data:rgdqSQjiqBkHeJRum7NJxxBdYh7fI2SQY1ae8KMA/QaQQQIrGOHYIOauyNaiOSsGkP/B6Ww3gu/gOXo7ubMDC1FyWIShfMM90sx3APnSmoXw7E58VHCIktNFq249nGXBJ8lH3YESzaplS/XYmCVcVcyc/Mcdi97CB8JWg8HXX+c=,iv:5tpxnwsLjrbcbZjCBe8XHzpnw8usrCvHDYUAXauN+/I=,tag:oI4chNxR1QndzPwO2fQrLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
