apiVersion: v1
kind: Secret
metadata:
    name: kan-secrets
    namespace: kan
type: Opaque
stringData:
    better-auth-secret: ENC[AES256_GCM,data:sWUQMNBokxEioXq+tOPkofesOwgWWTWghUXbPaA8ojNz5QgbRC2zQ+yFHq8=,iv:ehr4X7ZIFMvQ2hHEcUe74kCB9vIhYPdGuxRcrJTnc/o=,tag:o/mgToXp+GV4mItZM/WeBQ==,type:str]
    postgres-url: ENC[AES256_GCM,data:Z4mO23G5HhwgkTsu+8hdW3PWuLSFm/OW4hl++FNXpC4wUNfNZ9bpKkwm1gU7g58tLFcMqVFan5msyM7YK3KviWen2sokoOGDJx5oohh6kFn7BczpiQ==,iv:j0mTVvXymRORlm1l9cm8I5+R56+NJIMLNrUcBjea1L4=,tag:7PiwbXmHkPITuqYcAz1RNw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnJsL0FOUDJmUnZSTkF4
            TUxRM0YzYnZ0b2U2bmgrRlhYQTVxMHhNYjNrCkkrbXVoeU94bDViSXJYR1liUXp3
            cjFsWG9WWjI3TElPNjU1OVVvMmJuQU0KLS0tIDlSQ2ZTZnpFenVEdlNsWEhlRlpO
            VkpWWW9PdHo4R2tIbnkvQVVTUi9sOEEKOixdPj+GmS0ZCshFraxfvpMvZY8HyFQH
            A4S+DahQCqqyH4eDXwUzxR42M6icZvKSlfXglw0BILNSPpdRm54WEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T10:53:16Z"
    mac: ENC[AES256_GCM,data:mNKc5aBs2DASOacxA9De19RYSRHbwZxezlvMDdptxsApLSh/ksGm7KNc544nJulFShCYfT3fraRYDpu/UFkwc7YO+OzYIylt/NiEslVhzmOAl50NI87mhuPXyXL+lLSvz7ik6Uo+EYL/X0iSToa0l6MvBBYveSKJbpz5rQMFe6k=,iv:+qxtC2QWoL4byOlRU7JK5Kb525B9CYyKdkQ5oUjxJ58=,tag:lJvQ86zbBoBS3r42fFTTMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
