apiVersion: v1
kind: Secret
metadata:
    name: kan-db-auth
    namespace: kan
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MdNF,iv:4Rm6qFB1wQm7t061YKE5kguMSG82CtGRdiT8Xo4a1I0=,tag:iwXYlk+jLASYyOioxqmiOw==,type:str]
    password: ENC[AES256_GCM,data:1rF3rm74BYMvBg7QrEJ/0dLtO5e1bGRD,iv:LjbtLOQubl0mwpT3SO7lbHTvkgAfle8sm34QzV3etoE=,tag:pzguvWiILWe6NLGbaFCHdw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QjJQbnNIM3VhTHdKZ09k
            RnhPMjltWUV1MDJkRmcyN1RpMFBRRko4b25vCnlRNXpPTU1hby8wWnhQUnRYNk42
            eG1PZEJzYlBieXorbE5tcFNRbXl1WjQKLS0tIEtTbmVuNFYwcHprUnF3bURDMEVh
            S0U5YU05ZEsvdldaQW9wbWJnYTErQUkK/j4FtozKkeiJ2rlRTDDK89e2Dk4MU3a6
            LS7g4ox5cd8Y459eTWoF9C8qnyzCqGwqyzaDgiZ8b8/yVj44vV+CgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:45:46Z"
    mac: ENC[AES256_GCM,data:i8KwhBlOr5XzJ7saGvp9iwrdls/I/4DCEWl3CCKL/PbnnwM0/8OC84DFm7vsvMlIClhuqL+zHRIhWSM+9HxctEo5WUjFoICSAfAw86K2CUzrJ1tUqQ0z1hbA0f4rDixe0D3CA5+fJFy3z4vz/i83OQXMZ30UA9CNwSKQW5vipWw=,iv:Y1bM84Jf6kZWuSqrTt3ekRnjvw4adE5l42k7b2Yvry0=,tag:RdA0CPBEXDUhpR63ciSJgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
