apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:KhlHpAyYEKNl6v+ihpX72h1vW7VTXjjR3A==,iv:QXEm+VwKLgrfyshZNRHmcGh4q2iNanseWe75GtLeAnc=,tag:D/gTsi0KY5IVMspjd8/akg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:mEgEP+94/Ufjk++djNsBYAef/uPGFm5Z/Rw6M3L5XQ==,iv:gHWMW6yyFzRco3jnJBpJJZztnQNUmkxsoIyzhD3a8B8=,tag:K5AppN9KuNbVRoIHsnPsLA==,type:str]
    REGION: ENC[AES256_GCM,data:9GLI7GbDrqZij/wm7SY=,iv:l8V5iVx8M9zyJqIxEsVXRFKkX4EisghDInZl+KXo+/Y=,tag:17sn5IcnBBp8T1rLrcVkZQ==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:WXTSHaAnhkA05KE1L4QXU30t8hIo3K4KhZ734qbDLfYkbRbh6j7OYRg=,iv:W5SvciFO1sXwieFI6T3bT3I5+iDutQ2IXvfm2tO9SNM=,tag:iViXVB1GSYQjDx5DQHEG8Q==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWExDRkRKQ0tzVEgvQTZN
            U3laa2pqTFlibVZjeXNCNWRDaFJmYVo1d0Y4CnNkUXBsc1lQYlVqY1IvYWZVTCtV
            VEdRM0QwK05kU1ZNWExId3cwdFptMVEKLS0tIHBoU0M4dEFzeW41NHE2TUgwV3h4
            L2UrUTlLS2dTY2RBalQvaTg4dlJnL1UK/04MRVpqIIcZM1ZbSTJTo7Xzc5dK/fvz
            2wIbZzp+ee+hG/+Byz4MGvNIJCJnpaX/5gUdJiGsYMw99HTRJ0LpTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:33:36Z"
    mac: ENC[AES256_GCM,data:l/rigqNbRK/+Vm9ek88g6aWZJSlISWA5LzDIZXbLO8ebj4nvR1Hqq9vJkOVAE2iCgXhAF6ktuf7Ve2snfgqWem7CfsDzQbQT7JkirRMw7ysifKNzpAz1149C3s4ZCPB3Uk+tN/fsZ/Yt1fZ6EYX8DsNacDJiWVSHUnRP+YIp47U=,iv:Z02X7m0b7kYvSmz6kSY0SAxYboQd6/5FArEli1xGPTg=,tag:UhisGuY+tQmMlWQwcHYy1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
