apiVersion: v1
kind: Secret
metadata:
    name: immich-db-auth
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:I0MSj66X,iv:ad6lIG4VGxHtRltSJDgeLjlABqdvAFn1VxZyYyFXl6o=,tag:cNTaW6d1RYRb/rpV995J5A==,type:str]
    password: ENC[AES256_GCM,data:UIhURJ6pT2vQ5h4npr2GMooNhXyDDFE0,iv:cSuDHV1SfGlAGhTtp1Dn1IpB5tXDuCSEH4bQbBTW6oM=,tag:fenloCNmIURkKuTOXYzarA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTXVEekVyZ2grZWxrS0hP
            ZFJkMllyeTB6UThEWkkxY1pkVXRJaHFCcWtvCi9ENnFFMno3VTZVbVM4SW1UL21i
            UDR5NGNnV2ZIcVc4TkN2YSswMFVpdHcKLS0tIGRjYktNZjB4MmRzT3pUaGlFaE9B
            SUd2dkVWTUllU0ExK0hsTTFBZXl6WmsKAwYwuEh0nz7QxrOSeIcJXiL3Z3TDz+J9
            jLGtFx9Jsd4z+Py5Ynbaf0lgsXh6g5x5IB/eGgxhC3TU4SSYBMKICw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:50:46Z"
    mac: ENC[AES256_GCM,data:rR62Sprs0Ey0IA9+LZeOZJF2Q/rUy1IBzTw3wiOaP/TnnmtP5NM3+zjR5cgiScKVkVjeAATa0sCnMdiPut7ahMIvAXUcGd9mAlpWvbSTXCyabvIXWt4QIAhr4lX0ykhSkeoq4pUBdhahKC7Cv+4FNi4Iv443adoYvCMQaYQhbJ8=,iv:njyFNZ+Ppz/b8/E3cwyGh1NJij+kC+0jeq5Tqg4h5Sw=,tag:XDcecWxnCWSbxwPK5wDPUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
