apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-auth
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7/nV/ueQ7EBgIPCUmrLtgpOMt6dx/UkT,iv:9+kT7JZ7u1NmwsWlYImJ+uBBblaRlaAK/nJeyofnXyY=,tag:v/EB+j/jaEfvtxdj9WbDqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdzJDL3h5NW9ueTN6WmNy
            S2lSOHB3Ny9xb2J5Yi9wK1Mwa3dLdW94ODN3ClZhbmdvOTRrcStxS2VOWms1Mk1h
            WTh3STFhV3Q4czAzUGJaUkZQSjJXcVUKLS0tIHM0UElZa2RIdVZjZnBNVzk0UkM5
            VkROZlVZbGFsUEFmdDVtTUdPODdLRzQKEBEIzV1FZHNmh3rGxEqNdWxC+hGpxx4P
            KKrI49wVsC7gsyXzrCe0HhEnICro8kAsQ3Zzf2Z3Ym0T6I7nosQNTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T20:50:46Z"
    mac: ENC[AES256_GCM,data:JLoSuGr4tP/5NBSt1yWkIUwDu8sTJe7idvueldDT8z1pGFwS7pj3VcuN7JunjLQ8GzPBPRJJnygnTWtaRTEz16z7pquDXb6UxjdIrT+4jPIo///4790LWpcB/E9cS0lFCi9atsoCwlVWYvCL8WjmmP1ZLsuuIGBPSyAPQFWgx3c=,iv:gi5ZywG8tOV1cQvLeYWR/Vgn367geYP9T9gBNbWCZ+U=,tag:plQEStF78jisXe+B10pHBA==,type:str]
    version: 3.11.0
