apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-auth
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:7/nV/ueQ7EBgIPCUmrLtgpOMt6dx/UkT,iv:9+kT7JZ7u1NmwsWlYImJ+uBBblaRlaAK/nJeyofnXyY=,tag:v/EB+j/jaEfvtxdj9WbDqA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MG9DV2hNd1RFRlBXQWpP
            R0NMV1dLcXFVcXVNQ2JTRW54azRWNG9Pa1RjCnk4R1ZvU2dqT2VoVHUycld4eTFz
            YVFiV0ZaWDZFbnh2RU9idzlFR1BtODgKLS0tIFQ5MThGQXpIdkRlUk95VjdqdnpZ
            bGw1ZjJjbXVOQ0pybFIzOVZQR1lja2MKdiHzfiFTGkszPJvCNU3pU1LKtGTnSKjs
            b9f3YBISQCOsgFsN1aVRjVaACKaaguOCi74MtMHpOWfVsZR9UF4TOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:50:46Z"
    mac: ENC[AES256_GCM,data:JLoSuGr4tP/5NBSt1yWkIUwDu8sTJe7idvueldDT8z1pGFwS7pj3VcuN7JunjLQ8GzPBPRJJnygnTWtaRTEz16z7pquDXb6UxjdIrT+4jPIo///4790LWpcB/E9cS0lFCi9atsoCwlVWYvCL8WjmmP1ZLsuuIGBPSyAPQFWgx3c=,iv:gi5ZywG8tOV1cQvLeYWR/Vgn367geYP9T9gBNbWCZ+U=,tag:plQEStF78jisXe+B10pHBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
