apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - ../../../paperless
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: paperless-storage
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: manual-local
      - op: add
        path: /spec/volumeName
        value: perun-paperless-storage-local
      - op: remove
        path: /metadata/labels/recurring-job.longhorn.io~1source
      - op: remove
        path: /metadata/labels/recurring-job-group.longhorn.io~1paperless
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: paperless-db
      namespace: paperless
    patch: |-
      - op: add
        path: /spec/storage/storageClass
        value: manual-local
  - target:
      group: barmancloud.cnpg.io
      version: v1
      kind: ObjectStore
      name: cnpg-barman-s3
      namespace: paperless
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: s3://def4alt-homelab-backups/cnpg/paperless/paperless-db-perun-plugin
