apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-aws
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:UPTXqcBfD8WT643sh8F3SE8vtCc=,iv:lJv8h516eaVUzayc1TKUXZqFEVDpakHu/ewEuSSxd+M=,tag:A4dliVKghQBWEzxNqye65Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XcpjdXKIyNLE4wfgLdZ8Uu9x4u6NKaJzdUUiZbGKtTq923pSI5Yk5g==,iv:abe5AZQY9wyI3x/dmwSS812z4CWcbQq4iqplZ3YF4CI=,tag:5w+si6/pbVm2q8Un/P3TdQ==,type:str]
    REGION: ENC[AES256_GCM,data:zd+RH/NQaRyr,iv:AO1KKpvGFowJGqYRGzdpD9eyyknvYQHJM90anw7R7js=,tag:JCSLeEZfU8cTAReB95KJBw==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:G99uEAabNWGniQZMkQ+CnbEtaaIEn+RlasS8EcNLYJLocQ==,iv:0hOFbPdZHZPHbdISqxDBDoVqogj/WcT4nlqx9vkrils=,tag:sVFeveuV/EAGhtw6Elb6pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc1dVQmF3NStQSTJCc3ZB
            dThtRUMzWld0V09XSnZXY3RnV29zV0Z0ZHlVClZLcFFObklTMmJQTGIvWjZYTzNE
            bzdsQStpbm5DRTg2K3VWMFJpQ29qQ0EKLS0tIGRBcHV2eWNHVXZZUzZlWWVQdjAv
            SUw3Qkg1bFU1azFlL3B5S1BIdXNERTQKkrqAjq/VKMWiNyfNm485lAxaOA5kObYy
            9RGt/egCnJ5HD8jcU/rXakSmyZd+WOGOa6qkbBFDA7515ENyOvGWYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-19T08:36:11Z"
    mac: ENC[AES256_GCM,data:q7rYVVRi6tiPI5cN8cQMJiVCNdttconDjR77SrtPP6XFUtvojxNvt4laVhMWbbDQstnDHoBm+lshHdr1nCsOl/qpEIwY9LnHbWqeg/FFQXYDcocbYdTRHDU2GKSTUCjCHyoQ3D7AzGPDZdPQ4JOJ809cwywligAuHXJOuLIGc24=,iv:n//Ipb9xkjIPsuZAOQo7sG916aHcHPOuvBsCtoGDTcU=,tag:OP422VwNlubLcUtAvcaCyA==,type:str]
    version: 3.11.0
