apiVersion: v1
kind: Secret
metadata:
  name: cnpg-barman-s3
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:CF6Iwl41A1IaFn1MpdxBd8h2dtN0uLVTYQ==,iv:JODPQYDKEurE9+ARgvSWbUbrCaXDlCxVw/JSAxIWxuU=,tag:7CweqDct8j3nf1IWCUlTOA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:octwB99ElsNWqa3OeHwezU7Bew4hN8Erj5WUXKRLNw==,iv:ieHvHzx+LHg4Ou4P50Gzf4WA4wAYMTCq9xxJ8RX8e0c=,tag:J7OE0Pzo/3nQXMRZF0XK8w==,type:str]
  REGION: ENC[AES256_GCM,data:skLbKPWIUHpK0oqBjY8=,iv:AprdIo+W2AK6wh1YLlDpIc5HGeDcRcyQjHGgiJ7M4rU=,tag:qvL+sDKuwUnYCNki3bsaUA==,type:str]
  ENDPOINT_URL: ENC[AES256_GCM,data:QufFz60HObUkTEcosIIaXaPvhbwDHmX7fSxv5fDK6h1OCdN5NsTeH7c=,iv:3anqviT79AduvnUrtlT27WNZemkF2gQ4r1Dwp1+GR2c=,tag:rqb72AsBu2AsBQZEytRubA==,type:str]
sops:
  age:
    - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV0dCaHkzb0tXM3pxN1pY
        bFNkOTE4bEVJV3E0SlcxalUzUHlmeHRRZFJ3ClhMYytGN3dISFZkdzVISGllUWFX
        Z3cvc1RrajRCNFJIdGxUM3cvMGJkMFEKLS0tIFE5UVlzSDVXa0c1YUtGRUZhemxJ
        Ym5vK2hPL2psN3doZjZ5aXBUQmJhbTgKfuq1cFMwZSZhEMM+6Pg/C0UnGhERsAdr
        dX+LE6kE3rg5iILSvaKPKi+xOyLVUimyzf7WQYnISPorb2ClTmP3AQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T09:33:36Z"
  mac: ENC[AES256_GCM,data:tSfftIjmizX5vQlTQEoZwlqA8PvTPFnDwlo+gq8GGOwhW3gmmi/xRa0Ytyu9fjFvm9thMn+0XOg3ZVAz3RjbY9tkSN7qbpEyhQOg2+0Jnitsf4RJjJVhCpOElmPvIAOWk4vGTZ58l7lA+ftS6P8Zj8WpT2uTmW1CyNxGiIqEDPM=,iv:EhMgwODyfiVaSl3zNv+NTCZmOSyvUsRwfIXrX3X7Iok=,tag:BnGaNUn4bljIfCK0DDHP7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
