apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:sKxygyXJmj82l+A9QkHJ8gsyx8+oA3NNOSqpSTyMyunYkicCZPp1OlEulGoHcP5kmFNnlXI8Kel5VZ/zZllctA==,iv:hqWYVKligt9TaIIYcObsUskoinh/UumqZPvfCqSt40k=,tag:y9sfalkfU1TJpbACvDQ4FQ==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:sNORDO/3kgFNnPrGKlXUZeKUovYXteJR,iv:CPEmqdhXfz+8FB9+P3TwrBNfUE1AoO/P6NRX60Fzz+4=,tag:xt5jCVucHWWUAuwvGzFPqw==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:/hrhmEU=,iv:Q2V4cJSgzw968yJGWMFoEpTwAEbz6YZsUL4dxOggRLc=,tag:k0+spcF29vyuk8C7qSoT2g==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:kqrg9AHAJ9jWzFMzDgC9,iv:xvgv1JJ+7x6CxeprSh+xwpnrGGmAnZwZfFw9g1xvBUg=,tag:Pf20c/UWuwUy+3Uiq0bliw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:1qg1+kGgZQzS,iv:uVs7ac4/nkMSFkng8Gy0HW4BulllqPnxOUBRcZOCSS8=,tag:Lz7xvNffrTEiqu0KnaqWlw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:zewNVSWFfyK4,iv:AYJ5HHtcsowO22dOnvqgLRD0paK9OAsMAj3Ini2a2jI=,tag:FgD5/GbRkP7J9z+LrCNIIQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:y3ypzSWoGS4btJCw2dNhHXxbjiuk1v2eRc35yrZ+mbjXsgucpXycIPY7kBUhyppz,iv:DfkR6B9ieC9aHpyS/MYi66WsjvEpUqSZ2c5gaBRtDpY=,tag:xFnN2EVGzWSvp2D1aGq00Q==,type:str]
    AUTHENTIK_BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:gjC60CY=,iv:CDS0nkJ1zUzMZCIfnTAbkPUKiWZ/CBKF0sm/r7nPGAE=,tag:sSFkhQD8tVY/nfm65KwwhA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:nCFMkH5fF3B8fc+KjhHDgbQ=,iv:jVPackIwiizq/D6tVJ6xi9rKKMBiJJK/kkLt/+3d1d8=,tag:CFYS46MrpN0bFeXQ+ARzmg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:E3iNPpXNot3VXefOJtxElPdLcqyPVqwfoEh/V5TCgXc=,iv:VI4a0WYMJBII9FH2vH7OesSuni1xXnZ/wIQxZ8awXWw=,tag:neoEuaFxsg6wXmfusJgXiQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa1pwMWdtVzVuK0x1REcw
            N2cvTnVFOXU0V1hXanJublhieHF6OHZNODBZCjlBUnZhUXNTV1NFNnZldnBwRWVj
            VU1kcXcyRWJvY0F5YzdQSytNbzVSRzAKLS0tIE00MU1xUjNZa3NKZ0FQQ29Lc29B
            Q2dTMlpsSFROeHFQWUpjdVpINDRkOVUKKKWIEW2eYi/cKm/4HK9zZUqUAcQSAy5K
            lDKOTYpX38JET3GLBrFvuwbSV0XXhrrdMEMb539TDKl83ClRThE2pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T14:23:37Z"
    mac: ENC[AES256_GCM,data:4zOjYd9FuGrzOkohsficFrLnUIRdF4CvsmEstr5dShKIzObN8LSAwXkb5p2tjQWz1zaNKvnM34VUJIU4CYNp7dmzmqQfjKPoU/fhxdWUbr2K2Z2b6Jy0Pl0tzGAev4pJbQz8tV0VJEt9ppun+c6kDTZJK5MCFyxjIKxJjvqq1h4=,iv:4mGqFRtu/irhTE6cS7FtgxeI7Whz89SQ7RS0+sMAs7A=,tag:0tIBHPhnZ0pDwnym2V9++Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
