apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:8poY+q0kTg51+8Dlg5BEBtqnkzF2ATswuYfblBOdGQrY80yC88WjmrNWr9wwhTXeuweDE5fj55BUMELEE6j8fg==,iv:EkBZu6Mmp0qfJUUSY0RKvVIOnsId3eRON6TRq2ccZx4=,tag:wcUgpXmP0rksXH2oP+OOYg==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:jMHweYCKuF8tuDblq+4x2T4y7v5tXb2X,iv:bD1fhJeRmEaQ0TAcZdjznBe6xCocd781zg/fg1AT8yg=,tag:On9jrGEbboyJVWdwxrp/5w==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:uC2cXWo=,iv:HrFNKrj6ex5IJfaXwPcis/5fZt7eALpiqJz3nYJGENM=,tag:UIjHuBRrUMXJdHafF3z+0w==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:iRCKxe4H3L6AcJ0VLT2O,iv:F65WFOY7O+CJ8jvvT4pFU+uMt//bOVIfDqC+QfVd4C4=,tag:QjnJN23pc9AEPttbCuy/gA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:QqzCI5RXDtvN,iv:n8giXu5NLGswAJ7LYrdUwRza2SeXgC1eaW9uOy5raDM=,tag:ngZRTniDOsl4bUe9k0QYRQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:3x8L48eD44fy,iv:W0epu6pO6SASXdgN8HiBRb2w3fBu00M1Xq9UqZsBvyc=,tag:RKbG8pmdqTzkNrqu5QJI7Q==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:ALkgNqUFNXxplzla04MFxrKM81E1E5U+/nlTY8b/pWrQU7jXbeQD3umRBBhwkjcW,iv:1pwOQ1kfGoUfLxrRGmpXDHxix4wQbQv9xeADL3nQJxI=,tag:0EES3YYtMxOpK63xVF7CMg==,type:str]
    AUTHENTIK_BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:mOcjzAI=,iv:rWNlMzt9vtFDDTTS2Jttp03LZH7mHWcPdTqr1s88kS4=,tag:YfgnQd2ix6URXLwPeY90jQ==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:RNkGp3aeKruj8qKBeFqG4p4=,iv:g+JIsZRh2JJ6dJXdcSan0iJ9yI9l36Epm6OhlWxGDHI=,tag:LMXzccOIx4k0H1RqFjeaRQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:FQj1oZbnqOXiWcMieQpRCkI9j99poD7HGYuKX6vfKrc=,iv:4DWkP0CQhfWBo5/ehggso6tXA4/gxaDKzgTL/13/Ph0=,tag:WyH7LTZfemX/JKYv076Wmw==,type:str]
    AUTHENTIK_OUTPOST_TOKEN: ENC[AES256_GCM,data:4hy0SmRksLAuQktUgpgE+5phCkERJcsKymTXD2qdkPz4/d2GsQz06V0I/h//J0uvZI71FaAB3gWPDpof,iv:2bJimIh5DKtwa88MEHH/t7opGZf3xWO9vvSI+UVYlGY=,tag:AMo2XBlHC+p25edWGSpv7A==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRzRyVHF4aHdlN3duWUFO
            MkI2dXpHQitVZmx3dkFhWTVtN0Z2WHI3YzNBCmU1ck5TbzI2NXEvNDNTMWxoMjly
            Wng4T2NPU0tyblR4ZDlkclhFODFqaDQKLS0tIHlYWW1ZV2hqTnhmN1RWS0kvZTVu
            bFRaQXFGNGd4T2hHVWVYdUt5ZGFjMHcKcUt3snWsxY1me/aSqhiJpKNASEM8Rncv
            NMB+Cc/jqVd12SQniF6Y8jc8aCi4PZ09oBo4B7Rk4DVPZmUY8RqhDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T09:03:18Z"
    mac: ENC[AES256_GCM,data:iLrBEA1ZgFbDjkwLLBYl3bRYR6tTdbCh5SK440bgKKTU0i/4aTxewMSUxv2ipkWWFdkF4NFyXOe8ct+rObObLMuoyyV0dFEtavmQDiV0xvAKviqb8TIMKERSOa+tB0T3cla4RU8kUVMU96ngGRJ6/Mc6uqurk4wZVZEaITprHvc=,iv:tkWNoku+0bvotZixzRLh4TDpeS1heG/FtXr2UmGFNjs=,tag:eEXM2mt1ywqeuMl7Rc3zig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
