apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:8ELYhkgsEZxrXjdSgQAI5mh/LV/j1UyK+CH2RLxNCKcKhln1SpAhslwisVbbOfZ04ePsWicdoiqDqTC6QC7Zww==,iv:p31sJ8iNNKn0p8JsE4bRxe9RmZWMzk/fG//IZZH8cmo=,tag:quF5eHkvg+QK3t+06uzGcg==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:ZNRDXib1D94c9x2QbrpV0bgRF7ooPTL7,iv:tjYJSMA/l4hSMtC1EXKYXXqLu3lCGnkzNoi5vaakwjc=,tag:6Ny+435l4b+TP/ot0YEiQA==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:/57SVpI=,iv:r4tdAIj8MeYIHwY5By3JxrpDEZUVfHOXFXuW8uyu9ug=,tag:Ha7REdpWu4aEGa1+ifleVg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:3UPnTHWB2b1hGZpT7bWv,iv:gQo8Kzxqk43brgS6++J4nC2FlvZgagNq0BGXi4HYBc8=,tag:osfMv8WjBhcKcdq1tuyAeQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:w2lJAwTX2vew,iv:QI/dktpWpSco4eMonv+wbsJBpBOHudEEFOQt0unAr34=,tag:AtITRlCSQ69jN/7xuzvwZQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:jGlkohgPZXb2,iv:pro123zpwXnlYYPe98Gz6XXzmwAX0H2/sZaaWG/hUqU=,tag:rlahVodteEsM4yAPvRASRw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:s9oPtJVpM3CxVx43St9OMVLOzp90+Ve95e0TN3Nm0ruAR9JuKMHQbC6kuuodE08k,iv:p2zr6jUj61XtYPle33zWtuBU+Yb+G3d/mXhHypThfUY=,tag:6KbJwDiVTEjQ+emuXGIHoA==,type:str]
    AUTHENTIK_BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:nhcBRik=,iv:HobQTfM+B39gNqO7/N43zRCoxadyAIldNTfMlM8G1eU=,tag:LwwJyJUSpS1LI5NUdiYzqg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:StJtrMc8GvH2NATOsSdBKis=,iv:+CPXa6yQ19htHUJOc3CeCHB7cEvJ5bs6zPH4pVNvRkA=,tag:X5ToxDtJT5RrEZDZoE7KSA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:uOhnzNSnRy/PbyRyFbukVvTNL+DnnShDkaArC24bSLs=,iv:Wgbndw1MsbV2x7IQ9GU2X8a1Rby6Rc6PMQgXYw1nLG0=,tag:4ZSWb++Qd0xsEgipl848PQ==,type:str]
    AUTHENTIK_OUTPOST_TOKEN: ENC[AES256_GCM,data:VtbXtpHgT3D+ssHspxpqB+0dgR5ni5dxOfisEyfFDbJF/ZKyypgq4lvWReno9gr7FQQKTMRgMHBi/Lem,iv:yX3E9ehcr0GNbRUkz5gzvFhIjCGTJBbPsa27LleLxQE=,tag:OqWsSaSusEa8GyJezc/TzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSkkwcXV1YmhLaDUrbisy
            QzFKeVhQMWVtS3ZiTjBKWHU1ODhVUENiV2k4Clc0aXlhdkVGMzgxeHdJRERnU3R0
            TEM2bWwxc2ZKMTZNRUxpeHd6cU90a0UKLS0tIFhXSXFHek9BbGJQZFgwYzNDaytN
            OWVkR2VsdEhvV1hnNFJ4SjBMTDlNSk0KWZTiGpQCB4Y/HKafRQ4ps9JnI3M0G2D4
            ahPStP4kd8ZwTfZS+ny1hdU3TBmVG3dPunHEFM3b4XnEXDKzI1jcqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T10:05:40Z"
    mac: ENC[AES256_GCM,data:2QCXmBLZ0xunAuaVvA6hG210LchbEsB9xg7zh98KxsDKMxC8b5zD9zq1txsNghJn4LxSt7FVQjmQeDFnvsUetD8/etIlPAfjXibK8WcP+qAjgGsZE96ChmXQC0SSGRXOmTwcwpML+jLzQrJP+M1Xx/4Dgt8uA2TmXAfVhDb57vc=,iv:2NHECdO6S5g/P2Ngz1cSK0XhBP5+PN+dQBqeVehTJmk=,tag:D8wZSuHd3n6dhape1DTD2A==,type:str]
    version: 3.13.1
