apiVersion: v1
kind: Secret
metadata:
    name: authentik-blueprint-nikitos
    namespace: authentik
type: Opaque
stringData:
    nikitos.yaml: ENC[AES256_GCM,data:9SCtDMsNCQP+N+sMXaEpbCmmVYJ0WKDwvFzPWIaxbMqBuVW+Jeb1ofms0vWrRD87T8rVrHnTuFdnOLYoZ7d8Dqas4Dx3spNxm8TgluJKKJ38gthEiv41bxktwBuaXjEsUet2ZVRHdfN4V/jW57DI3qDMgUICGw0ANtvbhpOzk+Ihc7mwFNkP9XgzEUbxvwgtB3asDFEJfaknk4SuZBI2LjIfOqwdbNe3rPMmb/wJuftinGrwmXzZWQ9JhdPDSINXJbe+X2YQbVKYCeWZBg6XDeGK72zm2g3lJUyblnYk2/ZujTek2cRF/nvZ4DmFPdzDv5J6sS25B7ay7QJKfWQuwRfeLSpjGJwEDU3nQ+g2IzbW1S1LDNILIaUyM814JQNNQ9iv1yyHY8gEOgs1u+5Vyf5qOcs=,iv:X/hcjlpbAVXrhvIQl02AhoY3ezU4ZOkZcq+b7pum9qQ=,tag:rES1896SGcAocvSOK7f8FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXNReFdLOEJ1LzNHWndF
            RjlHWmpEc25laTBQaGEycjg1c2dBVHBITWpBClNBRzBjMStpWmNCWEJ1NDNYR1Ja
            K2thandlT1ZRaVU4Ty9oZURGOER5VW8KLS0tIHZOOG43dGYxVHJGRGdiS1BUM3hr
            aGo3am9LQnlMSlYzeW1ZRzE1OXl5UW8KYDIdhvdK22SWcVx3KVfPaDmimw4OTrzA
            +1tgq9TTksLq3K5o4a7hSWmR9/zxjbbaPcoQFdwwHTZtAf0+9+4ePg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T11:25:05Z"
    mac: ENC[AES256_GCM,data:7p6f5P2l8BzPtoxsAoCZcTbSZEAxvNA/iUiVFphK+bbj3TlfZsa0PCnxUtG4rxpYXi+6hU3u7Xm+IVnm+behEvYfe602murrNJEoAgAxB5fvcV+q9xzk97DZ+yX84ld41rTqrpzu8yIxGlwun7k3srU8+rURmkGk9MQnTTnWGxo=,iv:sNUBfzOzuMuAA2V3aimqIt6kk76Cp+xOBDgm8rWHgg0=,tag:gR1VbfQjoOUzNluGRJtBJA==,type:str]
    version: 3.13.2
