apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-auth
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cHx0BTmeaiIa,iv:Ro+8DIZ6TLbmmb3DR+wlB4tZORKGh8fF7lR9ndCyh6M=,tag:I1PQzYfUPeydX7EfVzm75w==,type:str]
    password: ENC[AES256_GCM,data:rbXHmIyyfPL7tQwTJvjVToYS8b2l2EvyzxP+VxMSM4ZWn1YC48WYx8f9glSCCNlK,iv:W9JVx3+T4rwKnbDMEyEnbraX+JVYxNGPMBPdRBtT1o0=,tag:nKVxQ9d6S36DtkDYcDd+Iw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSVd4RHRNcjJ3cHRwMFVC
            MWVYaXNTWkRkdElmWFdpdlhEK0NMNkNZUGtVCjI3UVBFakdkWE9qTFVTMWg2OXBJ
            bWZuUU12VXF1RWkvQmorWWRPWWxxK1UKLS0tIEpVNDRlQlJQL09NemlnQkJwNUxo
            SDNlVkJwZDZDeXVwOWlQTUs1VFBzS1kKtFlG8hZv6sV7I6QHQi80sfOwkfEsxI73
            43TxThFzfreW+Og18enUjbXEyiU/2Jp4lt2c4nNIRyZjqE0M/XasFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T14:23:37Z"
    mac: ENC[AES256_GCM,data:SdWdPVXDoTCA7msd3/aXThdbUV2n4VUq6zmMDaTNGGLiRe4d9Q1pRQ4P3i+MKU7nrMmwXaO5xH9apUKZI3fuwZezzQ2hz9FO6jKJm9PpoBIbh2hLaOQFebJDuEt1L5m+owvpKuVXM4+P957CJileOhYQzslz37/v53UQcdFp0XU=,iv:W9CNNKTbm+7yTwPZm7DcT8jNUb0jIAhub4hrBGKcIdc=,tag:xVeZLowBFSiGiIWizc3bCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
