apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-auth
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MAzEPLhPV3bl,iv:9H2qZ0ExxxE4TWc/vjhB7A+SgrW4uWPI+HF2zf8EY6U=,tag:zWi41ipLCiHs5iLzDCr7jw==,type:str]
    password: ENC[AES256_GCM,data:vTkv3vWFe6yucjmO/xIz3XVb726hS5qmFGPnQI/OYCqExrbcer2nJDrmuvjhR/Rf,iv:ESUTu2M5sQJosmvCRrGwAxkYjfL1cucUkTYS3sa2ATw=,tag:QIKyIddGXzefoLXi4xnnoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcEU3SDBtOXpFbEFHbFcr
            OU5jelJGbXkxY0xGWUFYUWdieU9tUU4zaGxZClNEQ0l4SmY4V0VSekxHQU9sMkZy
            bWZCZXZLbXROMUMwanJhdmwxVVFrdzAKLS0tIFpWeldxYmhuajJ3L1NuYlVNTlVE
            WWxxZ0tlSks1emZoYlRNaGo3S2VZajQKTstnwxpkKgoPprNylTCm409DrQ5Xz9fD
            4NW2nQOe4NA8/lXr9iC3V0Qk6j4p8YlJJRVVIKbUzNptfHvNLWBoOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T10:05:40Z"
    mac: ENC[AES256_GCM,data:CUTRGwPhA2pUfeoTAtniRuJLcHb6t91pG35dYHMJkDX5Y5PJp3vNXV8My7LgxRsOE/b9nBLjZzHFrNJcRZ38eoh5HNeElYqF1lrmGW/GQfI9pWSJ34H+FS7EUQx/nreYohSe6Lz1B6UWZBtfQnAyNpJmEjqj5hjdhl7ccAFo2WU=,iv:IuuznRCyfJKp5pF+DdbBNt3S0Twpl1uSCxOOYKpLEtQ=,tag:YpKkLgFGozbJv7cI/ENOWA==,type:str]
    version: 3.13.1
