apiVersion: v1
kind: Secret
metadata:
    name: nanobot-secrets
    namespace: ai
type: Opaque
stringData:
    venice-api-key: ENC[AES256_GCM,data:GgR34paNYrcDKtyEiTfQE72+vRDVoGKzJ+bgDwp8f9HxPrqGMuKp0o0bqqvjL+KUer+xGOCrdFWn606j4z9Y,iv:/jBD7qjamdzLV2rpfYCvorABhSlyBWa654kiMXGGonc=,tag:IAmad5IcCSBzkCYMaWvHaQ==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:7BhJ0as42zs8cqrKRBHpo1fWjtvSIFuWvJ5j3BNxA2st2I5djsYorum4mmoG/A==,iv:YzCM4FHRvpKaiweuCIA746LGXqlSZPJN1e4LuG7oa74=,tag:4cBCbH4OdcuHZflya/zs3g==,type:str]
    telegram-allowed-id: ENC[AES256_GCM,data:qsSEy8CdZypW,iv:LFpIM9oqzuOjKWZHRagTghUHEX86txv+ektMIAHr04s=,tag:jwZk2OdjcT0SE4SrzDXlqg==,type:str]
    brave-api-key: ENC[AES256_GCM,data:T+AT5STTfZeWTL417varZHnXXu04m87ABbAme119+g==,iv:kJiO53DOVjR2TYS8zG/48utsJSm91TP9cbfTgw7lnb4=,tag:kEhb5RWVC1IU66tEE4ATSA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bUNzUVJiWjFTaHpnOE9R
            ZHcveEpVcEhMTmFEZzBoRi9xdTVwR01DTWhnCk9YbnhOTkxkcmtndHZrYTBxTHVL
            aDVwSnJkYU5sUnJOQnI5Um04U1grNE0KLS0tICtObVYwNm9MdEVEMWJya2pnNkVU
            TWVQcEpxL3cwc2NlMjhsd3hldXFDZmsKdy5xFSWY86V1eIhQWdXOBQ4axYzSsY/P
            0Oy+SVxN/8/bUfPFVhSNMhabHDDxO7AhVDfDjQ9TWk8FQz4UPPzpAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T14:01:11Z"
    mac: ENC[AES256_GCM,data:Zf80BX8yVxIKemhKsjvZ/WKAUiw//3OZsGAUJRn7pY22oxaoPybi+kuoSwGnAVVFd1jom6FBdFVUbV9uK/Lq9gg47fq9gdCjPnM56kVl4yXWK3gr11XJoVqfQ57SV0WeevYIsjR8ZpfhaZxuru8SMs+dpTdiW/aX2hAZ7kwQKpc=,iv:/0XSeqlEF5Ow4gsoJYXksDqML0QKO6BvoFzPebJxn48=,tag:MXQlu54ECcJOi6c5v54IQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
