apiVersion: v1
kind: Secret
metadata:
    name: nanobot-secrets
    namespace: ai
type: Opaque
stringData:
    venice-api-key: ENC[AES256_GCM,data:3C14pxOHpbuVb7yA3YcOP0KF6mWxDeU06KAzXeKssHfJlmKLSF2L3+f2rt/3SP5FGc7TD9SVCfNUH85eV2BP,iv:E3IaSYBMrFNGhiM6bnC4wMkK177Yr3oDOnBdy2DFlV8=,tag:s+VeVHW0m5DGF+ApMD79fg==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:cqfjgs4KSMAjPDH43wV3D4a9iCx5vGQ91nRxuhqyqXjrPnHa8IVWnfmNgTT71VqXi5lQQmOwgLqaaukYdstaAMIhvBXSa7FwVA==,iv:tOrDKS0Tpm+WY9VbrVLLjxXTHHBOdS/mh+MRPmE2e9o=,tag:tXVl7QmkMr51aY0Bz6rE5w==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:GWrl7SVUpXNZoBlpftAjuLjtzwAjmN6P+jbh2GZj68JJrgUDvRDf4p3jnMevNQ==,iv:56OQOequqY5uI9hBu/+S3aOxsg9Sf6GHFCErx8nWPSc=,tag:8FhGqZbnsgIiNmWOUI6sbw==,type:str]
    telegram-allowed-id: ENC[AES256_GCM,data:5yfKVe6fdM4V,iv:dMerWXTPZGz9Wu4G7AcZ0kQJvu+R3Q8gSC/6gtM7Tww=,tag:NhULGUeg0u7Y9ZEGpqTolg==,type:str]
    brave-api-key: ENC[AES256_GCM,data:3/sM3qeZeJ9z7Crb9oEpWVOjTj9+T9LDp43DKDYCVg==,iv:Q0tosVGjaCJC+iPGe405u9RVbzHuV7NvKBlQ7qfJgII=,tag:pP6g/9QnMpLfxiHf/7G95A==,type:str]
    github-pat: ENC[AES256_GCM,data:5MzfRj7rnwsSt3H+56NQ3tBEwQpJ1GeSX76MqXSMskJBwsjdmSgLFaD/LuYGSkmJke/S1xM4kK3HA6YyeNlcqe3JiYhSeKXkmOPoe430ypgI+9TaWwPWVPeHyQxM,iv:X2it3z/tcHosNY53T/rxCljBRRrxaAcYxebfSigtVtk=,tag:9swMfX3ZFNKO5TGSgVuZ1w==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQUxiSVl3elQzaVIwZTJs
            MmZIaE5sVEVQeitETGlEWTV5eHl0VU1QT0RVCkFybHVtUWJlcDloclhGczNQS2JY
            SXNWc0crODlMOGt4VHhIQXhvaFJYZGsKLS0tIERtTG5HVk5uQUJua2VQMTVDYnNn
            WnhhWXpxcTdQbSthMzV2dmFTaE9LeG8KLGg6R+YkaOu4ypgUFa9kkRLEb9z9Gc0C
            h4aFK/EZtxSfw14Kk1k5Nuen+U4AXT1ioK4EyIWoAN1WposSHZmc9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:41:45Z"
    mac: ENC[AES256_GCM,data:kdRcRC9zMF6V582gStFSTYai2sDmyoZCoNILwdPqrMeU0AR9vy+lpDLSIwj5XkrC6uOEb+oWqOPf8VgX4KqrFAITPFGB6PTtJ+7xJu0uzsi2oavzqHAs5Q5x5U5fozvEWV5qZsDEuQc+Yy/2AOlioC4NaFGveQRTHnJCpZcH6Qk=,iv:Oj+ZRs5lLGctFBx+Pou9wKsEfGL7nS6SaGjC3fy0SU4=,tag:o4AZMe1nQfFf8gltmgCM8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
