apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data-local
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: manual-local
  volumeName: perun-transmission-data-local
