apiVersion: v1
kind: Secret
metadata:
    name: transmission-wireguard
    namespace: transmission
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:mlOYeDf3y+hX6W9gwHx47bjWUhu/Wle7JhjD9ZQIUevD2/3tHI+zuuoBFq0=,iv:t+Br3RksiNntng9JttiaZXaI+henNnb5jV58/KDai9k=,tag:a5+qBWgf3hzNK9X+tVVOnw==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:7NDrcw0ySbz+kEd61/oOig==,iv:iCA+Zgk286ZvgIg6uDf4HKeG2HgmTW4fz1iBzc86YTc=,tag:1Ov75zqRtSDt5Hy6cpfnsQ==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:I6vLB+LaVdCVu9IKufPOfNmgTiRxxrfMyow3bzr3BvJ7vmNXmr6qXE9dZCM=,iv:oiNtyS+nETptSwShSEyTvj+bcQ8e52St82pr4hcDizE=,tag:5HPmoO+fdWBKcbOaHwzImg==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:bDILv5UFWOttomUq2w==,iv:IfvszOZd3OPb9d2f1JqRdn14pDfR4CRYJ0L9yHSVMLM=,tag:1Rf4BfGuWBy2hl+gTKHKfQ==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:epuwrK0=,iv:CAW/dF2uBerXGIJKQYN2WzHuMi8mxyTDzu4KPFJ1Vl8=,tag:OTg6104AJLDcybLIuVHcXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZS9RcUhjQ2RJNU1lZlVW
            WldzMGw2Mk1qRlZLWGFFbzhYTzNwU3lKcmdRClFQKzRPYzF1NEpheFNycy9ZMnBG
            ZXBORlhQaUdJRWlvZTgwNldhSm1IeE0KLS0tIEluc1lYYWpsMkd2NzJncWl6N0pC
            eUNwS0ZUUkFFUUpTYjMwODRxOHhlYTQK+J/AnJ6O4J/IG+q0ljsDvurH9xT7mYtv
            c28OVRq6YDX7X52qdk1AGyvbnbXg4oPwM5Hukj0YK+1n7BWFHePaJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T18:03:47Z"
    mac: ENC[AES256_GCM,data:jSnM7uLCWpFp1IbMtPSGU02LmMgOoXQ6AFng7bK4RI8jAgJXryObzalmQhVGeG6a53j5x6tRC2eTelaHkH6B+3AcLirtuVPciak33lyjNgpcAX4nUcJJ0upIAST0pxNcH3APm4jm2rABY9cxN4rIAHSU9EZoH0Xxc6bx+AXrpPQ=,iv:leSnpdZkRNyBxssgY1tInDJex+fBEADRKv/hRQygTZ4=,tag:C5JckqHcq4XWskQCk/lZFw==,type:str]
    version: 3.13.2
