apiVersion: v1
kind: Secret
metadata:
    name: transmission-wireguard
    namespace: transmission
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:IeJGz8Hp5/H7Q1bE+0sjNEgeoHMTC/qhsoVB6M51n+XT3Hll7/c4F0wdXDI=,iv:p2mlc+xeimtnfdTlzFXRLPSqOFLVKS/9wD0/RHe5aJQ=,tag:olxTyFtk6Sq5z5FU+U6nrQ==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:n9R8vh8Mu2jvAoU+RoUR6A==,iv:q4hMNQqzCIwpiGdm79uv+YcPJM6TOYx8t8jfnktKJdE=,tag:YOIesW0WLPsAgu+5pDJfBA==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:DCsg12cCK3lGEayy9KWG2sZKx7HSFX7sb1kvospRtUK1xAkrwbvekAA3+JI=,iv:EpXmhsj0+L3u/0VdmbTuU0VmE+jG/DMUP2lpAcS9gC0=,tag:NyA0GtwTzS4a5Lf+U0TuHQ==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:T8iFXKbG91r0AZgrfQ==,iv:TJIteO8srhskzgq7v+ht4XF2BzE/+Zjv9iwxn+gl4yg=,tag:NorlRshccBnMN00uyoKyhg==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:acdGGvA=,iv:XcqNQwaEErqRVkM54cF7iloPGPQBnCOfWs1somrEUO4=,tag:dkHjVIVTRn+3vj3TF/QLow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb0xqV01QTzc3UjFwRzJM
            c1JGSFZxdEF6S256ekZpdFNZZWNWd21Qc3h3CkZYTGduL09kME1kM1NNRDhGb0pq
            aFI0SzM0OWxPNGsxc1BEVXowa2tEVlEKLS0tIFJSMkdBcm94bmtmUkV6U3JTSm01
            bVNoM1Z3TDhjWmU1SGE5UEd4cTE1MlEKqztKh1jbVNdlez9z0XZsTC3OxHI1Oxat
            OIGgAgsosQZgl5dGWy8paekdg/e8C53JrZ+1J1p6hsfCtePNHNV4qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T17:10:17Z"
    mac: ENC[AES256_GCM,data:qz9aJQdks/u2ugRk+//i7jQIUxQn5sSVFITKF1tym1kINovIRj54Spw/QTaXeTZ47Ut/ZTI08VV9HMJ/8a8Ucyfix4Lf9FJwMoXTYTjx8ULB+k2U/pfD/8lmBXtsRABC3CFUzVKA06l4Axa6Ea8RHwT3vvy5HDwVal7RwqxtLK0=,iv:RdhpKZ5vPHJ1pB5Nj9LOtR6lau696o/YA7AETSiblnE=,tag:wlwwnUrmgHi0ROg1CJuJoA==,type:str]
    version: 3.13.1
