apiVersion: v1
kind: Secret
metadata:
    name: transmission-wireguard
    namespace: transmission
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:IeJGz8Hp5/H7Q1bE+0sjNEgeoHMTC/qhsoVB6M51n+XT3Hll7/c4F0wdXDI=,iv:p2mlc+xeimtnfdTlzFXRLPSqOFLVKS/9wD0/RHe5aJQ=,tag:olxTyFtk6Sq5z5FU+U6nrQ==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:n9R8vh8Mu2jvAoU+RoUR6A==,iv:q4hMNQqzCIwpiGdm79uv+YcPJM6TOYx8t8jfnktKJdE=,tag:YOIesW0WLPsAgu+5pDJfBA==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:DCsg12cCK3lGEayy9KWG2sZKx7HSFX7sb1kvospRtUK1xAkrwbvekAA3+JI=,iv:EpXmhsj0+L3u/0VdmbTuU0VmE+jG/DMUP2lpAcS9gC0=,tag:NyA0GtwTzS4a5Lf+U0TuHQ==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:T8iFXKbG91r0AZgrfQ==,iv:TJIteO8srhskzgq7v+ht4XF2BzE/+Zjv9iwxn+gl4yg=,tag:NorlRshccBnMN00uyoKyhg==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:acdGGvA=,iv:XcqNQwaEErqRVkM54cF7iloPGPQBnCOfWs1somrEUO4=,tag:dkHjVIVTRn+3vj3TF/QLow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWm5kVnlSaXNlcXBtbzNM
            ZlRWcFRRbStDTEJ5RmQyTUxvT2ZlSEdPSVY4Cm5COC9TQUlsWWZVOTV5cmRrS2ww
            Q2xEZ3NQU1o2QjJ1d0hFUDl5aUlZcUEKLS0tIEFHd3l6NXF6a3NaMXVpc0d0ZUta
            M1NnYmUvWTFrSFJzRVhiZjdvNlB3ZkEKT23ABNlnxtJdk51iw9N6K50nNYmCaBkY
            lzFhfD+uZcI9SsrEBby2vNPT3u2o8SvY/kSLKhhrJFH3WznLQ/lGvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T17:10:17Z"
    mac: ENC[AES256_GCM,data:qz9aJQdks/u2ugRk+//i7jQIUxQn5sSVFITKF1tym1kINovIRj54Spw/QTaXeTZ47Ut/ZTI08VV9HMJ/8a8Ucyfix4Lf9FJwMoXTYTjx8ULB+k2U/pfD/8lmBXtsRABC3CFUzVKA06l4Axa6Ea8RHwT3vvy5HDwVal7RwqxtLK0=,iv:RdhpKZ5vPHJ1pB5Nj9LOtR6lau696o/YA7AETSiblnE=,tag:wlwwnUrmgHi0ROg1CJuJoA==,type:str]
    version: 3.13.1
