apiVersion: v1
kind: Secret
metadata:
    name: pihole-web-password
    namespace: pi-hole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8VUKcdIagFeLWAqOTapK81Yay9XZFpOs,iv:neG/05t9Z4iNjzh0h5eRPuN4GJBVfvr8C8FK2OsB0JU=,tag:rVrge6gOaeA6Gbk6PpFuew==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoclFXQXpIalBDQjBhOUhJ
            TWRwakVHdXRhSzl5Wm5FYkRsakQzZ0lnd3d3ClN6MEd6elExNEhxV1dNV0YvclEz
            c2NycDIvL0hmL3RNaWJtNEpNd1ErejAKLS0tIGtPemRobVlZNTJKWEV0bk1lNWJw
            S2pTLy9pSHg5UFlibk5XZmpKRW1KMUkKEf6Bfrx8oxu6JvHbV6TFG40eON2TyVV/
            tOyjyNrw1qTG1pKzC3Re8mmZXAZTe0yubbnBdff0x6UtUhCh+dzNZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T17:38:51Z"
    mac: ENC[AES256_GCM,data:hYz9ITdwEChBZ66kTPXhz+UM9PpCP86PyPa7HFP2QD2g6rxQxfEQGulaEAy0b8JGwcm+yT3383HjV+tI8MBoX0+Xgf3a+B+WmYTZFR2DRCklsnrxYV1QTGOVP13SaVt9FVYsENK8+79RscOTITboSjPlLzGVXQ4uDnlqqB1Ihqo=,iv:KxpBUYHcJLYSVdLvJFhWBPkBaRnbthzGlY88+mg+B3U=,tag:EnizQ7/ecr3iyrk/CGSPOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
