apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - ../../../paperless
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: paperless-storage
      namespace: paperless
    patch: |-
      - op: remove
        path: /spec/storageClassName
      - op: remove
        path: /metadata/labels/recurring-job.longhorn.io~1source
      - op: remove
        path: /metadata/labels/recurring-job-group.longhorn.io~1paperless
