apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaneo
  namespace: kaneo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-authentik-forward-auth@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: projects.def4alt.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kaneo
                port:
                  number: 1337
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kaneo
                port:
                  number: 80
  tls:
    - secretName: kaneo-tls
      hosts:
        - projects.def4alt.com
