apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaneo
resources:
  - secrets/kaneo-secrets.sops.yaml
  - postgres-cluster.yaml
  - barman-objectstore.yaml
  - scheduled-backup.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ../secrets/cnpg-barman-s3.sops.yaml
