apiVersion: v1
kind: Secret
metadata:
    name: monitoring-alertmanager
    namespace: infra
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:eZLAqOcGKrQmlJUA4l3dfYCcPHFAptCL5JTUBYjm3UUyNJbPATMQGcby5sJqp1D1WRFdbcjQv6u1V5WSyupmDDYApX1T+U1hVf8U2D/Zs2bB8zNMcYFgQs1NyC+4DDqboK72hQ87M1FTEh3ExXYxLqqbojJSaFtyoQPakSIx6nC4c1cK4GiGWiLqXtq2Brjl+6zg+tX59xubDPUr47f2BWwHcojtyYIXl5AOQ74oDsxX4sugRgGQ5b0vYSREnMIVsDcvP5w01b5RPmA9icwhJ8TZniHafaUqey+50X9v43UdTGDCNU+jRB/1Ohtz2u6M8QIBAwkPO+xH3QjocBX5HObxr+IpF6Aucz1xQ6595+yy2UIcC7/AxiELUye643I8y2BnYn1fa9kOmXCyGDbnYAgoIEtk/3z1WWad+GUddlhsaL8U4NXMNbQBbUSx5IVQWnLaK9YMANhczwFSYQS+l2LXwyj2cwhYyvezmFHHjXTWB/sdOvkRvU9Tq6IszfypEmpWDc9MJpVTRSUoxOZVeHW4U+vjbcEmBVXWmDcRYjuaDYJaWFjr5yaMMuWGVsU9vhD+Jh/RtOShBx5LRGEx4ezqrc1Ksq2Gf/N8CoOKfmTbv9MlYXqwY6kqtPq5O4qux2TF8eGyVFRc8ycWW18jLHeU//NbbYFc8xvRqpBkO1HAuifXnv5Jqa8MQG4GxbnAPOrMY+W92gA+0+P5F4WI/tpEbY2mfgKlmsREZQjC8rpWPUH5YxxWB01Ef9m4e5mlAihOC5pYTDwN67uSNN3xaPSdQmqY3s9xfG0iPksTZk+cpq/Caq8L4jHfu165HXRN59d5ji+i8gcX30Ev8O4OmcGUoNKgM+VNcHti4vwvKZOvNCVvpnkPDM0SPAecOtertPh0esMpRZ/cHyucDiI4tSW0oXuvZ6BLxxdIM9dr0YpFItijLav21ajPQt1JVnKKdsiGe2E3BbEcooX7xW8lVUgXjew7ImKFs9NgsND7v/igjNro0yz1J5SK3XMDf+oZpLEeX4j88cE54sFAPhN6MR+Vqm+M5EPKVOELcX8Ha/+Kt3iaZLvKZETAfN+4WDvBS0NDNxEXa0E4yD3Qz8CjojVYcLx4/LSOnYNOcwPoc/PjESpEzts3FvLmRe466hsmN0r3Y/Dwmt8VVWckgnehrcqraQEAh9sI9M8oOKKvJPfiCMjBaOj1fteWfElTqxhWzKnvW5YAo67LKJWBfhHB2GGPygBr0t8IGYcg+pzJkv3zLq8vlEYG26AzM1Snd/Rm6fQV0F3nLcVLZpwiUBRLvRIRtbwi4wBSVliJByJa4oMY,iv:gxkaj3hFqrx5xSRYTTQTEWWqbQu/6bNWGaIPV5JaGN0=,tag:bR+d9y6tOC5+fDOLnmSoKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aml5V0JBbzFiZHdTUllz
            OEU5OWljRVZxU3BlbDQzME5oNDROdlJiUTFzClhuUEZmb25KWXlUZXZxRy9VL1Jj
            ZlkrRll1SkhLemNMOXkvTmxnWTRVZE0KLS0tIEN6MVRNTytzd29iM3pObVBZQnhh
            c3g1UUthb3Rqc2RJd1VQc0VvS0dtaUkKkFzs+zhRLg9gKq//uXF6u9r3N/BKjI6X
            svV6hDvcpBOrCwRJgVHDv/wbJNsjTgk2hPod6c4iZZpd8GD69W8WRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-20T19:22:18Z"
    mac: ENC[AES256_GCM,data:F8GFtW5Gn2DoOkBCOI4HZxd+BFXHBoP6XqElN8/xyUU+68IO1K6oPTgBIGZruP5NcuA/ImJ5GpnljuYonNazXPHaOLtzOKbj45GtDqGgCes9iHKq5911OmDu9F0QZoD2MuLjz4nsXb31ctttvkTBfhbUx17KkdEIG5q/9lpV8s0=,iv:TQJC4O742Ttpez28y3PHairx5uEOfbw3QukbBxhx/v8=,tag:3kg7v6v5BZ2XJE/hYsWzmA==,type:str]
    version: 3.11.0
