apiVersion: v1
kind: Secret
metadata:
    name: monitoring-alertmanager
    namespace: infra
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:CJnQbF7UzT6NRz6hmCGAlzgi2z5MFQ3y1XSIy0M08hrQXoMuzavLM9geOjovg6yjJx8QY/914thLpRXj0ofhPMrVWAurhFgMKFH8P0xxUfcEER97Lizn/LrfwJxyk75xEWIiNDh5ve47kA8UkT2G6FpRI1JfPnto82G8lYPppLMxjvwJeHTwsTET2/MGUfU740eLuS/TTpn4TWIoGo8PJe941oHRMjn8HvB2M3+2WXi9v7iNPggQOGtZ2ruUIY7WZWeFXwnDFcK5QQ+ujZYCMsLnKZ/LAe27NmMP+s0d+qukIqEBGHPZZO3pl/4tqQe3WLUmXv7n4c5oQuPIxOaJFFXulq7nIn736zg9xYy48xCctQrsRRZKVA1Nszlh4vT07Y6l+HS4oS5VNyEVeMFhkGWZqplXq6/sIS/5ahlT4QLkFAfkXOFrrGIE2c1EsoqmZaDn4UXGFcM2vbc7hVVsPq/ayFuqgs9BTDM8emu+lfRj0YjCdyB39r0208qkZojcTWSYtfGgV93yu6eJyPzvy8rD51f5IegXS7404dsAWpKbj9gtuogwT5baMrvaMZOxwiVhaGVvwmUxaB51AKis3tiXuEAIQV85STkAFj7kqf3JO4gK5SWNpukU5lAuEl4Hoq7tVhp3rmkIuOeVgyE5sCVh/2cWIyJTIf4x/ThUbE1rl7zyXLjeJvohHWDx9DK/az9GAnSoWTaQjUsBbU1c7Wb6QVPyJSWcfFAVwDsBAPTxmIAbFrHcsSbdUSsdxntEKXQN06grGBVoP01xWi1Hr7R4O6EalSoMhG5ZOkztCSteX48WM6CQ0nbJ9PJZAzgFLjnb/nGGA8dcHwaBiV1HkfvNOztbz42eCXFx8rz7r7wPRBCZfg5VygVrCmkNpchILzooaCSxi2Pdm1rIRi3v395TGnHxvbLhr+OjNjOjO0Kz4wgUU88GMV1elfmuCUmQRKI40HZQdcVkj38K5ghp2nTnLkSvyl/XlXWNblL/rJbHhIdW4/htT2dC8ErfGLYRjFeLnoJZ8NjMuB4XzCjmmy5RHi6MCWvgSfmjZLdojv+NS6cu3LOp52bbnpUMGrESVrki5ru3reYmeNwltmuVJIIy8qsOuprS4wKJE2R8DeuJtEn6STV0uJeAKZ6AZ4lbj8Eh4Bz/sh6RAento+nFvVNtsBEL0XRaJGgAFJrw4JKO/IVhNg0cLs12C4bi4yguqxeKHyinl/yk1yXY5EdZSklem1m4HC5Z8z//REuKfAGs5TmJlKPXU/YoILbBQ6HopGITcPgs3gdO0Yj0vdg+xwireOhcQoTV7um+7YID+0pkqkxmrPi6VXWhYHwrdTQ=,iv:bNHWboGnl8oDt8q9BRz6lG0BK5kckCwZd9XuVs0WtpE=,tag:xlMovxQapfN43F6Hce/Pxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aml5V0JBbzFiZHdTUllz
            OEU5OWljRVZxU3BlbDQzME5oNDROdlJiUTFzClhuUEZmb25KWXlUZXZxRy9VL1Jj
            ZlkrRll1SkhLemNMOXkvTmxnWTRVZE0KLS0tIEN6MVRNTytzd29iM3pObVBZQnhh
            c3g1UUthb3Rqc2RJd1VQc0VvS0dtaUkKkFzs+zhRLg9gKq//uXF6u9r3N/BKjI6X
            svV6hDvcpBOrCwRJgVHDv/wbJNsjTgk2hPod6c4iZZpd8GD69W8WRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:51:08Z"
    mac: ENC[AES256_GCM,data:BgE6Et/xrmCjuIcnzsjVwPVjdE3sWYPofqummd2hbzwlN3TXWm62ab4mr7UbAun7m83ksIACKA2aEulBNIsH3DTkXBRjUaH1J0mPM0pIQahxAyFQs/93ABrOoORz579RIhLMtZwDtka5XYXaZ6TSCGMMgeoozmhE7zdNGvaU4uw=,iv:r0qErCxWnxsS+j9AI27HQGWG4IukJBzSyXIR9gRBCbI=,tag:Hk9dwV0wvIGdv8XOIRlgOg==,type:str]
    version: 3.11.0
