apiVersion: v1
kind: Secret
metadata:
    name: monitoring-alertmanager
    namespace: infra
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:hvYFtJA75nw+4B9SAAf7lcOi/s6Q7wOuTFlJ0iBST4dL0ix9RLuq+7ktWmajDuWnZC+swh9OkxM+3QO3gqHhHGlUokwt8Y3XTHqURkzgKA9Czz2fCe2lxc3INwMnqvIGstxKVM8xoiO8vgvygBoD2DXJ/8tKPlJMsIZtgc+YSfb6M7iXy9o+fFNhd5HMOdDLQSRgjM7BtwPIflhoLJyn7B+Q2nCJVvwKoEu7JCirzbmKm39ta603z0sViUUr3lRZPMRZ+F7wdeSVogIGS0UiefYTn0dpxBfiEzCPhEwiUpWnv4lkVxjZzf/QDtShvU0JmCf/GY0vgvHMw78wFKzKX+PkUtOl995gtO0Mm8ImidBNMAOD10INfjuXMZYu+gzA4e4LjFBm/mR9UdDNg58T6ezk1cMZswu30CZwtcudZ++6GvRibPmfhVcOB3f8Ee5/8111l4sOgLXsAtGDY0iW2dGZmFAHPlWA/KwJkbEioCw4ctxgkJ8VkjmyxqPbTmxYSt7d8f51UfflnaHNkd1XWH1gCpfaGgGqeoe1S5gYNmN4jxLUa0+2XFjWMdQwvbPsa/xZWz5jjWAOzxE+jjjJETlm3oJSrUstD1BKKxU2k6Kqiamcj8Xc/D6HxO/lCs+nQzYtouH2EluRUaHjbP/oA5Pwtp8KxN9ZbstQWwpoWjw47bmvBE8inU1mVJk9fMU/UfnB,iv:KOmk5ifmDB8ouORep97aM6Klkcc3tvHlKBJ+MRn1q4s=,tag:RY+L8+r+ZOhpFFOrjnEj0w==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L2dnYkI4cnpRN0hvS2NR
            MWl0NmlFcHRsaTMrL0UvalFta0NHaEpWVkhFCkNnb2xJRkViNnpJOHJNUnlNdU9v
            cEV3VEsycFlRejZ1RWkvRUJaYjI3b00KLS0tIEZvUmhqRVFUZ2l2TkdhZUFxcGFv
            K2dEQXFiQ2hCTjg4TVBBTVJ6SUt0VlkK3Fg+gmGmJeQkhFRblDm4Z0S29LqBSNLW
            xbAPcF4LRJJZtwLX2ksqXz1tpSav2CLOiivAoeQAfCV5MksGnSXybw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T01:08:47Z"
    mac: ENC[AES256_GCM,data:F9fcnckKD6xv135yaQCMGrKUq+1Y0aynvPT5QcmT6UzKpQQiwfW7Osw6J+PEUfvfm8yUQ17h73QKOVQG6U08y5/9lKcZ0qVmWA+JjwsGGFCJRZOP+6YfsLVZEdi1MR5Ge63RfpXST8nduIrkmajAMRdN8YSUXkrgcf1neWmzjT8=,iv:PJZETUuDBezZVTkvsJqE7T+pNR1TavBlRXViESQEoyY=,tag:6o2gjs6mD+jY8uKfluTbVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
