apiVersion: v1
kind: Secret
metadata:
    name: monitoring-grafana
    namespace: infra
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TlxHC5I=,iv:p4Thl9ApsPFM/Z7Ocsy2C3a9enjxJKGM06dXLLAMN7Y=,tag:lughSeWJbvMfFg/SgjG2IA==,type:str]
    admin-password: ENC[AES256_GCM,data:NGPMr8QB/1fpofuWHdm1uqfyfM9b64YRhGJc5+MNHtl2+f1/6b0jn+CvYk0=,iv:SxO+kmqd/T9bhj1cfP2GHtcyRH/OK0x3vCbEEf+dwXI=,tag:L7tUaP9IjQQV2ZYk1NkXSg==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUE2eGxzMW5kT08xRTho
            VXJNZlRpcEFoL051NlZ6YWZ3eG9PV0NwSkhJClU4V2lZVnJZWWt5ajlxZWFEcWVu
            NjNhbUkwaXV2UGpUOWJvZEVsWCtqSWMKLS0tIFdOTHpDZytiSFJPSCtnSGtldG5t
            NGZCTXg4OHZ0U3o3V3Rja2t5MFY5QlEKOsQAnQUxhTBVxrU04+3NwDs2RxXadaKA
            KY/2hmC11HUyrF8pBdjWi42PCOUJrn0suFeUN4q2p+/cpl+6VWtK9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T09:28:25Z"
    mac: ENC[AES256_GCM,data:WuABNBZHko+mhHfWowcI+1OXUvHcFBGlX4h57d9Pmbf0Ck6UMWVP6jvHxKbsNOfng9cpPp7jou3cL6tGDojs31aQE2owzSMT0Oq1uhY11F0dQmuVo/OcFYVubhMSq3+oqHGz7CbY1atcqZj3qOLA6KvjHDOicY9KcP3FKglb71E=,iv:Gxzgrb+kzMjeUcW7KZaKVv759t5qizlhYtRQ0ywXUHM=,tag:VD/3z+9Z4Fxp6pWk8aUCcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
