apiVersion: v1
kind: Secret
metadata:
    name: monitoring-grafana
    namespace: infra
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TlxHC5I=,iv:p4Thl9ApsPFM/Z7Ocsy2C3a9enjxJKGM06dXLLAMN7Y=,tag:lughSeWJbvMfFg/SgjG2IA==,type:str]
    admin-password: ENC[AES256_GCM,data:NGPMr8QB/1fpofuWHdm1uqfyfM9b64YRhGJc5+MNHtl2+f1/6b0jn+CvYk0=,iv:SxO+kmqd/T9bhj1cfP2GHtcyRH/OK0x3vCbEEf+dwXI=,tag:L7tUaP9IjQQV2ZYk1NkXSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV2ZIdjFuc0QwaTBSRjVO
            ZmxONEJqUGZNekNhVFRXQSt2REVoRHpjYmk4CkJRWTVDLzQraTBUVEF1ajF5OUty
            dTBmdXBTdks5QWRBOU5GeHJERXZaa28KLS0tIHZ2ZnZYSDkrcnJ6S1pBNHViQjNM
            bE9Zb0JPNW9ud25NWm91dGhCdUY3T2cKHe73lQbfbTbSzXjXRBz9L693r4YN1TLP
            wZFNgG/R76dJ0I/ViUkze258+mHpsgygTiH4EHTp41SlPSLqyA3X+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-26T09:28:25Z"
    mac: ENC[AES256_GCM,data:WuABNBZHko+mhHfWowcI+1OXUvHcFBGlX4h57d9Pmbf0Ck6UMWVP6jvHxKbsNOfng9cpPp7jou3cL6tGDojs31aQE2owzSMT0Oq1uhY11F0dQmuVo/OcFYVubhMSq3+oqHGz7CbY1atcqZj3qOLA6KvjHDOicY9KcP3FKglb71E=,iv:Gxzgrb+kzMjeUcW7KZaKVv759t5qizlhYtRQ0ywXUHM=,tag:VD/3z+9Z4Fxp6pWk8aUCcA==,type:str]
    version: 3.11.0
