apiVersion: v1
kind: Secret
metadata:
    name: traefik-home-forward-auth-outpost-api
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_HOST: ENC[AES256_GCM,data:STQvomarBu7FYLvyiDGG57TZefjV4cV7,iv:mZT1h4R0GdB//Fg34gkKUxv8MhmCy0o9B5nQddDlmJU=,tag:NyfBoovJwq6Vb6b9y/NQEQ==,type:str]
    AUTHENTIK_INSECURE: ENC[AES256_GCM,data:ZTH9LgM=,iv:GC9YBHrV5F2ATp6IsC0IyPjD7kuyKE6myyV92blFW3U=,tag:LyTDV6BENytkeS0VuRzOxA==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:gVsQj0r/DNc4a7ZkIoAVZj7PuW2O2erEYZA1a2RXD38/steiE8ROyidVVDSwz33ireBxDqp0jOyC75TG,iv:1IE3AHsOvhTniKtnLgZjAha2YW8+yapv7Pb6ipt2Y7E=,tag:Nd8/MqUmXu+XigpQAHYbWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT3hHOXprL0tZbFFyVkV1
            WDlYQUpUUTdrOWlFQmsvYms3anFSenVlTUFRCm4yMS9qaWRyc0lsL3NwSUN1UmF0
            aHZNUXpBclk0RkUxZE1LK2tZQ1ExdjAKLS0tIExyYzJyQmd4elVWRzRHT0JDcFgw
            OHczYzNpK3ZrcmlUSnpvR0N5OWFBTlUKo3+cYmJ7RxMHQ72X/+8s8QaSP9nmdiGs
            fyityu7pkdEJ2Fzf6GBNJsrjkPdE5MY45vCy0zbusboUsib4Vg6Zhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T15:10:01Z"
    mac: ENC[AES256_GCM,data:CkGxToKwjfozSjAmkg2fO/qX1QRXDsp6oY2K0y/KJGWVf0jWVXIohQXb1GjFR1Q8qmACXhkU/lRBvZO8UnqZNk6uskZPGhVuexBSPAiMDvbmqu/9Xnjgwh1VGho9OCZuF871zaJCSmBoSdht/S8z0Y42cQvm/2SRbTP2+4lKXEw=,iv:uFtAQv9g/aS+0aX0n3zO229EbL58qvpWHmZoM4Z0/kE=,tag:tHoll0Rj5pBfxYEk998Qag==,type:str]
    version: 3.13.1
