apiVersion: v1
kind: Secret
metadata:
    name: traefik-home-forward-auth-outpost-api
    namespace: authentik
type: Opaque
stringData:
    authentik_host: ENC[AES256_GCM,data:Dy8ZFdin4Mv4cJCrGL8I9u3xR7U0O7M8,iv:rIpDhOroZjNiLvFPn/3Y6+YycwW4BF1zYkR7ypgPITc=,tag:gf4qkqF8QFZE20GMpKfGNA==,type:str]
    authentik_host_browser: ENC[AES256_GCM,data:8GY3oRkOWJiNyXp4VRxZ0s97pZtncS2I,iv:cns9ldOHhDbualq9AD0WwjZpgcn4tdIthOdocLm+9Vw=,tag:V43Jf5y9VGBhQ7AEyQa93Q==,type:str]
    authentik_host_insecure: ENC[AES256_GCM,data:9jzx1dw=,iv:Fgsx3X6/51vL8FP5xmKPGsEC9k3PV59b5wDlT81cJ58=,tag:RafJ9Uyd2wS66exI5g1nnA==,type:str]
    token: ENC[AES256_GCM,data:VwbHp7loW1OOvYZ/r2483jbwK8Ox+uunn6Y54aR+m+7lPycBVahqiVGF3OGfDMUuSqopCcvlnTSGJCKh,iv:NFQ4n0iDEU8zOQQm3vH/X3GsWyfitF+KnBQHPlPlrr0=,tag:LFgYZxpauQgnMcHwwcQ6tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWHE0MTZIZk5sdnE1MnAz
            MzJvWkcyempjOHpXOFZ4aXhxdXJCNC9aeXpjCkZXMEsrTkI4TCtpSk1KbTdnUVk2
            TEJ0VDM3aExaMGhWaW5pOXUxSmFZRFUKLS0tIEFxWUl0QkgxUFVDN2h2WnZ2ZVZW
            dW9IVU5qVlpPWDkrUVljRERFcy9FSXMKxLpyBTo/5pIHJUg4G8lYhDLhABtRokAh
            D9KXSzkYT8rUWoCi/5dz/Xglxz3DK4YtgwqdT+JiYU5PK2co6tc3Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T15:48:19Z"
    mac: ENC[AES256_GCM,data:A0yX7qZi8vy3HXirZ9zpfUhgCy7bkv3kS2AbiKx2CeiStCM+4riCazLSRhigZHaDEOHTCc1LzPvQLqQ5KWBP2Ve53WcwIHLJ5Nt1wg/lxCFNIpWhGQrtkFTZ9vdSFhdeJ1VshTqsbRroJEVRtz9bLenoEqvhbvD3g+jS0SVMYzQ=,iv:VlVPxU7Gq25xI1jIyosT40zwPhfXg2/nd+imOPJ47bM=,tag:1B2cScjGK51c0+YySQlNxw==,type:str]
    version: 3.13.1
