apiVersion: v1
kind: Secret
metadata:
    name: traefik-home-forward-auth-outpost-api
    namespace: authentik
type: Opaque
stringData:
    authentik_host: ENC[AES256_GCM,data:ZGWhqXqNeyqU7F+npXst4jKie8mU8K29,iv:kGf5CI39SndJUtgsYKndH8tpHyY4vUNco+SRUmLYsqw=,tag:gz9ZphecQMA+enS9tFCHPQ==,type:str]
    authentik_host_browser: ENC[AES256_GCM,data:AZ1wQBI2u204dWOAWHbWRQem8jYJs2Mx,iv:IWFP69rTtSrrY9GmcEPCrMdnr5FeufD2CO3avF+SduI=,tag:PrF4A/zcM6022zHXEItcrQ==,type:str]
    authentik_host_insecure: ENC[AES256_GCM,data:h/9zRQU=,iv:ltuPuo/Wnim+iUDNCp1YwbHH/0pJCwQsVvdlR1xFF+s=,tag:UxNoKgGnJ7e5KFM1oPONBw==,type:str]
    token: ENC[AES256_GCM,data:VwvPQUGQXylmiNT5hNvr1bvDR1ouNDb1VvVRekLg15bqzM6hKFtbRmIZgV8LhtmCMoRB9VJjLSPI54fA,iv:hA+s1HeYGVGkI1c3D0xiCMSSXkyedP77VZJQdfjLkXY=,tag:LpUgjeZRxQLX2/sdgU2QPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRmQzN3l5QTVpNytDbjVB
            ZTBuZjIvaldSY21kWTk0ejZrdkM2OVNEUTM4CkF4NFhrTXo3cmRNMDlyRmhXZzVx
            SzFUdW1FK2NZYzVzTHlxOGR5bFhXVHcKLS0tIGcraGdlQzBUc1czTGIxZUtBVHE5
            YXRtdk45alhFRE5BN2h3MHc4RFU5WUUKnmrgctQqC+cENlmKRqhRg2bdwPc7JaNK
            5ljMydJf/gMGp6ZX8ik6pm8sGwPtB5/zsy/dXafXsiVG9CHdDKU2tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T15:13:16Z"
    mac: ENC[AES256_GCM,data:kvdb/hmKLQpmtLrH1HOeiJ/pUMmv+vQOKtkUUVn82BohKBb9l81QNYo5Ukx2f34UiS5WxVFqo4RJnXgCpORV95kOyixN5gWsEsk8hzOonxASpkaRQNhq1XgIO6D81O9ihzpdj7VaC/D04GifsTYwLIhUZp+HjIh8JP7pP5I4nhw=,iv:sRwznwo21wkAtxVVTu5nK6N7L5dIlXujx/LzB3O4SbA=,tag:pPG2b8QQ+ousypdtUULMiw==,type:str]
    version: 3.13.1
