apiVersion: v1
kind: Secret
metadata:
    name: kaptl-bot-secrets
    namespace: kaptl
stringData:
    telegram-bot-token: ENC[AES256_GCM,data:I43zIMtRDsqqA8P5E5VUleaXSziEKtQW6FXtBUUnG0Mr+d9gCTAXLN1EEb/wwA==,iv:eRgNa0ND3/RUNQU1WKMuTf9WgvU5kPLRoLBp/OH1+s0=,tag:Web9vti8wJRHigkbN2mREg==,type:str]
    allowed-telegram-id: ENC[AES256_GCM,data:yl3ABoTWA0FQ,iv:zr5rFvvQRJBmwgQ6t0Lsm2GwnEHOy5QD+4Xx/pEIgpc=,tag:O6ewN2Cy/yk5gHFClcnbJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdU5WQVpHT0szaDYxbTI5
            U1dtcERmSzJta20wR0pMc29WaWVMbHVIVTBzClFyY2MrNkhuQ2JURk93eVZUM295
            ekxrSmhRTjdwSmF0ZjFYUXBiWWZ5VGMKLS0tIFBsbEkwMDdOajR5bW85WklrZ1R5
            NzlOc0xTbkdmd0RMOVNFWFRZRjh1Y28KszRyvpOy5BBN7T9SiS/EqPtY0dtW3Jkf
            kvrogxhk0ks13r+zifieJonpdrATIPHi1oSliaNfWQI5KDJAK400wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T14:59:08Z"
    mac: ENC[AES256_GCM,data:nlfcCccyzqTqXlDn1TSGxkpdKeXUx7jPA27fmz3yXstJ735wQzJ3WWc7UpoGB+lwY7mv8VFB2MCEICTh1nn/AT6dRtE13NxiO2RAL1i44vIGFVayAjo5gpaffefoiWxeJZU32WKjqQrNz49Z0U6wapBJnRXqwgUz8GKSBX8oMD8=,iv:Sz3ZSIsUz9XciYFuLq6zleQY+r/hIhctamdHteLMRJM=,tag:3YqDKdsu/0BTrkI7YT2QRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
