apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: paperless-snapshot-daily
  namespace: longhorn-system
spec:
  cron: "15 4 * * *"
  task: snapshot
  groups:
    - paperless
  retain: 14
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: nanobot-snapshot-daily
  namespace: longhorn-system
spec:
  cron: "15 6 * * *"
  task: snapshot
  groups:
    - nanobot
  retain: 14
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: glance-snapshot-weekly
  namespace: longhorn-system
spec:
  cron: "45 22 * * 5"
  task: snapshot
  groups:
    - glance
  retain: 4
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: pihole-snapshot-weekly
  namespace: longhorn-system
spec:
  cron: "45 0 * * 6"
  task: snapshot
  groups:
    - pihole
  retain: 4
  concurrency: 1
