apiVersion: v1
kind: Secret
metadata:
    name: executor-secrets
    namespace: executor
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:tflruG4skbI=,iv:GdzexPtRXwzeBGrHcW/pLche1LO75EyT7s0ZPxguzck=,tag:T5SLc/unKB0fVwcHROW7ZQ==,type:str]
    db-password: ENC[AES256_GCM,data:W/pxMDdzmQgaWv4XCBa1iUwbXyKiOVtmbdT6z1TJvtc=,iv:3UdEt01HeVI8EcNKJ/LCNWGUoQ9K4HgbIEEV3dbmViI=,tag:HXznixEIQiBvA7r7UCq6uw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaEZzOTQ4dHoxbTd5T3da
            ZFk2R0lJS2lQWFBuWFdkL1RDQmtXUTBIdUFzClNqMS94NzVGc1FxZ0pWcVRRbkpx
            UUMvY0RKZUtLYmZSZk4zWk1NcHNrcU0KLS0tIGZnQTNWTWFsRWZCWFgyUDBBdjND
            cEhqa3crQngxU1M3R1JpUitWR0Y4QzAKEjJUS0XM+aaF5wrnYZNo1a20mvj45eN0
            +UHyZzSy0XhcNLLkqRUUohIVo7FkoR0orRAq5UFnNH08j302/sZ0mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:07:24Z"
    mac: ENC[AES256_GCM,data:cChg3jrUKx76fkKS97V10ezY7Z3K5EnWD5MNmFWi1ONOOri1GFINudMN4PlGmgL7blnBV2HmpQsHS0QL1hC7Gre1nygi2wwmkeRc4EMuh2jKrF5cS5+lQwttfAUvHZg++lL+L/TdtbEOnMKub+R6X+04mpFrb+s9rJK3McBHKew=,iv:2wdVFCExYyXQFKWvF8w21dJDwnna9xt5ywKw2h6Okog=,tag:JF9vRC8jMl/64OoT7Xmlaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
