apiVersion: v1
kind: Secret
metadata:
    name: executor-secrets
    namespace: executor
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:tflruG4skbI=,iv:GdzexPtRXwzeBGrHcW/pLche1LO75EyT7s0ZPxguzck=,tag:T5SLc/unKB0fVwcHROW7ZQ==,type:str]
    db-password: ENC[AES256_GCM,data:W/pxMDdzmQgaWv4XCBa1iUwbXyKiOVtmbdT6z1TJvtc=,iv:3UdEt01HeVI8EcNKJ/LCNWGUoQ9K4HgbIEEV3dbmViI=,tag:HXznixEIQiBvA7r7UCq6uw==,type:str]
    executor-token: ENC[AES256_GCM,data:TCVrbYfF4usWSgvyLU4ykcenAGTMXcrvMCS3J5scru+4Vr7LUkOXMaBpFA==,iv:txBRUHKIAzDYEsmzlzIT2Tl5gamIiPZyPxGGnqwW60Y=,tag:HL0CmxDWsIrjy6+RsxTQbQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaEZzOTQ4dHoxbTd5T3da
            ZFk2R0lJS2lQWFBuWFdkL1RDQmtXUTBIdUFzClNqMS94NzVGc1FxZ0pWcVRRbkpx
            UUMvY0RKZUtLYmZSZk4zWk1NcHNrcU0KLS0tIGZnQTNWTWFsRWZCWFgyUDBBdjND
            cEhqa3crQngxU1M3R1JpUitWR0Y4QzAKEjJUS0XM+aaF5wrnYZNo1a20mvj45eN0
            +UHyZzSy0XhcNLLkqRUUohIVo7FkoR0orRAq5UFnNH08j302/sZ0mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:48:50Z"
    mac: ENC[AES256_GCM,data:fQU4+YDp26xZdJGb6q0BeWygz7YtAorWZHtu3baidd2jMbdD1Ojos6SkqV3aviDsMJ7eaYdDeJGmvh7SJRDMXkIHoyGtw0hNVkEEDMrGNA7uiVkO+nGrk8W+u557/RSkG8WEkhICM518d3MQp3eDsiE81gc73bHPS4UpwvRUCPg=,iv:hc7NM9KvMVBQJfnmn3KhbPNywYQ5h4c2bC5tWg1JSLA=,tag:q0sdTJ3ygQa9OoQAFv8Y8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
