apiVersion: v1
kind: Secret
metadata:
    name: executor-db-auth
    namespace: executor
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pYOLd73xXcM=,iv:3FIo6MNQXMFABDNDn2U+9VYSOuOmPqu2BemCOaBn9t8=,tag:avmWG+dQKQV57BUVn4fuiA==,type:str]
    password: ENC[AES256_GCM,data:L6a204Y+osobMoSYAbEou5DXcCnauaNkUSyDtod+FBE=,iv:AQX1xoDnI2P9ul015C4B8hL3LIvgZCc9C7Vy853mjmM=,tag:/LEXBmu1q12PCdLLp7N32g==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFZlL0ZoZDFHcnhaclhh
            dHovY1krYURHT2RvRERyL1dFQkFkZ0pUaUZjCm9zRStSaU1jLzNLZ0h0Qi83VXpz
            ZVV5MUNOeHNld2dsZUpUV0tyY01uaEkKLS0tIDdoU2pSWWlYNm5Da1ZVYmkybmRU
            UnowZEFIaCtnWTdHemUvVEswQk5ldGcKXjiTx5bFqWjzhlNe+llvgTdXJqulY83h
            faI9oLvb6Y/Jir2hwyANSefWDRzwgrgcpRvC48Or1jrXwj2IcUc1ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:12:03Z"
    mac: ENC[AES256_GCM,data:I3wXxy+JhUYNDwkTOZ2VH+hQCp1vZAxIinP3MBK5/NNFpinqnRGSvgY0OBXBdib2o8K04IkXmsT9G//CL1eFI2IYBfx9jLMEFRX1Ld5U+RksmNyIUJu/R49yqLXQe49O/GNDlsEOHX+Fb9FYK8XkIq9vrw4hrvTMzvd/d66thlo=,iv:g7A1i1rS8PtdKfNQxUqcCuXJlVCQAf4Zz2AFM3m0HVw=,tag:sYdvXFaFT3XBZAIm+cFkgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
