apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: nextcloud
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:OyoBESRyCEMFkFuM28JTvwuvxUAlUBUP7Q==,iv:pE+KgR5FOq2aF8I7hy6nii3nbomCJPDrCIOEtsOyNsA=,tag:HfqLo88+MLl25mNmIEA52A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:chYP5r1QlT4hrcXhipYS3CPWyiLBaOrTed2f1ZRfiA==,iv:ipYJ+BffU0XoU2Y5Ao5fmjLYog8Fjtxd5xIYWxCjjDs=,tag:izSPehFmvQ+ei+UmBjagcA==,type:str]
    REGION: ENC[AES256_GCM,data:TlisI+4Wnc5c4emFcrg=,iv:0n15E66SGGojHiB3rWjTgQEF5mQc+MZKKmCHQTvL/Q4=,tag:9Bo8tcJER3pHQ7kmYHwk5g==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:XoWq5zIHKKSOakmGebRZPejmAKsZEhIUNmMS+SlqM0Dkvrx6IlIii1s=,iv:X1Ak53RDzvDQ2rx1PZxLzYtVM7Mkl39yqGTkDg1MP9w=,tag:5XRLsBo8EJdscfhPZI+EdA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdWtEY0ZDMEsycFhtdytq
            WEVKamo0T3MwZlBzWHJuaWoxUnZxZi9BQlJjClBtQVhzQ216V0FDdlUxRnppSGVs
            VERaWko4ZEFzMmlUd1dsK29VT1dQKzQKLS0tIDg5ckxNczVGaUl2WjZCRTQ2REZ4
            SkVWaU9hWDR4Y0pwQVZHM2szaDUwUW8K4xbKQlVTzrcH1bSeStnpe38zCR1ZevDn
            u3YSnRQBnd7R8LbfdJDIOCXj55ImPon/WhtbtjucBHhUsRCvhqWjIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:33:36Z"
    mac: ENC[AES256_GCM,data:z8nX+glfgPKNJiTsPiQlfDoK7mYvmpH96ABVnGtRkzUGNrlZQAE0REJgiGtVoEid91Rn/Imu3OZI96AdS8NxbwdgWfmsQ00j0ih1EFrPfhYGmpCQm9ryW5gGlr491k/tlilK5CEGL/b96Dtz9BORcvnbSiiNQ0u1PdwsvYFADQI=,iv:3lToeVvqSyBINBDjvPtzDtLURgMP1hikwZJb0QPNt1Y=,tag:6TMh/TvZx++0Pfzb8rm+xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
