apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6SKOFCwLiaiM,iv:ambZiq1m/PCT2cvXNP9FhjPyVoiYQ4DfYgeli9zfJbk=,tag:gntm/Utt1+bVtDcuO91zDw==,type:str]
    password: ENC[AES256_GCM,data:Rx/quLUCx90gW+T5lcAA++iIAt/cO4J0,iv:OGzafUKRjxeKxlxipvXluGFTqXk8tj6VJxhFPsd1ty0=,tag:W+FHWNofhzGZEAuWiqmr/A==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV2Q3MlFVbW1lNkhURU9K
            eUprKzhLQ213Z1NZUWNsbTJ6SHNZcUczNXljCnZMT05EK1h1eE5rVW01VjZMWlFF
            NW4zU2x6ak4rc3lyRm9xT3BxUElrMlUKLS0tIFU1SGVsbmFlSktGbDVnNGZpcExl
            dXBGWXdsak9IdytqV3lzTldsM2I1STAKkEb2jk6Cxt4ou/a7fKTMRz33BtfA8k4E
            wh9CxXZ6ddZg7CFz12kaaD4iB8BFbLgqohXKm2XyaxSCx3QslfVAnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:48:14Z"
    mac: ENC[AES256_GCM,data:sSZPSRDKaTMdUtGaFDG+dnz3jnPNhS59c05QLH4KE1BNOXeS4wX+3wv++jljozhc2cqJ3yOPX2BCaxNJtuVSSPlgcVUeomFHUYlvjj1eOIsxQ+Qudwe0MEY36cMctU7yapEAlnoVkQFeXC/r+OmxC22uH7NbBVissTQE1XqMe4M=,iv:vWXTFadm+QDgk2Jmidl46rkGfm/mAISLESVFTFUurt8=,tag:+OaUPin1Ch+y4+CtbpOoSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
