apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-redis-auth
    namespace: nextcloud
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8B7Dvx3TCEPDiI9j/3pc11VikKHxGbwt,iv:4tBGOuDybzFk1ZcwzIkXC3BuPy0ZA4yLMAvgbXMZs1g=,tag:YfzBpXpYnuU09Ji3H0AFOw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcTFid0JMMVpMWG1ZOGlF
            STVYWlg4TUFVVElYVUJuWUJuelA4cHgzT3cwCnBXR29xTnFLOHVUTXFkS0FLU0Nx
            VFlrRG0xKzFwTDRMVmk5VzFpZHNKR3MKLS0tIFZtQkFlamw3cTNEbFBZWDRPbCt4
            RjFJM2g5S1lRYUhybHN4eG5icXMwbmcKZT2VPYZiDrsDvJpC7jRztS06NeOqtHgi
            spQYY/4CZrJUhZ/sSnruYfUqzpGYJwfaHZUTxF10E9uXb30ODvWfGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:48:14Z"
    mac: ENC[AES256_GCM,data:5nO6fo6mBTxjGyxzys4OewxMmReq8oVTM1dc/jFYMjSKHiKaSIrTBRs29SDJIz18j8dtaNpv7xEnUG2qtXJCGNT85xyreBXmGr+TUe6g6l3+8cxCJxgPJI5pUE45HeDkqF2EiNLS6mPqTbH92O8JRC56zXz0PXyxy9LyCAHiqwc=,iv:G1mVNFlCDsajvGzzPzIviUgx0xmGTZKz0PkN8lQSPuo=,tag:0emaLinPOvgv86jsDJzX0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
