apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-env
    namespace: ai
type: Opaque
stringData:
    OPENCODE_API_KEY: ENC[AES256_GCM,data:CXngYhwUEmKLhiuxhsridi7cjxrUZqYNPBb+EkitsvxEKbJuO1n9CooTO6rT2wpSGXwFDeDD6vtyCmFAM0RYyPiqAQ==,iv:FXS4BOfPUXuU1rdKa5N1/8gb5rsCv5AJmGW2GSvrIVo=,tag:ASurxd5KaqBem2iWdktkyw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:fNViGbVi4uhsfQ1DYAO7KBMxPUWq7OIU9m/kxo2q0xGRWho9x8h8EGcqeAO5rQ==,iv:fAZ9x6WBUWJ/vk9GDW33GynRprFUwUfG1dRGQDX2boE=,tag:/YPw+c5i9vV/pPFhIPwICg==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:KQ+89uCjTxFs,iv:peTT+DSDl4ozC98H3MxaQB2fgzI4PbsIrQIVw6HKX38=,tag:SlVsjUb6rS3pzsd7L4Rvmw==,type:int]
    GITHUB_TOKEN: ENC[AES256_GCM,data:DD3xKc/fhuK3rMbyA9cri+sEARxw7Mt7aNhJV0SJIT93KSEUUAVMd2bSy64V+gIQ5CYpMY8ImCqtkxZEM0Rm8QQ47d28R2X2WczU1pogIAUDz2HqtGw5JMZBesyp,iv:LOFy2BrP+57C/g+0PY6lDkdB4qvZoOAUiAuGdC7gWR0=,tag:DnN+RUHtQrvBylXDm17bOA==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDdvS1ozMmgwL1UvWUlO
            Um5oT3JKR1Q3bVhXWW40R0gyclNMc2ZqV1d3CmZlVzI3bkdrTTRMUkpxUmlkV0Zs
            cERQUGZSS1RrTTFGeExHK2FYd3VsVWcKLS0tIFR0a1ZJbk5oeHhiM01wTlRtcGhi
            eEdXLzFoTWxXdE9HNVJPN2k0cE5KQlEKji4PX5GCu7KbezWQdk6ZJrwGJG8K9YGh
            PBa2VB9Dfy8+Ki99axwBwy3rionfPXMbQtoj809yXxX3dxQvqa7lcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:43:21Z"
    mac: ENC[AES256_GCM,data:Gy4J1dDWtL8pJIgL3fBrD0uXFrEqDsfG5hpUjB/ERbj8KH+ssmW34qHYjPCVr5TZZzB7zfMRCnH1JJcb3RXGCPGOfV3C7OGwqko2ioBgGplv6R6OKXt72YwE+ryRPBc6ne29sbSY0j+rQt+6nGcoXcLJMTOtjf6KtVoRysdmSDc=,iv:QCuPQ0sWT9/BaiDofO8ZAi+VX7yfaD4khLd/A7LNCZM=,tag:i2W8O1tE6E52d0VtY8telA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
