apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-env
    namespace: ai
type: Opaque
stringData:
    OPENCODE_API_KEY: ENC[AES256_GCM,data:mRUBnFfgv/n3fULqsTWHFrfiRJbFmI4YTdh0j+lUvQK+5yC+UeuZxRDTiHwteIgiF+smxOHp74cKNCDOiVZsaWwqHg==,iv:JjLnnBM5FFalAMkzHC9+bEHWYOEyR4o6o8qIx1Sf+XE=,tag:EFHVUgtP58p20hR7deVY3A==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:zlPu6RvHtLd/JByLYUbHcb49vGVkyyWAga6Z0CV32vzWER+L0mkW+jI1MC1z4g==,iv:Dm0xV5ImKBeEkkbsNhJxf3VBn1kQwxcs4n5h3Ar/MWc=,tag:TUwOYOXkI0fqt/9d0ZdA+w==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:IKtDz+4qakd5,iv:74B11ukkDeATU9IwUYZoC7oxKKsqMxboiMi3Ksm1n/0=,tag:OlWMgVYV3BUSyY6QcoNOow==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:YerPVwVmveNiMNIbWVGmt7zgLOViPWcURPkYsgAu0Dut/akfIHjNPr6gwIIZJMsq7rqx6hTi3d0JNwGhgLONajoXQ2+l6HNEYFiKHXy/e97x+iU9MY7TJncn7mmr,iv:1rqEbsOsXfK4el8+1MWBhBpib6je+nwqF8rDBAmt+Kk=,tag:SZnnzAxoaSk6n/pZmQNQbw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldHpEUEN5eDFKWTJrUStz
            M253RWN6cHpBRzN2WTV5REVabkJOOXlaTzFvCjJlV1NxaVU2dXZRU1R2TE9oM0xL
            WktGNjV3YTJVNUZaNGtrbEdjMVhEakEKLS0tIHVqNTBJLzRZVEFvMVMreWI2ODJQ
            dy9KNHhCSmY0Y2s5ZmVweGJiRjFSUzQKspxsL8BGNVeMQ8uvVEmU+nz52A2NV2Z/
            gLAgkJUgpq6OZ5dkiJNNk8LlVaKroKQnbc6Z4RqcB3zROwetRCEe0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:49:34Z"
    mac: ENC[AES256_GCM,data:QJj3nXf4HCni+0FAjAwWRzkZUfhkgIL7J5jTL1Q7HLlkx96ZGlw+0YJBCrrmwgiPXk846oM+l5Bes5qpS0Kr/NF9BHeF5qClprDAdi5j5DrTQoOL8jG7ADhIo6wmsZWhmjLYkQBQhu10ClIXDnwZiKxSbH/c+MOpqN67c+uRYEg=,iv:3K1CY97R4hlo+GMfo+CkIiG6I7PHhHV/Rc2Ba2zHomw=,tag:jrgV0SOcQlZX2uNEjAPA5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
