apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: ai
type: Opaque
stringData:
    openrouter-api-key: ENC[AES256_GCM,data:lnjTgpAi0WWhYwROw1lDBr6sKFytuuyJ37wsDsP//irW8ev7QZp2JBAp3xU2hWiLA1WmQxKizZ8R+YjuQwDrirE3xv4pJ4aujg==,iv:wMF/c/0uBwA+QEd7CPPfhbTVQetwxjmiR1+7v/fCA2A=,tag:RvgVu7h5js1YalC2ZPTDBg==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:ZU95Er8TjKFs+945BfgUxX1HAyhEWmbjtg4uDpc0eDCCKEI54ORhVfRIRNXRhw==,iv:uoXWHtiGXvoFrD1ZYRJQW1HSDYzIaxldCpvQIAUd7WU=,tag:+e0hVlsmrHWpFnFsc9IzGQ==,type:str]
    telegram-allowed-users: ENC[AES256_GCM,data:z/W+E+/Hkq3g,iv:Ro+BGVfEAxiNrAnXABHcbcWMxcmhE5uxHOJTPDc3Rb0=,tag:8MUL6yTF1mta6ux3fz8bng==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVblpubjdtcndGSlZ0ZFJi
            NGtXOGxvZlh4WVZwTitCdDRaR3NJQ245eWhBCjhCR05xSGl0OVY1a2FzVVFjMERl
            K1Z1bWRaaHpZOHN2Rmc1NXVnTzNIZTAKLS0tIEtiWVpLT1NLWE5CbUZ2azlpR1hs
            eXZRSkY4bjFjcTA0M1YyQTFvRUJsUTgK3OD7GDmasyYAbo9biyG/6nJDKC04bZKi
            /gOSBDGKT9NyOu8/jlHeRLax2QeirjTzo2bp7vt6MVjOfKPl9M8zJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:30:52Z"
    mac: ENC[AES256_GCM,data:MiHWcDOgtpxcmBSNX9ofgqJIBN9JLyQ09Bw3SsHvnGvRz+4yiIqRQ+YuLyilsFCZujzDSuCkHq/H/dUoJGoSZdbjTAmkrKhUzI8Y073NAQL1/Lou2HPhgQRLEiiFwQjSgkleQNo4oS80ysj7ZWjPsAIRVLrOYGtPrlGNpglto1w=,iv:pROSgmSApT8Ci7YVfLtfSbFEwjNjRN8uwNRlZEaGsFU=,tag:z0S3JHoVV0B2oEqfRnWOug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
