apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: ai
type: Opaque
stringData:
    openrouter-api-key: ENC[AES256_GCM,data:cqfjgs4KSMAjPDH43wV3D4a9iCx5vGQ91nRxuhqyqXjrPnHa8IVWnfmNgTT71VqXi5lQQmOwgLqaaukYdstaAMIhvBXSa7FwVA==,iv:tOrDKS0Tpm+WY9VbrVLLjxXTHHBOdS/mh+MRPmE2e9o=,tag:tXVl7QmkMr51aY0Bz6rE5w==,type:str]
    telegram-bot-token: ENC[AES256_GCM,data:GWrl7SVUpXNZoBlpftAjuLjtzwAjmN6P+jbh2GZj68JJrgUDvRDf4p3jnMevNQ==,iv:56OQOequqY5uI9hBu/+S3aOxsg9Sf6GHFCErx8nWPSc=,tag:8FhGqZbnsgIiNmWOUI6sbw==,type:str]
    telegram-allowed-id: ENC[AES256_GCM,data:5yfKVe6fdM4V,iv:dMerWXTPZGz9Wu4G7AcZ0kQJvu+R3Q8gSC/6gtM7Tww=,tag:NhULGUeg0u7Y9ZEGpqTolg==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTXVEekVyZ2grZWxrS0hP
            ZFJkMllyeTB6UThEWkkxY1pkVXRJaHFCcWtvCi9ENnFFMno3VTZVbVM4SW1UL21i
            UDR5NGNnV2ZIcVc4TkN2YSswMFVpdHcKLS0tIGRjYktNZjB4MmRzT3pUaGlFaE9B
            SUd2dkVWTUllU0ExK0hsTTFBZXl6WmsKAwYwuEh0nz7QxrOSeIcJXiL3Z3TDz+J9
            jLGtFx9Jsd4z+Py5Ynbaf0lgsXh6g5x5IB/eGgxhC3TU4SSYBMKICw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:50:46Z"
    mac: ENC[AES256_GCM,data:rR62Sprs0Ey0IA9+LZeOZJF2Q/rUy1IBzTw3wiOaP/TnnmtP5NM3+zjR5cgiScKVkVjeAATa0sCnMdiPut7ahMIvAXUcGd9mAlpWvbSTXCyabvIXWt4QIAhr4lX0ykhSkeoq4pUBdhahKC7Cv+4FNi4Iv443adoYvCMQaYQhbJ8=,iv:njyFNZ+Ppz/b8/E3cwyGh1NJij+kC+0jeq5Tqg4h5Sw=,tag:XDcecWxnCWSbxwPK5wDPUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
