apiVersion: v1
kind: Secret
metadata:
    name: pocketbase-admin
    namespace: pocketbase
type: Opaque
stringData:
    admin-email: ENC[AES256_GCM,data:euzcaJHTo4s15EKDwBw8Y0tP9AstZg==,iv:GOQ2+0AQA66d6YGSAJcdNrNMEt9B17deKHkxSWruM8E=,tag:ZZuglK/BQ7b1REoUzU0/+w==,type:str]
    admin-password: ENC[AES256_GCM,data:3ySLE8d/riDMXTWs9EPkndjJVzBwiW1UBI7sLZq5P2c=,iv:U6dCibOsqoWZx5ESOnMHnuelc5rPov8PFgq+rM/0W2E=,tag:IWmMOMTGzYVmTmHC5ZGttg==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb2djdVVMMmUvUGQ0VUZj
            bGpPNWRJOEZ2WmJid2lyVmUwZ25ManZpT21VCjZPaXBTM3QwcVo1dFNaY29MbGts
            WUNJZEhNaG9IVkk4MXRCTmZjM3JnNmcKLS0tIEFSdk9ESVBsdklKZUJ1S0lvZC96
            WUJwUmt1WGwvUE9ienMxaGNNUzlHT0EKxKjpv+d37ul+PJeb2V2GOnZ4tq+GSUd0
            QVSk5OaS8d2aiKvPw3siNTD61GcbetRWdBY42+RKP5njrVEOvcfN5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T11:12:14Z"
    mac: ENC[AES256_GCM,data:u18jj0JyJrKuIw/LItccJ+1PncqBnDVsUlPNH9Pppm6x7l+txlAnMTb7mZzdbCakQU6ZENaR+Tt1VQUzyZ1bUd3n6x2sCq6dQOD7J2WgBEmlg2qFZ4R3fPRGBjTxMUBoT/HJlNSKmPezRUhK2SXPZNAziTr2khDtuRKsekn8r4w=,iv:5pk77+XxABLd6XR3UFIlnb4TAWdi0WsiQzh2GeED/Mc=,tag:0nYDobThCGE1wioLUatfNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
