apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:rjwxFoCZIOgY8crOrGUzbF45qOn8IfCUDmIxjAAi3MV9okU6GNfh0w==,iv:eK5KOi5GM2cDaG/Mbbt/O4MvYRg+ZrkPlNdcJq0rDsY=,tag:PY+Ba/R7c10akeFqFWCWgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzg1WlNJd2ZEdGVVU2RZ
            amFqWGQwZHpQbE1UYWJ6N2tRSFJpQ3NBTGtNCkpOb0QvdUREUUVWRFpqSUtXZytn
            RkpPQk1vWXdBUjNjZTBIMWFaejYvMG8KLS0tIFp0bk5zMmNrcVg0Qm12TkFxSDJW
            VkFQSlllNDU0V0pIcndmb3VkZWw2Mk0KWwwpzz56q03LD4Sr0vwU9hgVSQzo1v4C
            n1tJG0p/GZ3bvhbq47rpm4VDWHZGRwQYgvzn1vdINW0D4IT63colpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T10:10:17Z"
    mac: ENC[AES256_GCM,data:n9S3zZmiwDFgRdnjqhOE/B3QvSjUJuKw1f8CC9DJ6fYMkGyX6quG6GzYvJXmpJeismjpMuF8EJx3VJvVW5lJ07rNtdrVkr9GnbjdinAWlIVjqLrR0zxgomRHVvz0Dk+ePrJBR+zBvXPKuGVj6mWM+dARNHpZiAsWo15DYjZG0NY=,iv:wDCotxbJe1wOJHjr0cseMxKBGdQZPDPmVGiQaUQBCt8=,tag:tWn++mO5XpzlK2zNGYkWUg==,type:str]
    version: 3.13.1
