apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:40dxu4kXp2D8f/j3ovreW3atTtCbXCPOJyKJ9BtGRpvyYEGUSeslrMfuWJDPHaWpFyJDWWE=,iv:obpvVbABEHXMuWj6ZFYw3ThMaoxFiEvK3UQNSWL/YKE=,tag:64ls+aW6SL1sCX8hpWTr4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzg1WlNJd2ZEdGVVU2RZ
            amFqWGQwZHpQbE1UYWJ6N2tRSFJpQ3NBTGtNCkpOb0QvdUREUUVWRFpqSUtXZytn
            RkpPQk1vWXdBUjNjZTBIMWFaejYvMG8KLS0tIFp0bk5zMmNrcVg0Qm12TkFxSDJW
            VkFQSlllNDU0V0pIcndmb3VkZWw2Mk0KWwwpzz56q03LD4Sr0vwU9hgVSQzo1v4C
            n1tJG0p/GZ3bvhbq47rpm4VDWHZGRwQYgvzn1vdINW0D4IT63colpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T17:30:23Z"
    mac: ENC[AES256_GCM,data:+8/bafxxSYDiftspsfn4ClEiN20d56d28zbYXLugci67GLfJ/+B6hoOoA5fFAIlVsYm7NNmRkrFq004yoPojVfsHRpgkZGVyn/csyEa/wvt4IMUV3SKwn/ueDjFRIG9JsuZvie+WA79qgHLP0MnKT15DEAQ1MEAbmQ5wgVQX0ZM=,iv:CPT3BewNYzNGPQMUS0nGEj6+iaTvqaFXr5Z9NIWabcQ=,tag:LWEtjobKsq32hRb6ylAbkw==,type:str]
    version: 3.13.1
