apiVersion: v1
kind: Secret
metadata:
    name: slskd-wireguard
    namespace: transmission
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:d7hOJUMn2iGY18Oo2nULlbG7i6V3QlgaAiMY1CNCqlHdtQw0IAhZzjigZYk=,iv:0DcgMGMwkMYD3Uk25NPwKB0ekpkNznBgWbA3CtAG2AU=,tag:3iQ6enwd6EcabQa9kjkx0w==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:bDkunyKFcKYh1PjtQb0QXQ==,iv:m5dse9W+pfLZYugfFd5McrN2zohaapi4LP0kq/etxVA=,tag:3tPluNdz/3pQCnTDTWCM/A==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:Kn38kHyvR7VbsgSbyGGwUa9ZKwLedZ4TEzHW+4kZ3m5G50qsK7sfwEo7fJI=,iv:ch8sc9/ufSfrTXXl2zMn2kT/7UMXYV4rCIH4IvRZwi8=,tag:BYLW2jcj7VZ/vKH7GLf/9g==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:RlmmNYzjIG0S8+gMPQ==,iv:KTmn3Cay+JEEHelBd+DC90hu5sXvgR2BoMfot+mlPwU=,tag:J864K1nOtlVk2tclHySR/Q==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:SK+cKr4=,iv:lgPlWXaNHmssMdLnS/o2MhFErcD8yLnGGdoTFgOteqA=,tag:3pZHA+G7Abi8/NH8Ek8F+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVk43QkJJbDRpOXoxRnd1
            eXBLRUxlQXlvVCswSnE4SVBLdmhndExlbTNFCndpSEl0S1NyOG53MHJhRktwalFz
            THM1NjNkQXhvWFhWeGtoRVRINVFEaE0KLS0tIExWNTkyNndqdEZNRXUvYktaeVJH
            UnI5QzJaUXRvR0lGWlc2VjFUQllVNUkKVwYoWyJKWR9WpBij1W+ZEqk3Y5YPE86S
            OGzKvSxetq+zQafWHWraBqJXYAzztrhOnQ334sewQ0YzhSreKCsN4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T17:57:09Z"
    mac: ENC[AES256_GCM,data:QNIvaCvbiS4prmDisLlBpe5doodcMrTgYPTmYR60EYJgmPYvGyzJSN53AdgAUDyK6tcV0mA3RNZMhOUwK4QCG0FTuIKtGAqLKJctZofQQ8B7XkRXWMxjjCi2apXDEKgmRRyQTJukc0It8JqSdL3t/0jDtOgD/aJV7FtDSjprIl0=,iv:98A9zAbJMWTfGAeNJ6skK4x2bBBzOgbPvMfdPv6u2mc=,tag:ICljBnaEx1qH7aaMZ2JZNQ==,type:str]
    version: 3.13.2
