apiVersion: v1
kind: Secret
metadata:
    name: slskd-wireguard
    namespace: transmission
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:7Y46D+XczgevBHzxPnLK0EgP6D5gssdG1/g/feFf9LqhHuq48azoIFHlHIk=,iv:CwB4U+Me7uJdCNDSLV8hAPQo7LiBUe9CkLv6OInI/F4=,tag:Hj9NLlHDtsns/9XHzo1gLg==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:ZiQdc0ti7Q71OpZL7HKApQ==,iv:PT5iUmnD6dk5rsGug3v7SKIW9uJsg6QLOTst9ziKB0c=,tag:elYs/CtAXNxa+9PV7JiL7g==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:SjoWgMFXGcmpSiDObm1NWxx9n5HFQ+YHMjIYYypyHR3oB98VAlOFKsumrns=,iv:Y+1yEtW3baFKMQwHlogrgBpTY528u7EghyhxUNb712I=,tag:KZCrNVfqPkn+1cy70r+H1w==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:EZYECBgjpNOMZqUE8A==,iv:myvN+4xP692g1cl0oDugX1ZYeoNFu12l1s3xaV+AEyA=,tag:8J51FGlk9GBk1ZIIPgPEdw==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:td399Ow=,iv:5Y+LOuFZ/5alQ4rqHGk8eFalx825nozNmAToZ86xE5k=,tag:GPhvOHvZTTYhDdIeC8GOSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NzUySEcyazFDdzlqOGJF
            eGs3UXVTQWlwZmNMeG42UEpJNERqaEU5OVhnClQzb3RlRWY4S3FQQnhtSzR1ZExl
            RTQ4MkdGN3Eza0lISFBQNC9haWt1NzAKLS0tIEdBbGVTVG1OSXdvSStlT2lDZUdF
            UFBxVnZlWG41dC8rbkdGdzJvR1NnK2cKlT8YH/UPYRTzN6TBKxbq2RykAhMimMyh
            nOoyioGS337kGaEYMt61mGXoeyWAIxIySg2UkEovTfST13YxhMXBnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T18:00:39Z"
    mac: ENC[AES256_GCM,data:QRhmrpr39TUVePeyPTLywm823o0aGgGgrwWWm/vTLURAMy23FYJ9NJsMVZ7DfRCi0E38XXtBWHPzFAEhQGcedJIw3z+vp03XWz5t/6JwkHaIxc8HtFBbcLSPTZamEpLmtYXreX79JPWEdGExaTmpLdFqXm1LZIOdsSWcap8g5Z4=,iv:JPZFVvJueLFh6uC0cCTgMLNJwRIkexkIr9RfQY4WCiQ=,tag:NOGlh3cbSYl16/RqgnInmQ==,type:str]
    version: 3.13.2
