apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - postgres-cluster.yaml
  - secrets/postgres-auth.sops.yaml
  - secrets/home-assistant-secrets.sops.yaml
