apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-db
  namespace: home-assistant
spec:
  instances: 1
  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant
      secret:
        name: home-assistant-db-auth
  storage:
    size: 25Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-barman-s3
