apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-local
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual-local
  volumeName: perun-home-assistant-config-local
