apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../authentik
patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: authentik-db
      namespace: authentik
    patch: |-
      - op: add
        path: /spec/storage/storageClass
        value: manual-local
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: authentik
      namespace: authentik
    patch: |-
      - op: replace
        path: /spec/values/server/replicas
        value: 0
      - op: replace
        path: /spec/values/worker/replicas
        value: 0
