apiVersion: v1
kind: Secret
metadata:
  name: ssh-authorized-keys
  namespace: shell
type: Opaque
stringData:
  def4alt.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFh6m4qX4U4sYAI+ngMuLACi4pqSz2pNjdPcB8aEzD6k
