apiVersion: v1
kind: Secret
metadata:
    name: ssh-authorized-keys
    namespace: shell
type: Opaque
stringData:
    def4alt.pub: ENC[AES256_GCM,data:N3pfhh7qzlMhCohdujAC/VTN8QfObOClcEw9xrONXn1/yGyA6357XiB3bUOfkUQsNr2pjiXvBpmMTLa3wWyaIfd27rFhyW0/njeQucY74umk,iv:S1MaQQ3vpnflFd0Po1uZv73c+GwIC36gD56M1r49WlE=,tag:HbYvFldohQAextCRiPOCoQ==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS1hsZ0IyQVFuSjlQSmlW
            clRzU21oZWJsNjR1SFp3WmR5dURLMVAvSXg4CnY0Qy9sakxNbHRPU0orV3NhZjho
            SngwMVpDNXZibnM4TVRMb3ZHWHNwL0UKLS0tIGtzRWNtSVhuZnYwSUF2WVBDZGdM
            ZGJjNlZvQmpiWm10RlJGYXhVaXRWb3MKQtEN9uG85tDWxiobi+NRhaa4zFm4aWGm
            1p8Rg9nMm/gqtiz61IFKv0g5nSWwNzXwxzV0OwH4AN5WiUZP/Vrt3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T18:53:43Z"
    mac: ENC[AES256_GCM,data:8Plzm73Cb4VFj83h56HPO3x7iIYue57cVN9TODkrL/FrHO18WJs+Tkki5DVNjoagn1uHnJ3wapMvoP11/aRKSZMiXLSg7fIeLBXGpwgQ6y0/cBpBIVEYzRPV6NTPXpwHq+G+DcL82KVbHNVw3xx1vBa8uKY3CEVM5Pb1+YiW9HQ=,iv:1jQMmd3SDjXgb4O5Q0LhtasbFScnHt4bUrZHt52jhHk=,tag:DLWBBNgkAvN8V1aA3z6iHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
