apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhelsia-datadir
  namespace: valhelsia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual-local
  volumeName: valhelsia-datadir
