apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - infra.yaml
  - blog.yaml
  - authentik.yaml
  - cnpg-system.yaml
  - glance.yaml
  - paperless.yaml
