apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Startpage
        width: slim
        hide-desktop-navigation: true
        center-vertically: true
        columns:
          - size: full
            widgets:
              - type: server-stats
                title: Server Stats
                servers:
                  - type: local
                    name: Services

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Authentik
                    url: https://auth.def4alt.com/
                  - title: Paperless
                    url: https://papers.def4alt.com/
                  - title: Kaneo
                    url: https://projects.def4alt.com/
                  - title: Immich Photos
                    url: https://photos.def4alt.com/
                  - title: Grafana
                    url: https://grafana.def4alt.com/
                    icon: si:grafana
                  - title: Pi-hole
                    url: https://pihole.def4alt.com/
                  - title: Prometheus
                    url: https://prometheus.def4alt.com/
                    icon: si:prometheus
                  - title: Home Assistant
                    url: https://home.def4alt.com/

              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters
