apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Startpage
        width: slim
        hide-desktop-navigation: true
        center-vertically: true
        columns:
          - size: full
            widgets:
              - type: search
                search-engine: kagi
                new-tab: true
                placeholder: Search the homelab or the wider web
                autofocus: true
                bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: Wikipedia
                    shortcut: "!wiki"
                    url: https://en.wikipedia.org/wiki/Special:Search?search={QUERY}

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Authentik
                    url: https://auth.def4alt.com/
                  - title: DocMost
                    url: https://docs.def4alt.com/
                  - title: Kanboard
                    url: https://boards.def4alt.com/
                  - title: Paperless
                    url: https://papers.def4alt.com/
                  - title: Immich Photos
                    url: https://photos.def4alt.com/
                  - title: Pi-hole
                    url: https://pihole.def4alt.com/
                  - title: Home Assistant
                    url: https://home.def4alt.com/
