apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-data
  namespace: glance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
