apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/namespaces.yaml
  - infra/traefik.yaml
  - infra/cloudflared.yaml
  - infra/tailscale.yaml
  - infra/longhorn.yaml
  - infra/restic.yaml
