apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/namespaces.yaml
  - infra/cert-manager.yaml
  - infra/cert-manager-issuers.yaml
  - infra/traefik.yaml
  - infra/cloudflared.yaml
  - infra/metallb.yaml
  - infra/metallb-config.yaml
  - infra/local-storage.yaml
  - infra/cnpg.yaml
  - infra/authentik.yaml
  - infra/traefik-auth.yaml
  - infra/juicefs.yaml
  - infra/monitoring.yaml
  - apps/blog.yaml
  - apps/glance.yaml
  - apps/paperless.yaml
  - apps/pi-hole.yaml
  - apps/home-assistant.yaml
  - apps/immich.yaml
  - apps/minecraft.yaml
  - apps/jellyfin.yaml
  - apps/prowlarr.yaml
  - apps/sonarr.yaml
  - apps/radarr.yaml
  - apps/transmission.yaml
