apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/namespaces.yaml
  - infra/cert-manager.yaml
  - infra/cert-manager-issuers.yaml
  - infra/traefik.yaml
  - infra/cloudflared.yaml
  - infra/metallb.yaml
  - infra/metallb-config.yaml
  - infra/longhorn.yaml
  - infra/vault.yaml
  - infra/longhorn-config.yaml
  - infra/cnpg.yaml
  - infra/juicefs.yaml
  - infra/authentik.yaml
  - infra/monitoring.yaml
  - apps/pi-hole.yaml
  - apps/home-assistant.yaml
  - apps/paperless.yaml
  - apps/immich.yaml
  - apps/glance.yaml
  - apps/hermes-agent.yaml
  - apps/minecraft.yaml
  - apps/blog.yaml
  - apps/executor.yaml
