apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin
    namespace: livesync
stringData:
    username: ENC[AES256_GCM,data:jfnfYzY=,iv:Q39Y3qfJKriKYL9cOflgiB32AdrP0Saz6fPGS4eHekI=,tag:UrvDnqdzIeFNl47NBbAEBQ==,type:str]
    password: ENC[AES256_GCM,data:8w4+8bgd2o5ahaCusniy/KvTZVAvJgUv,iv:dqb6RQ6zRQVn9pbu0qcXyPyGQFgeIYrfQAczAA7CshM=,tag:yCv4XK68EwtRZiSLQn+udg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXBRSm8zVTgvK0NKK1Ru
            c0tiUFpnVHRoTnFZTGc0dFg5SDhhRHlRQUVRCmp6TE9SQUdQdFVoN3dpUDdsQ3RL
            MVl2enoweWVQMXMyaDcvWmZOL3JkNTQKLS0tIGllVFBTdkd1dm53MndqRDJXSXNO
            SEdBTFAvamxFSmcyZWJEb25KakJBRGMKsZXXYIzBLhr73HW8jkcEPT8huyWuC7hx
            FysFZRZ0PU0u+Z/gpFNjKjZoKs0DnVAj85zxc1YyXQWb90Y3zZS/Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T09:26:56Z"
    mac: ENC[AES256_GCM,data:XGRbxM9fqI6E436YknOTe4xmN9twbSkVXVSNwGEA2FzZiYzVLy6qFDEL8i6GgrFuQQ1q9dzgNTg/oyiw9A806y5h51/p3cNw9BySkhU3XJyMTJ8VPIXHu2dtXVQ3XJPSWA0quKmwP1OL860NoH8fNLpgSZtKYecdyI9OPSrro6Q=,iv:N28YLy/3aGEyvqmeaA1hVCoC0c3V8qU9YpuzNGg9awo=,tag:x3/bSwkfXjh9MxQ8KThhAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
