apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-db
  namespace: linkwarden
spec:
  instances: 1
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-db-auth
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-barman-s3
