apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-rag-cache
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
