apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/hermes-agent-secrets.sops.yaml
  - serviceaccount.yaml
  - configmap-launcher.yaml
  - pvc.yaml
  - deployment.yaml
