apiVersion: v1
kind: Secret
metadata:
    name: navidrome-sync
    namespace: navidrome
type: Opaque
stringData:
    listenbrainz-token: ENC[AES256_GCM,data:fzdP3RqaOTn/93jql04DZWBQWM06Ax9UOJ6qgWVDeJ5HniB2,iv:Cjl6hPpXjbFDnj/YgI6BaczQiXSdKZmOuyd96p45Qdc=,tag:untJzsfZ19ptCYtl5hZY3A==,type:str]
    listenbrainz-username: ENC[AES256_GCM,data:qHaglfJRKw==,iv:4aexLwdCt6gFl9aK/0zdZEoky4k363tUuY8c3zQbI+0=,tag:gIxdCITFKjAQ0dYI03SRKA==,type:str]
    navidrome-username: ENC[AES256_GCM,data:dZ6NHFslJ7xOrYg=,iv:Vd2Ufp2NNgyizH+5cjAJwgZJ6F/h5m3WiTY2YZgtbcM=,tag:zI0cjiw/3zzvPBJiLZtl6g==,type:str]
    navidrome-password: ENC[AES256_GCM,data:MIXGAUE8dbvUeNM=,iv:sdiRMKy0/iPdBlAjcBsrYXGVZF09u/tvdDCcPYKzCHo=,tag:fUBWNWfZ111RRcrRfmJocA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcHpma1hjbUpxdE9BcmVB
            TWtpZlFpTGYxcUE5RnpWOFh1TE5SbGVqczBnClBBVkdHa1dHM2J5Z0NrWk1HeEtN
            R1dDaVNLUUFuTFFVMnZMbVRPZlIwblEKLS0tIHFkU0QrUnE1aUJtSkgwQ3hlRnBY
            RkpabGluaFZodEs1OVpXNjYrR3NUenMKj7sdIboZjGEDT3UwQxvD+f7LPxctk09b
            gHZYTCjXUT9eMiLXAXdv5FlNfRAJHhNLo6uIFxEB9R2kEDCB/GRVSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T16:00:23Z"
    mac: ENC[AES256_GCM,data:fUkaRO0m5/Q8NkPO0YnKW7GLQi1EN6DHlX8tzaDrV4L8CbbZL3tfHa1hRwRqcWwUp/xTyQNLo8SP/lpgEvlHc0qTlVChteBWprVwEUkcYlgs8nxjJD5xUYMA/uzUsml/0hb4ZwvOjHSQR6zJqGnCKTZortlmP0susqrpElSL7gE=,iv:zM/+eX+rB9kCQ5S63XrHs8CaD3E2jatnTFRNcwzt2TM=,tag:9ykMOrUTbPlEzo+LiwmATA==,type:str]
    version: 3.13.2
