apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
  namespace: invidious
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      containers:
        - name: invidious
          image: quay.io/invidious/invidious:latest
          env:
            - name: INVIDIOUS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: invidious-db-auth
                  key: password
            - name: INVIDIOUS_CONFIG
              value: |
                port: 3000
                db:
                  user: invidious
                  password: $(INVIDIOUS_DB_PASSWORD)
                  host: invidious-db-rw.invidious.svc.cluster.local
                  port: 5432
                  dbname: invidious
                check_tables: true
                invidious_companion:
                - private_url: http://localhost:8282/companion
                invidious_companion_key: bayWx608JkTUh70x
                domain: yt.def4alt.com
                external_port: 443
                https_only: true
                hmac_key: 5eb635629d95d15ba907d74a6a87961d115ca59e
                use_pubsub_feeds: true
                use_innertube_for_captions: true
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/v1/stats
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/stats
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi
        - name: companion
          image: quay.io/invidious/invidious-companion:latest
          env:
            - name: SERVER_SECRET_KEY
              value: bayWx608JkTUh70x
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: companion-cache
              mountPath: /var/tmp/youtubei.js
      volumes:
        - name: companion-cache
          emptyDir: {}
