apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invidious
resources:
  - postgres-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secrets/postgres-auth.sops.yaml
  - secrets/wireguard.sops.yaml
