apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlays
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: immich
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/modes/minecraft/immich
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: paperless
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/modes/minecraft/paperless
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: pinchflat
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/modes/minecraft/pinchflat
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: jellyfin
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/modes/minecraft/jellyfin
