apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: immich
    name: immich-db-1
  hostPath:
    path: /var/lib/k8s-local-storage/immich/immich-db
    type: DirectoryOrCreate
