apiVersion: v1
kind: PersistentVolume
metadata:
  name: perun-immich-db-local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: immich
    name: immich-db-local-1
  hostPath:
    path: /var/lib/k8s-local-storage/immich/immich-db-local
    type: DirectoryOrCreate
