apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: jellyfin-config
  hostPath:
    path: /var/lib/k8s-local-storage/transmission/jellyfin-config
    type: DirectoryOrCreate
