apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: juicefs
    name: juicefs-db-1
  hostPath:
    path: /var/lib/k8s-local-storage/juicefs/juicefs-db
    type: DirectoryOrCreate
