apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - pv-pihole.yaml
  - pv-minecraft.yaml
  - pv-monitoring-grafana.yaml
  - pv-home-assistant-config.yaml
  - pv-juicefs-db-local.yaml
  - pv-home-assistant-db-local.yaml
  - pv-immich-db-local.yaml
  - pv-monitoring-prometheus.yaml
  - pv-jellyfin-config.yaml
  - pv-plex-config.yaml
  - pv-transmission.yaml
