apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - pi-hole.yaml
  - minecraft.yaml
  - monitoring-grafana.yaml
  - home-assistant-config.yaml
  - juicefs-db.yaml
  - home-assistant-db.yaml
  - immich-db.yaml
  - monitoring-prometheus.yaml
  - jellyfin-config.yaml
  - prowlarr-config.yaml
  - sonarr-config.yaml
  - radarr-config.yaml
  - transmission.yaml
  - application-data.yaml
  - homelab-tools.yaml
  - navidrome-music.yaml
  - navidrome-data.yaml
  - slskd-config.yaml
  - lidarr-config.yaml
