apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: infra
    name: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0
  hostPath:
    path: /var/lib/k8s-local-storage/infra/prometheus-monitoring-kube-prometheus-prometheus-db
    type: DirectoryOrCreate
