apiVersion: v1
kind: PersistentVolume
metadata:
  name: perun-monitoring-grafana-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: infra
    name: monitoring-grafana-local
  hostPath:
    path: /var/lib/k8s-local-storage/infra/monitoring-grafana
    type: DirectoryOrCreate
