apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinchflat-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: pinchflat-config
  hostPath:
    path: /var/lib/k8s-local-storage/pinchflat/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: youtube-media
  hostPath:
    path: /var/lib/k8s-local-storage/pinchflat/media
    type: DirectoryOrCreate
