apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: prowlarr-config
  hostPath:
    path: /var/lib/k8s-local-storage/transmission/prowlarr-config
    type: DirectoryOrCreate
