apiVersion: v1
kind: PersistentVolume
metadata:
  name: perun-minecraft-datadir-local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: minecraft
    name: minecraft-datadir-local
  hostPath:
    path: /var/lib/k8s-local-storage/minecraft/minecraft-datadir
    type: DirectoryOrCreate
