apiVersion: v1
kind: PersistentVolume
metadata:
  name: perun-plex-config-local
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: plex-config-local
  hostPath:
    path: /var/lib/k8s-local-storage/transmission/plex-config
    type: DirectoryOrCreate
