apiVersion: v1
kind: PersistentVolume
metadata:
  name: perun-radarr-config-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: radarr-config-local
  hostPath:
    path: /var/lib/k8s-local-storage/transmission/radarr-config
    type: DirectoryOrCreate
