apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Retain
