apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: syncthing
    name: syncthing-config
  hostPath:
    path: /var/lib/k8s-local-storage/syncthing/config
    type: DirectoryOrCreate
