apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-local
  claimRef:
    namespace: transmission
    name: transmission-data
  hostPath:
    path: /var/lib/k8s-local-storage/transmission/transmission-data
    type: DirectoryOrCreate
