apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cWqgIfAAlk3vK2RuvDlMSsI9NfX0jN392w==,iv:ZZ7d2l7CYTcxqlknuTSwqeLL1BfZ0WofJPDSa+Har/Q=,tag:70PpyTFvlKlHD0aWau2a/w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:S/Ilpr4M013L0ocY5rEyHlh6vWPUozxo9yTXtE+nkQ==,iv:rr6WIRmMa9xP23Q2vi1g08syfGNYEaaFPKor3D+V2fU=,tag:0k+B5q3e8PwnEXFki3+nRw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:W93PjaS3RXJUAYxOcvyk+1NuKosqBDCV+NTetvzR7o98TjfSU5B1aps=,iv:QZNaYR38WU8zQeHo2Jy8CJy5Gc06N37JUpCPzcwkivo=,tag:2xkyGjjacAI97kNQ9b7X5A==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cUxqdUZlNGovZmNZWkFF
            RitZUzdEdWtXRytVSy80UTFtWXVoeXhkS0NVClNzcFpXT0cwTTU4OHJTYTB5MFBs
            L0RSN1Vqbm5xVUc0OS9UTGNSWFBsdDgKLS0tIEREeHNKM25Vc3FwMkJEME9tT0dL
            d0h0aEg4T0FSUngzUHRud0JqZ2ROeWMKkNo2cdx5gHUMaM4tmN0JO/RnODUdTNSu
            TtKlkRJk6E542p/b0N54qTFJdiRuq1s6xpOrvf+Ut4fW0VDHgRfDfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:39:37Z"
    mac: ENC[AES256_GCM,data:hz0/yqVIVrbY6fUv//DeDmj8Xi2AEkMG09XoUxJPH4pDgLpbhtP8cCk/cpkgbRFeY8bSxSc/UDET2oZhnFekJLGN4Em8+kyqtjF0hKKbusO3WezaxRBnp9jujMRhrHPmBmpt8CtL7HDWsEbzFpceyo1GeR9xDgx/lcqw4n9pMLo=,iv:kB7HXBwkcxaKjohpTqv9GFEWUAFNbRJotmfteqnvJHM=,tag:KzPz55TzGVWre0KbQo6NFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
