apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: infra
data:
  config.yaml: |
    ingress:
      - hostname: boards.def4alt.com
        service: https://traefik.infra.svc.cluster.local:443
      - hostname: home.def4alt.com
        service: https://traefik.infra.svc.cluster.local:443
      - hostname: cloud.def4alt.com
        service: https://traefik.infra.svc.cluster.local:443
      - hostname: papers.def4alt.com
        service: https://traefik.infra.svc.cluster.local:443
      - hostname: photos.def4alt.com
        service: https://traefik.infra.svc.cluster.local:443
      - service: http_status:404
