apiVersion: v1
kind: Secret
metadata:
    name: kaneo-secrets
    namespace: kaneo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IJMCE3A=,iv:wqKiLb1uaoLak0ZhhkH1QvZ5yM6pihIcd2A8q0RROs0=,tag:QVMn1gy0/9hfq0lyO0K/rQ==,type:str]
    password: ENC[AES256_GCM,data:O46Sfx+tpMlwtoQOpCYnn34fyjrjcDJc8RV/Oqzp83A=,iv:e+t9BtjVJSiNYZKN5vtpFedOfXuasyUwl3eEAbo1Uv8=,tag:ZzcdBE2iWEZ4d5BhcpUcXw==,type:str]
    auth-secret: ENC[AES256_GCM,data:txTcSxcFtARXYfZ+sFzKZrZ9lkY6XW7fpt766amzdyyYflDtNMqfZ/QJ7To0YKCr,iv:bGigg7vxmThL0GE8k/Y9tH1PZFQ9sI3MOT+DVyKO/9g=,tag:ijTTeA2uBxCNd8lFvR9TIg==,type:str]
    database-url: ENC[AES256_GCM,data:zNoRl6OrFIxMs35NrwJnVBx7PX69wXswunxhC5aLTDCz8gob1Hwr9tag7tcWpc4ZxT/ZCGS6fPu94434pUPQtQv5qnFuZUgp6ArGwxsqOb+sulqAfefasEf0SrviA1r43qk=,iv:YDoV07LmhbeMvOpR15+8Brz++/4IvRAlksTfo/Bzjd4=,tag:Yk+db12VhBqUU/Ro2s73mw==,type:str]
sops:
    age:
        - recipient: age1843v8f2yesr9gdywuqwrlpfyvhvvnngsrkphks8cgm4rh9aaw94q24x8cz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTVYrR3I5VGhLcEllcVJt
            djR5U2Z0K2NJanJORnIyWVFXSHFteDlYRVNzCk1FWk8vanhXWTk4QWIvdEtFb1E3
            a0ZHdSt2ckhOOFpqYkFITlNlL2h0U0kKLS0tIDZZLzZKSFIvSVRxK0hXMlNDNitu
            M3VUYVZ5SkIxUi9VVVR2ejMrZjRMbGMK4wsBbo8D1AXOybb6R/BP0medkgJwiOih
            ZHBSUgnQ9sNcNzOTmnv+ndXJDutVznwVuL/H/1xUL2+GLK3qVeD1Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T16:12:41Z"
    mac: ENC[AES256_GCM,data:+QKih5k+b/CbSuhkyGNZq0w2EaMcVeN7uL/qzmJwk9nmHz/cR034wwJIF0f5pH3S7AikwqpQwZGvREzVTnqMXYFDqiNWzxqyAu6Du+O0orEKA0k7MtYfqF83CzP+3rhbi51jUgfqA+09lzYP2/yQOoUnRHjFFm0TPbp5qvdetAk=,iv:rGLO1Pqh4s9Vsnq+cb3fx8Luox5z9EZSCZz9+mwdBxo=,tag:+9mB35YNL/7yA/rq/KEiNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
