apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../executor
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: executor
      namespace: executor
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 0
