apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: infra
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:dHlarhw7M4LLN9LHdZHHggW2ZSA78LAg3KQ4URAw6cxuCuz+ChiVhYCK3Dm/u91d1moNCxBZrYMYVTQ91+zGADEwjIf0pQlg+8E7xKzHhcKK0U2u8kAr+Dps0tei2nNaBvuGkJUo3DJ02MPldp0eqfVOUuYap1Lv+a85EnSy+1rDyn1opJHvTlikgSuiZHMY6hff2Y+GcM6b9gpEhwkzYi9iBBq6BUJCxohBrEY0LiaSPq8IcGG80w==,iv:p1yYucfhKlm8PPLMQinS536sbu/yF5yAbxbXXoMBZA0=,tag:J8NvsNDgGffb5yDGPStCog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZjAyM1Q5cHlqazRTZitN
            aWdtUXpXcDMvdnRYbFNuYzB6NXliekliR1N3CldHL0x4L09rQmYvNUZPMzFmNWZh
            ZGVyVTN1eGVHdjR2TExaSU1PTmFiTEUKLS0tIGZvNDA3dUNDbFp5TDJ6ZW5WbG43
            WFpaYjUzTkZYWnRGYTkvb2YyQkxXNVUK9MzkEWDdbJegWdBoXZyOLheQIypwB8bK
            u+3XUcPcSg4fP3o6kO07cnjVYDx6umPEA/aVthtofLhjMBeBAkGZUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-17T16:44:52Z"
    mac: ENC[AES256_GCM,data:LZkLwZpV1dJNWE/46s71DgZLcjagdb5zvVMSnsS3PaIDWNnzD2/aEL3H8dl1mcDFuh+txnhaAGzxD7Mdb24vPpNPyLEpDYyGy0daN0990qy2xTrGcwwA4PHEe8zN9u39bvUtXm9Ch+pcbGfSz72MJsARAc/MW/tkUBQ519LCEoc=,iv:zRoJfeCxNWHqGuWRMNVck77z93EqXq2KBHSsT6wKA9A=,tag:WwZISXvPIVbvF/RvHzOSAg==,type:str]
    version: 3.11.0
