apiVersion: v1
kind: Secret
metadata:
    name: invidious-db-auth
    namespace: invidious
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XvO9K3XbiHRv,iv:MqcswdtU0Bg7CXDYTtj1wJhIsKL/hPGuLRShP/azars=,tag:Gr8zd2LxwZMKqXAhSR91/A==,type:str]
    password: ENC[AES256_GCM,data:UeltC/qcbwwhpZqz9Qa9FEqkiYVK4/g/5CVwbx/Q6uc=,iv:YkXWWJm94fHGwabxK5g2gUU1x/dnA8YMH8eSHr3nfd4=,tag:c3GXZFYYQ0vNDzUbmJVu9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRnpyYVVsSTBnSmx1dFUw
            cmRCU08xWGJQTVhkc0hndjNuTGMvbzRZcmxzClUyRXdvMmo2SGo3eVBaYUl4bzVB
            eCtsV1FZNHIzWERZV214Sm5JSUxiOFEKLS0tIE54RDdKQXBQeFFwTW40cWxJV0xV
            TFYzRUVtSjMzaE90YW9OdFMvNDBYT2MKhz79hE8LnSh2rpWkKWrUBAbflXeXLwsF
            SAE9lXwBReFTZbjGoz3cE3EHlPLKFPz/zDSu49jtkr+zL9e/eTS+zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T05:57:46Z"
    mac: ENC[AES256_GCM,data:QNcxm0MOm11sgOTyYU/7P9RPDsBSieUp3NA9kDRDdzbz6YP+jDXzTkhWmFxkN16XB+EZbDA+tMU1wi59oaasGAdbKa2eKB64sa79qCSbXsjSjOdIYxfDlH5CzVWQ+iE+C1atzQbBsm+e2TUfWSJDysE+8Giw3S4d2uewIHFHq6c=,iv:1AbzsI2oVGwb2iX5QkpGJHAUEa8yGBTOuJbzUjPoOMc=,tag:X/2lzEJkaYoLM+elvq/+Dw==,type:str]
    version: 3.13.2
