apiVersion: v1
kind: Secret
metadata:
    name: invidious-wireguard
    namespace: invidious
type: Opaque
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:U7W4052D+04s0CYaf1UtMIwQXVEh7neeJPkTo9tCdWhY5cX9W1w/PYxqNcc=,iv:P/Ljy8dnFqigdE9TAknB7Vo/7olZBkOu00vQf2MU7KA=,tag:2o+4wSDZ8gkGDS1C93/Srw==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:IwyTF8grlsLLZqf1HgAyGA==,iv:8AZ7swLYluEabqk4xr0xMki4KNgvb3xzcH78+sfHpSw=,tag:ZC+AesyXJ1vZYeA9iJfmDg==,type:str]
    wireguard-public-key: ENC[AES256_GCM,data:Fi8KoIfakQFM8GmAac6cb++/cg4Solk0iD8gAfQXUtri3iuiNgpHJN2IctU=,iv:S54nFo3HmIDctXJ7f5p5SWiHAxotgKQR1dItD9D8qYg=,tag:9rK+jByV7vx7LY+M8pWWow==,type:str]
    wireguard-endpoint-ip: ENC[AES256_GCM,data:Vq0HWWOnvXtpeoPewQ==,iv:cGfF8W8R6zOHqT3xX30vj0awWWGboXJ41XzHebBmEqQ=,tag:+8dEND7Z+9Rt6AxsD/UFnw==,type:str]
    wireguard-endpoint-port: ENC[AES256_GCM,data:UbM3nWE=,iv:L878nia/W/ujVg87QvtwiUhC5Ie/VwCB9XVTT0j6gOc=,tag:c4SG36p2UT4s0MrnyIxpaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZmU2cjNIZXg5bURtekVj
            Y3J6azJlUmMyNW1nSm9yWGI3OHRySXdEV1dZCnlNRlhmZzFmbFcvZHlwczVZZFdH
            bUNnWmFJZy9aWVc1U055SXVNUlNMZjQKLS0tIDltUUFlSGZBQnVMSk91NU9ZUHlB
            bVBxQlZYMlUwbFJxQWlTRlF2S2RFd1kKpNTChfBP4XjNDIq+Dv/Y8QoWpDIwu2JJ
            u5n+JYkl/ajKNlvEjU0QpltY+yl2Qjnu5aFr19ejIOrCsDzq0dEc5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v06e3fzx5mqz3k8y6c0uneyfghzj7qkphxu2vfgm9ajwlwd605usdr69zr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T05:57:46Z"
    mac: ENC[AES256_GCM,data:Q7wDcKfNRyTnU4cgeZZCmnnHKKwNXD7n1fY6odrcjZil2fnGF395PiZGQ86XaZpUt015QpU3Jw9tN9nhT2GwSrvCB6cpv76aEavrqs0fAPyQLQ/0Npak6VEFVdgUkkcep5HIBSeQzov7qEcRnPwSnf+Pdf3+KFEFSA4IaF5h7IU=,iv:JcYQeMugLFrF0AbTnq2C6kFpwUIcD5MQy6vB+OGrC64=,tag:TBZtclKIg5Au3bHXYpmufw==,type:str]
    version: 3.13.2
