apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 5Gi
      limits:
        cpu: 2
        memory: 5Gi
    nodeSelector:
      kubernetes.io/hostname: perun
    startupProbe:
      enabled: true
      failureThreshold: 60
      periodSeconds: 10
    extraPodSpec:
      priorityClassName: minecraft-high
    extraEnv:
      TZ: Europe/Berlin
    persistence:
      dataDir:
        enabled: true
        accessModes:
          - ReadWriteOnce
        Size: 20Gi
        existingClaim: minecraft-datadir
    minecraftServer:
      eula: "TRUE"
      type: PAPER
      version: 5.1.3
      onlineMode: false
      enforceSecureProfile: false
      memory: 4G
      serviceType: LoadBalancer
      servicePort: 25565
      loadBalancerIP: 192.168.88.194
