apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-datadir
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual-local
  volumeName: minecraft-datadir
