apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cnpg-system.yaml
  - authentik.yaml
  - infra.yaml
  - metallb-system.yaml
  - pi-hole.yaml
  - paperless.yaml
  - home-assistant.yaml
  - immich.yaml
  - minecraft.yaml
  - juicefs.yaml
  - glance.yaml
  - blog.yaml
  - transmission.yaml
  - linkding.yaml
  - navidrome.yaml
  - piped.yaml
