apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-cert-manager.yaml
  - namespace-ai.yaml
  - namespace-cnpg-system.yaml
  - namespace-authentik.yaml
  - namespace-infra.yaml
  - namespace-metallb-system.yaml
  - namespace-pi-hole.yaml
  - namespace-paperless.yaml
  - namespace-home-assistant.yaml
  - namespace-longhorn-system.yaml
  - namespace-immich.yaml
  - namespace-minecraft.yaml
  - namespace-juicefs.yaml
  - namespace-glance.yaml
  - namespace-kaneo.yaml
  - namespace-blog.yaml
