apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-cert-manager.yaml
  - namespace-ai.yaml
  - namespace-cnpg-system.yaml
  - namespace-executor.yaml
  - namespace-authentik.yaml
  - namespace-infra.yaml
  - namespace-kan.yaml
  - namespace-metallb-system.yaml
  - namespace-pi-hole.yaml
  - namespace-paperless.yaml
  - namespace-home-assistant.yaml
  - namespace-longhorn-system.yaml
  - namespace-immich.yaml
  - namespace-docmost.yaml
  - namespace-glance.yaml
  - namespace-linkwarden.yaml
