apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole@sha256:f7d1be836e3bc608b56d82fc9904f5a831cdfbc0dc9c6d58f94e4c985c70038b
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: DNS1
              value: "1.1.1.1"
            - name: DNS2
              value: "1.0.0.1"
            - name: DNSMASQ_LISTENING
              value: "all"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-web-password
                  key: password
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
          volumeMounts:
            - name: pihole-etc
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-etc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
