apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: pi-hole
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-pihole-root-redirect@kubernetescrd,infra-authentik-forward-auth@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: pihole.def4alt.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-web
                port:
                  number: 80
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.def4alt.com
