apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - pvc-local.yaml
  - deployment.yaml
  - service-dns.yaml
  - service-web.yaml
  - secrets/web-password.sops.yaml
  - ingress.yaml
